label palla_date_amusement_park_male:
    scene bg amusement
    with fade
    "I'm pretty excited to be getting a chance to visit the Amusement Park."
    "It's not something I get to do that often, so I always savour the opportunity."
    "In fact the only thing on my mind is getting to the gate and into the park itself."
    "But in my hurry to do so, I almost forget the fact that I'm not on my own today."
    "Nope, I'm here on a date with Palla - and I seem to have managed to lose her!"
    "Stopping in my tracks, I cast my gaze around in search of her."
    show palla blank with easeinleft
    "And much to my relief, I see her walking a couple of steps behind me."
    mike.say "Hey, Palla..."
    mike.say "How come you're so far behind?"
    mike.say "Aren't you excited to get in there?"
    "Palla does little more than raise her eyebrows a fraction of an inch in response."
    "In fact she just keep on walking, as confident as if she were on a fashion show catwalk."
    "She doesn't even stop once she catches up with me, meaning that I have to jog to keep up!"
    show palla whining
    palla.say "I find it quite hard to get excited about this kind of thing."
    palla.say "It's all just one massive crowd of people."
    palla.say "All of them milling about and making a racket."
    show palla blank
    mike.say "Huh?"
    mike.say "You make it sound like you don't want to be here!"
    show palla wink
    "Palla gives me a tiny smile the really doesn't tell me anything at all."
    show palla talkative
    palla.say "Oh, if I didn't want to be here, then I wouldn't."
    palla.say "You can be sure of that, [hero.name]."
    palla.say "But you are going to have to try extra hard to impress me."
    palla.say "So just you keep that in mind, okay?"
    show palla normal
    "I nod and then turn my attention to the rides I can see before me."
    "All the time trying to tell myself that it's not that big of a deal."
    "I can impress Palla in a place that's as much fun as this."
    "Of course I can..."
    return

label palla_date_ferris_wheel_male:
    mike.say "How about a ride on the Ferris Wheel, Palla?"
    mike.say "Something nice and gentle to get us in the mood?"
    "Palla doesn't hesitate to walk over to the back of the line."
    "And I take this as a good sign, hurrying over to stand beside her."
    palla.say "At least this one won't shake me up too much."
    palla.say "I just hate the idea of a ride that would turn me upside down!"
    "I can't help frowning at Palla's comment."
    "Because to me, that's all part of the fun of the Amusement Park."
    "And I can't see how Palla's going to have any fun with an attitude like that"
    "But I hold my tongue for the sake of keeping the peace."
    "And soon enough we find ourselves at the front of the line."
    "Palla steps into the gondola and sits down."
    "Then she pats the spot on the seat next to her."
    "And I don't hesitate to hop in and scoot up beside her."
    "The safety bar comes down, and then we start to move."
    "The rise into the air is slow and steady."
    "And the view gets more impressive the higher we go."
    "As usual, the ride stops when we reach the top of the wheel."
    "So I take the chance to check out the view and suggest that Palla does the same."
    mike.say "Pretty spectacular huh?"
    mike.say "Worth the time on the ride just to see all of this."
    palla.say "Hmm..."
    palla.say "It certainly is something."
    "I pause for a moment, waiting for Palla to say more."
    "Because I think the view deserves more than those few words."
    "But when it becomes clear that she's not going to add anything."
    "I decide to leave it well alone."
    "Better to accept what she said than start an argument over what I wish she's said."
    $ reona.love += 1
    $ game.active_date.score += 10
    return

label palla_date_merry_go_round_male:
    palla.say "Oh wow..."
    palla.say "I haven't seen one of those in ages!"
    "As soon as I detect the enthusiasm in Palla's voice, I home in on it."
    "And can you really blame me?"
    "She can be so superior and dismissive that anything positive is impossible to miss."
    mike.say "Huh?"
    mike.say "Are you talking about the Merry-Go-Round?"
    mike.say "The one over there?"
    "Palla nods as she walks over to get a better look."
    "And I keep up with her, eager to see what the fuss is about."
    palla.say "It's just like the ones you see in movies and TV shows!"
    palla.say "All gilded poles and painted horses."
    palla.say "We have to ride it!"
    "It's not like Palla has to sell the idea to me."
    "And I'm nodding away before I even realise it."
    mike.say "Of course, Palla..."
    mike.say "The queue's right here."
    mike.say "Let's get in line."
    "Luckily for us, this isn't one of the more popular rides in the park."
    "That guarantees a short line that soon delivers us to the front."
    "I follow Palla onto the Merry-Go-Round and sit on a horse next to the one she chooses."
    "Then the music begins to play and the ride slowly starts to turn."
    "It picks up some speed along the way, and the horses go up and down too."
    "But the whole thing is pretty sedate by modern standards."
    "All of which makes it odd to see Palla staggering as she gets off afterwards."
    mike.say "Are you okay, Palla?"
    mike.say "You're not going to faint?"
    "Palla shakes her head at this."
    palla.say "No, no..."
    palla.say "I just...think I spent too much time...looking down..."
    palla.say "I'll be fine...I swear."
    "Not wanting to ruin Palla's good mood, I decide to leave it alone."
    "And instead I hope the next ride will be able to prolong it a little."
    $ palla.love += 3
    $ game.active_date.score += 30
    return

label palla_date_haunted_house_male:
    mike.say "We really should do the Haunted House, Palla."
    mike.say "It's one of my all-time favourites!"
    "Palla looks at me with an expression that says she's less than impressed."
    "And she underlines the impression by raising a single eyebrow too."
    palla.say "The Haunted House?"
    palla.say "Really?"
    palla.say "I thought those were for little kids!"
    "I can't help blushing a little as Palla insults me."
    "But then I feel the urge to stand up for myself."
    "And I do the best I can to defend my taste in Amusement Park staples."
    mike.say "You're thinking of the kind of stuff you see on Halloween."
    mike.say "The sanitised stuff they churn out for trick or treating children."
    mike.say "I'll have you know that the Haunted House is for sophisticated adults!"
    "Palla doesn't look like she believes a word of what I just said."
    "But there's now a hint of amusement in her expression too."
    palla.say "Okay, [hero.name]..."
    palla.say "Let's see if you're telling the truth."
    "Oh, so she wants to call my bluff, does she?"
    "Well we'll soon see about that."
    "Taking hold of Palla's hand, I march over to where the queue begins."
    mike.say "You're on, Palla..."
    mike.say "Just don't blame me when you're quivering in terror after we do this!"
    "Once we're in the Haunted House, I lead the way for Palla."
    "I'm trying to keep myself from jumping at the inevitable scares."
    "But at the same time I want to be able to see her jump out of her skin too."
    "This means that I'm not really paying enough attention."
    "And so the scares take the both of us by surprise."
    "Palla and I scream in unison and begin to run through the Haunted House."
    "We don't stop until we make it out of the exit too."
    palla.say "Ah..."
    palla.say "Oh my god..."
    palla.say "Let's never speak of this again!"
    mike.say "That's..."
    mike.say "Urgh..."
    mike.say "That's fine by me!"
    $ palla.love += 2
    $ game.active_date.score += 10
    return

label palla_date_love_boat_male:
    palla.say "Don't tell me, [hero.name]..."
    palla.say "You want to ride the Love Boat?"
    "Of course I do!"
    "Who wouldn't want to ride that thing with Palla?"
    "But that doesn't mean I'm going to be so obvious about it."
    mike.say "The Love Boat?"
    mike.say "Do they even have one of those here?"
    mike.say "Okay, Palla - we can ride it if you like!"
    "I don't think for a minute that my impression of innocence fools Palla."
    "But she doesn't call me out on it, and so we end up joining the queue."
    "As this is one of the older rides, the line is smaller and quicker too."
    "So it doesn't take long for us to get to the front."
    "Palla and I step into the boat before it sets off into the tunnel."
    "And once we're in there, the privacy seems to have an effect on her."
    "Now that there's nobody else watching us, Palla kind of loosens up."
    "I feel her leaning against me, her body relaxing."
    "So much so that I decide it's worth taking a risk."
    "I slide my arm around her shoulder and lean in closer."
    show palla kiss
    $ palla.flags.kiss += 1
    "And much to my delight, I'm rewarded with a kiss."
    "In fact it's one that keeps on going for the duration of the ride."
    "One that makes choosing it well worth my while too."
    hide palla
    show palla normal
    $ palla.love += 2
    $ game.active_date.score += 20
    return

label palla_date_hedge_maze_male:
    mike.say "Let's take a stroll round the Hedge Maze, Palla."
    mike.say "It'll be a chance to have fun and give our brains a work-out too!"
    "Palla looks at me like she would something she found on the sole of her shoe."
    palla.say "Seriously?"
    palla.say "You want to waste time in there?"
    palla.say "It sounds pointless to me!"
    "Despite Palla's lack of enthusiasm, I'm determined to give it a try."
    "Which is why I walk over and join the queue without another word."
    "For a moment she resists, standing with her arms crossed over her chest."
    "But then Palla seems to notice people are starting to stare at her."
    "And not in the way she likes either!"
    "So she shakes her head and hurries over to join me."
    palla.say "Okay, okay..."
    palla.say "We're doing the stupid maze."
    palla.say "I hope you're happy now!"
    "The truth is that I am."
    "At least to begin with, that is."
    "Because I've managed to get Palla into the maze with me."
    "But that happiness soon begins to drain away as we walk around the place."
    "Palla doesn't warm to the idea one bit, instead complaining the whole time."
    palla.say "Urgh..."
    palla.say "This sucks, [hero.name]."
    palla.say "It's so dark and dingy in here."
    palla.say "Hurry up and find the way out."
    palla.say "I want to leave - NOW!"
    "That's just a small selection of what I have to endure as we explore the maze."
    "And so I make every effort to give Palla what she wants."
    "Because it rapidly becomes what I want too!"
    "And once we're out, I make a vow never to do that again."
    "Tricking Palla into doing something might feel like a win."
    "But it's simply not worth dealing with the inevitable fallout."
    $ palla.love -= 2
    $ game.active_date.score -= 20
    return

label palla_date_amusement_ice_cream_male:
    palla.say "Urgh..."
    palla.say "It's so hot here today, [hero.name]!"
    "At the sound of Palla's voice, I turn around to look in her direction."
    "And I can see instantly that she's less than pleased right now."
    mike.say "Oh yeah..."
    mike.say "I guess it is pretty hot today, Palla..."
    mike.say "But it's not like there's anything I can do about that, right?"
    "Palla seems less than impressed with my response."
    "And she underlines this by giving me a disapproving snort."
    palla.say "Hurmph..."
    palla.say "Well I wouldn't have come if I'd known!"
    palla.say "I mean, I want plenty of people to see my outfit."
    palla.say "But not if I'm sweating into it like crazy!"
    "Looking around for any source of potential salvation, my eyes settle on an ice-cream stand."
    "And thinking that could be the answer, I take hold of Palla's hand, pulling her towards it."
    mike.say "Ice-cream, Palla..."
    mike.say "That's the answer!"
    "Palla has no choice but to follow me to the ice-cream stand."
    "But as I order my own ice-cream, she crosses her arms and shakes her head."
    palla.say "Oh no..."
    palla.say "No way!"
    palla.say "I am not eating one of those awful things."
    palla.say "They're full of sugar and chemicals."
    palla.say "And what if it ends up all down my clothes, huh?"
    palla.say "Did you ever think of that?"
    "I can feel myself cringing as Palla berates me."
    "Not least because I already have my ice-cream in my hand."
    "So all I can do is kind of shrug as I start to lick away at it."
    "Then walk off feeling the sensation of her eyes, staring a hole in the back of my head."
    $ palla.love -= 2
    $ game.active_date.score -= 20
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
