label scottie_date_amusement_park_female:
    scene bg amusement
    show scottie sad
    with fade
    "I've been looking forward to visiting the Amusement Park for what feels like forever."
    "And now that the big day's finally here, nothing's going to get in the way of me having fun!"
    "Not even the dumb hunk of prime beef that's deliberately lagging behind me right now."
    show scottie surprised
    scottie.say "[hero.name]..."
    scottie.say "Slow down already!"
    scottie.say "You're gonna leave me behind!"
    show scottie sad
    "Urgh!"
    "As if the thought hadn't already occurred to me."
    "Stopping is the last thing that I want to do."
    "But I feel like I have to at least look like I'm making an effort."
    "After all, Scottie and I are supposed to be on a date."
    bree.say "Okay, Scottie, okay."
    bree.say "But this is the last time that I stop to let you catch up."
    bree.say "From now on, you need to move your ass faster!"
    "Scottie looks less than pleased with my ultimatum."
    "But I can see that he's not about to challenge me on it."
    "Not when the alternative is to have me walk off and leave him on his own."
    show scottie happy
    scottie.say "Alright, [hero.name]..."
    scottie.say "But I'm doing this under a dress!"
    show scottie normal
    "Scottie seems to think that I should know what he means."
    "So he doesn't look pleased when I stare at him in confusion."
    bree.say "Huh?"
    bree.say "What the actual fuck are you talking about?"
    show scottie joke
    scottie.say "HAH!"
    scottie.say "You never heard of that, did you?"
    scottie.say "And people are always calling me dumb!"
    show scottie normal
    "I narrow my eyes and frown at Scottie."
    "And all the time I'm trying to figure out what he's gibbering about."
    "But then it hits me."
    bree.say "Wait..."
    bree.say "You mean 'under duress'?"
    bree.say "Oh, Scottie - you really are dumb!"
    show scottie embarrassed
    scottie.say "Wait..."
    scottie.say "I thought that was a smart thing to say?"
    "I shake my head as I walk into the park."
    "And Scottie comes scurrying after me, still asking what he did wrong."
    return

label scottie_date_ferris_wheel_female:
    bree.say "How about a ride on the Ferris Wheel, Scottie?"
    "I'm expecting Scottie to take a massive dump on the idea."
    "So when I hear nothing at all from him, it comes as a surprise."
    bree.say "Scottie!"
    bree.say "Are you even listening to me?"
    "I turn to glance in Scottie's direction."
    "And I'm just in time to see him look up from his phone."
    scottie.say "Huh?"
    scottie.say "Erm..."
    scottie.say "Yeah, [hero.name]...whatever."
    "Scottie keeps on staring down at his phone as we join the line."
    "And he only looks up again once we make it to the front of the queue."
    "Soon enough we're jumping into the gondola and making ourselves comfortable."
    "I mean to check that he's not still on his phone before the ride starts."
    "But when it jerks and begins to rise into the air, I find myself getting distracted."
    "With every foot that we go up, the view just gets better and better."
    "So by the time we get to the top, it's kind of breath-taking."
    "I can't help jabbing Scottie with my elbow."
    bree.say "Isn't this great?"
    bree.say "You must be able to see for miles up here!"
    scottie.say "Yeah, [hero.name]..."
    scottie.say "You're right..."
    scottie.say "I totally agree with whatever you just said..."
    "There's something weird about the way Scottie's talking."
    "Almost like he's not actually on the same page as me."
    "And when I turn to look at him again, I can see why."
    bree.say "Are you kidding me?!?"
    bree.say "Will you put that damn thing down for two seconds?"
    "Scottie looks guilty as he tries to hide his phone."
    "But by now I'm pretty mad, and I get the drop on him."
    "Before he can stop me, I pluck the phone out of his hand."
    "Then I dangle it over the edge of the gondola."
    scottie.say "HEY!"
    scottie.say "Have you lost it completely?"
    scottie.say "What are you doing with my mobile?"
    bree.say "You're going to look at the view with me, Scottie."
    bree.say "And you're going to enjoy it too."
    bree.say "Or else I swear I'll drop this thing!"
    "Scottie grumbles and groans for the rest of the ride."
    "But he also does as he's told."
    "And I seriously think about dropping his phone and claiming that my hand slipped."
    "Though I somehow manage to resist the temptation."
    $ scottie.love -= 2
    $ game.active_date.score -= 20
    return

label scottie_date_merry_go_round_female:
    "Scottie stops in his tracks and stares at the ride in front of him."
    "I see that it's the Merry-Go-Round, one of those classic carousels."
    "The exact kind that I have so many great memories of riding as a kid."
    "I'm about to suggest that we ride it, but Scottie speaks up first."
    scottie.say "Ha!"
    scottie.say "Look at that old pile of crap!"
    scottie.say "What kind of a loser would want to ride that thing?"
    "Normally I can ignore most of Scottie's boorish comments."
    "But for some reason, this one flies straight up my ass."
    "So I grab hold of his hand, dragging him towards the ride."
    bree.say "This kind of loser!"
    scottie.say "What the..."
    scottie.say "[hero.name], wait!"
    scottie.say "You might be a loser - but I'm not!"
    "Scottie keeps on protesting with all of his might."
    "But I'm not listening to a word he says."
    "Instead I hustle him over to the Merry-Go-Round."
    "And as there's no queue for the ride, I push him straight onto it."
    "I have to let go of Scottie to climb onto one of the horses."
    "As soon as I do so, he sees a chance to escape."
    scottie.say "Ha!"
    scottie.say "See you later, [hero.name]!"
    scottie.say "Whoa...what the..."
    "Before Scottie can make good on his plans, the ride starts to move."
    "This sends him swaying and staggering, and for a moment I think he's going to fall off."
    "But then Scottie makes it to the nearest horse, grabbing hold of it and clinging on."
    "That means I have the pleasure of watching him do the same for the duration of the ride."
    "And by the time it comes to a halt, he looks pale as a sheet."
    bree.say "Erm..."
    bree.say "Scottie?"
    bree.say "Are you okay?"
    scottie.say "Urgh..."
    scottie.say "I think I'm gonna puke!"
    $ scottie.love -= 1
    $ game.active_date.score -= 10
    return

label scottie_date_haunted_house_female:
    scottie.say "Whoa..."
    scottie.say "Erm..."
    scottie.say "What was that?!?"
    "For a moment I have no idea what Scottie's talking about."
    "He seems to have heard something that's put the wind up him."
    "But all I can hear is the sound of people screaming with delight."
    "That and the music of all the rides around us too."
    "You know, the usual sounds of the Amusement Park."
    bree.say "What are you talking about, Scottie?"
    bree.say "I don't hear anything weird."
    "Just then there's the sound of a cry."
    "But it's not like the ones coming from the people on the rides."
    "Instead it's deep, creepy and almost blood-curdling."
    scottie.say "That's what I'm talking about, [hero.name]!"
    scottie.say "What even is that?!?"
    "I don't hesitate to answer the question."
    "Because I recognise it straight away."
    bree.say "Oh, that's just the Haunted House."
    scottie.say "Haunted House?"
    bree.say "Yeah, right over there, see?"
    "Scottie sees the attraction in question."
    "And the sight of it doesn't seem to reassure him at all."
    scottie.say "Oh, no way!"
    bree.say "Wait a minute, Scottie..."
    bree.say "You aren't scared, are you?"
    "At the mere mention of the word, Scottie stiffens right up."
    scottie.say "What?"
    scottie.say "No, of course not!"
    scottie.say "None of that stuff is even real anyway."
    "I smile as an evil scheme pops into my head."
    "And without explanation, I begin to walk towards the Haunted House."
    scottie.say "Where are you going, [hero.name]?"
    bree.say "To join the queue, of course."
    bree.say "That is, unless you really are too scared to go inside?"
    scottie.say "No way!"
    scottie.say "I'll go in there..."
    scottie.say "Just you wait and see."
    "Scottie keeps on getting more nervous the closer we get to the entrance."
    "And by the time it's our turn to go inside, he's practically shaking."
    "But when the moment comes, he does the best he can to stand up straight."
    "Then he strides inside, holding it together until the first thing leaps out at him."
    scottie.say "AARGH!"
    scottie.say "[hero.name]..."
    scottie.say "Save me!"
    "With that, Scottie turns and runs off through the rest of the Haunted House."
    "I'm forced to follow on his heels, doing the best I can to keep up."
    "But it's not the running that's the hardest thing, it's trying to stop laughing."
    "By the time we come out of the exit, Scottie's shaking with fear."
    "And I'm just as helpless as he is, doubled over with laughter instead."
    $ scottie.love -= 2
    $ game.active_date.score -= 20
    return

label scottie_date_love_boat_female:
    bree.say "Let's do the Love Boat next, Scottie."
    scottie.say "Huh?"
    scottie.say "What's the Love Boat?"
    "I point out the ride in question, and Scottie looks in that direction."
    "But I don't give him anymore details than that."
    "Because everyone knows what the Love Boat is, right?"
    scottie.say "I like the sound of that, [hero.name]!"
    scottie.say "Plus the line looks really short."
    "Taking all of this as a good sign, I lead Scottie over to the ride."
    "We join the back of the line, and pretty soon we're gettin into a boat."
    "But that's when the first problems begin to present themselves."
    bree.say "Come on, Scottie..."
    bree.say "What are you waiting for?"
    "Scottie looks puzzled as he finally steps into the boat."
    scottie.say "Is this a rowing boat or something?"
    scottie.say "How's that going to be any fun?"
    "By now the boat's started to move off."
    "And we're headed into the darkness of the tunnel."
    bree.say "This is the Love Boat, not the river rapids."
    bree.say "It's like a slow, romantic voyage in the dark."
    bree.say "You know, with just the two of us?"
    "At this, the look on Scottie's face becomes one of horror."
    scottie.say "Slow?"
    scottie.say "Romantic?"
    scottie.say "The two of us?!?"
    scottie.say "Aw man - this is going to suck!"
    "Scottie proceeds to make sure that the ride does just that."
    "As he spends the rest of it leaning off the side of the boat."
    "Just trailing a hand in the water as he sulks away."
    "So by the time it's finally over, I wish I'd never suggested it."
    $ scottie.love -= 2
    $ game.active_date.score -= 20
    return

label scottie_date_hedge_maze_female:
    bree.say "Come on, Scottie..."
    bree.say "I want to go do the Hedge Maze."
    "Scottie groans and rolls his eyes."
    scottie.say "Eurgh..."
    scottie.say "Do we have to, [hero.name]?"
    scottie.say "That sounds so boring!"
    "I do the best I can to ignore Scottie's negativity."
    "And instead of engaging with him, I make straight for the attraction."
    "Once there, I join the back of the line and wait for him to join me."
    "Since Scotties only alternative would be to wait it out alone, he soon gives in."
    "But that doesn't stop him from muttering to himself the whole time we're waiting."
    "When our turn comes round, I walk straight into the maze, not waiting for him to follow."
    scottie.say "Hey!"
    scottie.say "Wait for me!"
    "I've gone a few steps into the maze when Scottie catches up to me."
    scottie.say "So we're in the maze."
    scottie.say "Are you happy now?"
    "Without offering Scottie an answer, I turn and dash off."
    "And the move is so unexpected that I'm gone before he can even react."
    scottie.say "B...[hero.name]?"
    scottie.say "Where are you going?"
    scottie.say "Wait for me!"
    "I can still hear Scotties cries as I weave my way deeper into the maze."
    "But I don't think of stopping for an instant."
    "Let him find his own way out of here."
    "I think that's suitable punishment for the way he's been behaving."
    "While I find my way to the exit with ease, Scottie doesn't have the same luck."
    "Instead I get the pleasure of listening to him whining his way around the entire thing."
    "And when he finally slinks out, he looks more than a little defeated."
    "Which I take as proof that he's been suitably punished."
    $ scottie.love += 1
    $ game.active_date.score += 10
    return

label scottie_date_amusement_ice_cream_female:
    scottie.say "Urgh..."
    scottie.say "Oh man..."
    scottie.say "How can it be this frickin hot?!?"
    "I can kind of empathise with how Scottie's feeling."
    "Because it is really crazy hot right now."
    "And the sun's been beating down on us all day."
    bree.say "I know, Scottie..."
    bree.say "You got any ideas to fix it?"
    "Scottie looks at me with what seems to be terror in his eyes."
    "And much to my dismay, he shakes his head."
    scottie.say "No way, [hero.name]..."
    scottie.say "The sun's totally baked my brain!"
    "I think about making a sarcastic comment."
    "But the I see an ice-cream stand up ahead."
    bree.say "I know..."
    bree.say "Ice-cream!"
    scottie.say "Whoa, [hero.name]..."
    scottie.say "You're a genius!"
    "I lead the way to he ice-cream stand and Scottie follows behind me."
    "Then we queue up and wait patiently for it to be our turn."
    "Once we have our order, I take a small lick, keen to pace myself."
    "But Scottie throws caution to the wind, digging into his like crazy."
    bree.say "Erm..."
    bree.say "Scottie..."
    bree.say "You might want to slow down, yeah?"
    bree.say "If not, you could get..."
    scottie.say "AAARRGH!"
    scottie.say "Brain freeze!"
    bree.say "Ah well..."
    bree.say "At least it's proof that you actually have one, I guess."
    $ scottie.love += 1
    $ game.active_date.score += 10
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
