label kleio_date_amusement_park_male:
    scene bg amusement
    show kleio b normal
    with fade
    "I'm always excited at the prospect of going to the Amusement Park."
    "But the problem is that today I face the prospect of going there with Kleio."
    "And she can be notoriously prickly when it comes to the idea of having fun."
    "So that means I can't help casting glances in her direction as we walk in through the gate."
    "And of course, that's something Kleio soon picks up on."
    show kleio surprised
    kleio.say "What's the problem, Loverboy?"
    kleio.say "Why are you staring at me, huh?"
    show kleio upset
    mike.say "Staring at you?"
    mike.say "Who's staring at you?"
    mike.say "I'm not staring at you!"
    "In response to this, Kleio fixes me with a stare of her own."
    "And it's more than enough to call my bluff."
    mike.say "Okay, okay..."
    mike.say "I'm just worried that this isn't going to be your kind of place, Kleio."
    show kleio talkative
    kleio.say "What's that supposed to mean?"
    kleio.say "I'm not the kind of person that likes to have fun?!?"
    show kleio annoyed
    "I shake my head vigorously, keen to dismiss the idea."
    mike.say "Of course not, Kleio..."
    mike.say "It's just you're more of a rebel, you know?"
    mike.say "Like, you tend to see through stuff like this."
    show kleio bbis seductive
    "By way of an answer, Kleio wraps her arm in mine."
    "And then she starts to pull me towards the rides."
    show kleio bbis happy
    kleio.say "Is that so?"
    kleio.say "Well then I'm gonna show you, [hero.name]."
    kleio.say "I'm gonna show you just how much fun a rebel can be!"
    return

label kleio_date_ferris_wheel_male:
    mike.say "There's the Ferris Wheel, Kleio."
    mike.say "How about we ride that?"
    "As soon as I mention the words Ferris Wheel, Kleio rolls her eyes."
    "And I can see that she's fighting the urge to piss all over the idea."
    "But somehow she manages to push down her instinctive bile."
    kleio.say "If that's what you want."
    kleio.say "Then lead the way."
    "I don't want to make the mistake of questioning Kleio's response."
    "As forced as it seems to be, I just take it at face value."
    "And soon enough we're standing in the queue for the ride."
    "Luckily for us it's not too long, so we're soon at the front."
    "Then we get shown to one of the gondolas and begin to ascend."
    mike.say "Will you just look at that view, Kleio..."
    mike.say "Isn't it impressive?"
    "Kleio answers me in her typically sarcastic tone."
    kleio.say "Whoo..."
    kleio.say "Yay..."
    kleio.say "We're going up in the air - how amazing!"
    "It's only when we get to the top and the ride stops that her mood changes."
    "Now she's leaning over the side of the gondola, staring down at the ground."
    "I feel a sense of relief, thinking that she's finally showing an interest."
    kleio.say "Oh man..."
    kleio.say "I could totally spit on that guy's head!"
    kleio.say "Watch this, [hero.name]!"
    mike.say "What?!?"
    mike.say "Kleio, stop that!"
    "I pull Kleio back into the gondola, foiling her attempt to spit over the side."
    "She crosses her arms over her chest, already beginning to pout."
    kleio.say "Aww, man!"
    kleio.say "You're no fun."
    $ kleio.love -= 2
    $ game.active_date.score -= 20
    return

label kleio_date_merry_go_round_male:
    mike.say "What about the Merry-Go-Round, Kleio?"
    mike.say "The line looks pretty short."
    "Kleio looks over at the ride in question."
    "And then she lets out a snort of laughter."
    kleio.say "Hah!"
    kleio.say "Of course it is, [hero.name]."
    kleio.say "That's because it's for little kids!"
    "I shake my head, dismissing Kleio's explanation."
    "And I start to walk over to the back of the queue."
    mike.say "It's not for kids, Kleio..."
    mike.say "There'd be a sign up if it was."
    mike.say "Come on, I say we ride it."
    "Kleio shakes her head as she follows in my wake."
    "And within minutes we're working our way up the queue."
    "Like I said, the line is short."
    "So it doesn't take us long to get to the front."
    "Then we get on the ride and pick our spots."
    "I keep shooting smiles at Kleio as the ride starts up."
    "But no matter what I do or how fast it goes, nothing seems to help."
    "All the time the ride is in motion, Kleio looks pretty bored."
    "And by the time we're getting off the Merry-Go-Round, it's obvious."
    "She didn't like that one bit."
    mike.say "Erm..."
    mike.say "What do you think, Kleio?"
    mike.say "It's a classic, right?"
    kleio.say "I don't want to talk about it, [hero.name]."
    kleio.say "So don't ever mention it again, okay?"
    $ kleio.love -= 0
    $ game.active_date.score -= 0
    return

label kleio_date_haunted_house_male:
    mike.say "Ooh..."
    mike.say "Look, Kleio..."
    mike.say "The Haunted House!"
    "Kleio follows my gaze, taking in the frontage of the ride in question."
    "Then she turns to look at me, seemingly puzzled by my enthusiasm."
    kleio.say "Ah, yeah..."
    kleio.say "I can see what it is for myself."
    kleio.say "What's with all the excitement?"
    "I look from Kleio to the Haunted House and back again."
    mike.say "Erm..."
    mike.say "It's scary and full of spooky stuff."
    mike.say "Aren't you into all of that?"
    kleio.say "What do you think I am?"
    kleio.say "A goth?"
    "By now I've managed to walk Kleio into the queue."
    "And we're steadily approaching the front of the line."
    "Which means that Kleio finds herself inside before she knows it."
    mike.say "Come on, Kleio..."
    mike.say "We have to go around the Haunted House now!"
    mike.say "We can't push our way back down the line."
    kleio.say "The hell we can't!"
    "I grab hold of Kleio's hand before she can make good on her threat."
    "And then I pull her into the Haunted House behind me."
    kleio.say "What the fuck?!?"
    "What follows is a pretty quick trip around the Haunted House."
    "I keep on pulling Kleio along as scares in the place go off around us."
    "And more than once she manages to land a punch or kick on whatever pops out."
    "Every time I find myself hoping it was just a dummy or a puppet."
    "Because if there was a person in there, then they just got hurt pretty bad!"
    "Once we're outside, Kleio yanks her hand out of mine."
    "And then she shoots me a mean glance."
    "One that makes me vow never to take her into a Haunted House again."
    $ kleio.love -= 0
    $ game.active_date.score -= 0
    return

label kleio_date_love_boat_male:
    kleio.say "Ha..."
    kleio.say "This looks like a pretty lame ride!"
    kleio.say "Don't tell me, you want to ride it?"
    "I see that Kleio's talking about the Love Boat."
    "And instantly I forget about her running it down."
    "Instead I'm thinking of all the possibilities it offers."
    mike.say "It's not lame, Kleio..."
    mike.say "It's a classic!"
    mike.say "Come on, I'll prove it to you..."
    "Before Kleio can object, I walk over and join the queue."
    "Which kind of leaves her with no choice but to join it too."
    "Luckily for me the line isn't too long, so the wait is short."
    "So we soon find ourselves stepping into a boat."
    kleio.say "Boring wait, boring boat..."
    kleio.say "Odds are that it's going to be a boring ride too."
    mike.say "Just give it a chance, Kleio."
    mike.say "That's all I ask."
    "The boat moves off into the gloomy tunnel."
    "And as soon as I think it's safe, I make my move."
    show kleio kiss
    $ kleio.flags.kiss += 1
    "Sliding my arm around Kleio's shoulder, I lean in for the kiss."
    "Much to my size, she's very much up for it."
    "And we spend the rest of the ride locked in a pleasant embrace."
    "So once we're getting out at the other end, I expect her opinion to have changed."
    mike.say "You see?"
    mike.say "Pretty good, right?"
    kleio.say "Nah..."
    kleio.say "It was lame as hell!"
    kleio.say "Next time you want to swap spit, do it in public!"
    kleio.say "And not on a boring-ass ride."
    $ kleio.love -= 2
    $ game.active_date.score -= 20
    return

label kleio_date_hedge_maze_male:
    kleio.say "Huh..."
    kleio.say "They have a Hedge Maze!"
    "I'm more than a little surprised to hear the interest in Kleio's voice."
    "And so I decide to jump on it without really thinking things through."
    mike.say "They do?"
    mike.say "Then we should totally go in there, Kleio."
    kleio.say "Okay, [hero.name]..."
    kleio.say "If you really want to wander around a load of hedges!"
    "I shake my head at Kleio's characteristic disdain."
    "And I hurry over to join the queue."
    "All the time becoming more sure of how I can get my revenge."
    "Because after all, this is a maze."
    "And if she needs me to find her way out of it..."
    "Well, let's just say someone could be forced to apologise before that happens!"
    "As soon as we're inside the maze, I start trying to get us lost."
    "But at the same time I do the best I can to remember the route too."
    "I'm feeling pretty confident in myself to begin with."
    "Though I soon get the sinking feeling that I really am becoming lost!"
    mike.say "This way..."
    mike.say "Erm, no..."
    mike.say "Maybe we need to double-back on ourselves?"
    kleio.say "Are you ready to give it up, [hero.name]?"
    kleio.say "To admit that you need my help?"
    "All I can do is nod meekly."
    "And in response to this, Kleio takes hold of my hand."
    "Then she leads me quickly and confidently to the exit of the maze."
    mike.say "Wow..."
    mike.say "How..."
    mike.say "How did you?!?"
    "Kleio shrugs nonchalantly, but her expression is extremely smug."
    kleio.say "I dunno..."
    kleio.say "I just always had a gift for that kind of thing."
    kleio.say "Comes in handy on very rare occasions."
    $ kleio.love += 2
    $ game.active_date.score += 20
    return

label kleio_date_amusement_ice_cream_male:
    kleio.say "Fuck it..."
    kleio.say "I'm sweating my ass off here!"
    "I look up to see Kleio wiping sweat from her forehead."
    "And I know that I should be offering up a potential solution."
    "Or at least being sympathetic to her plight, as a good friend would."
    "But instead I find myself staring at the way she's almost glistening in the sun."
    mike.say "Oh..."
    mike.say "Oh yeah!"
    kleio.say "Are you..."
    kleio.say "Are you perving on me right now?"
    "The accusation snaps me out of it straight away."
    "And I go from lusting to lying in the blink of an eye."
    mike.say "Who me?!?"
    mike.say "No way, Kleio!"
    mike.say "I was just thinking, that's all."
    kleio.say "And what's did you come up with, huh?"
    kleio.say "What's your answer, Loverboy?"
    mike.say "Ice cream?"
    mike.say "We could get ice-cream?"
    "For a moment Kleio looks like she's going to laugh in my face."
    "But then she tilts her head on one side, actually considering it."
    kleio.say "Huh..."
    kleio.say "I could really go for an ice-cream."
    "Kleio holds out her hand for me to take."
    "And then we walk over to join the queue."
    "It doesn't take long for us to get our ice-creams."
    "And then the most amazing thing happens."
    "Kleio goes totally quiet as she licks away."
    "Which means that we enjoy them in a pleasant silence."
    "And I can go back to stealing longing glances at Kleio too."
    $ kleio.love += 2
    $ game.active_date.score += 20
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
