label audrey_use_condom:
    $ result = randint(1, 5)
    if game.room == "audreybedroom":
        mike.say "Stay right where you are, Audrey."
        "Audrey's eyes are already beginning to glow with anticipation as she waits for what's coming next."
        "But the moment I mention anything other than getting straight down to it, she looks puzzled."
        audrey.say "Huh?"
        audrey.say "What's the matter, [hero.name]?"
        audrey.say "Did I do something wrong?"
        "I'm shaking my head as I climb off the and head towards my bedside table."
        mike.say "Oh, no way, Audrey..."
        mike.say "Just trust me, this won't take a second."
        "With that I hurry over to the pile of my clothes on the floor by the bed."
        "And when I turn back around, she can clearly see that condom I'm holding in my hand."
        audrey.say "Oh yes..."
        audrey.say "That's such a good idea!"
        "I nod my head at the way Audrey's suddenly changed her tune."
        "And I hurry to get back to the bed, as I want to get down to it too."
        "Together we open the packet, putting it on as quickly as we're able."
        "Then we're ready to get started for real."
    elif result == 1 and game.room == "bedroom1":
        "I ignore Audrey's words for a moment, as I reach onto the bedside table."
        "And when she twists her face into an irritated expression, I hold up a condom as way of explanation."
        "She shrugs in response and nods, admitting that I'm in the right for once."
        "And then she lies back and waits, as I put the thing on."
    elif result == 2 and game.room == "bedroom1":
        "And I decide that I'm going to give her just what she wanted, but on my own terms."
        "But that's still no excuse not to take the necessary precautions first."
        "And so, with my free hand, I reach for one of the condoms on the bedside table."
        "If she even notices the time it takes me to do this and put it on, Audrey doesn't say so."
    elif result == 3 and game.room == "bedroom1":
        "I hold up a hand, letting her know that I need her to hold on a second."
        "And then I reach for the bedside table, grabbing a condom."
        "Audrey looks annoyed at the hold-up, but nods all the same."
        "I waste not time in putting it on, eager to get things started."
    elif result == 4 and game.room == "bedroom1":
        "But then something important occurs to me."
        mike.say "Hold on a second, Audrey."
        mike.say "We should really use a condom!"
        audrey.say "Oh shit!"
        audrey.say "You're right, [hero.name]!"
        audrey.say "You've got one, right?"
        "I reach for the bedside table, finding one with relative ease."
        mike.say "There you go, Audrey."
        "Audrey takes the condom and tears it open without hesitation."
        "Then she smooths it down over my cock."
        audrey.say "Okay, we're all set!"
    else:
        "But the one thing I always do is play it safe."
        "And so I hold a hand up to stop Audrey in her tracks."
        "Of course, she instantly looks more than a little annoyed."
        "But then she sees me wave a condom in front of her face."
        "And she nods hastily, urging me to get on with it."
        "All that takes is a couple of seconds, and we're ready to go!"
    return
