label amy_use_condom:
    "Suddenly it dawns on me that I've forgotten something, and I stop in my tracks."
    "Amy seems to notice it too, looking me straight in the eye and waiting for an explanation."
    amy.say "What's up, [hero.name]?"
    mike.say "Condom, Amy!"
    mike.say "We need to use one..."
    "Amy nods in agreement as I go to grab one."
    "Once I have it, she waits patiently for me to put it on."
    "Then we're good to go."
    "Everything is falling into place, and I'm more than ready to go."
    "Amy seems to be on the same page as me too, urging me on."
    "In fact, she seems to want it almost as much as me!"
    "A fact that makes me all the more eager to get going."
    "So there's nothing that can stop me now!"
    return
