label kat_use_condom:
    "I feel one hundred percent ready to go."
    "And Kat looks like she's in the same place too."
    "But then something pops into my mind."
    "And I realise we're not ready after all!"
    mike.say "Wait a sec, Kat..."
    kat.say "Huh?"
    kat.say "What's up?"
    mike.say "We need to use a condom!"
    mike.say "I can't believe I almost forgot!"
    "Kat's eyes go wide with surprise at this."
    "And I can tell that she'd forgotten too."
    "She nods as I hurry off to find a condom."
    "And then all it takes is a few moments to get it on."
    "Once that's done, we're good to go!"
    return
