label master_date_amusement_park_female:
    scene bg amusement
    show master normal
    with fade
    "I have to admit that I feel kind of nervous taking the Master to the Amusement Park."
    "Sure, he seemed pretty keen to come when I asked him."
    "And right now he's trotting along happily beside me as we walk into the place."
    "But I'm still worried that this isn't going to be his kind of thing."
    "I mean, most of the people around us are young enough to be his grandchildren!"
    bree.say "So..."
    bree.say "Are you still sure that you're up for this?"
    bree.say "Like, you wouldn't prefer to go for a long stroll or something?"
    "The Master chuckles and shakes his head at the question."
    show master happy
    master.say "Ho, ho, ho!"
    master.say "Are you worried that I'm going to have a funny turn?"
    master.say "Maybe break one of my brittle old bones?"
    show master normal
    "I can already feel myself starting to blush."
    "As the old man hits me right where it hurts with his own questions."
    bree.say "No!"
    bree.say "Of course not, Master..."
    bree.say "It's just that..."
    "The Master cuts me off before I can come up with a suitable excuse."
    show master happy
    master.say "I assure you, my dear..."
    master.say "I'm fitter than most of the people you see around you!"
    master.say "How many of them can say they're a master of the martial arts, eh?"
    show master normal
    "I nod at this, already keen to change the subject and move on."
    bree.say "Okay, okay..."
    bree.say "Let's just get into the park and onto some rides."
    "The Master nods and smiles at this, as if the matter is settled."
    "So I decide to take the same approach, and think no more of it."
    return

label master_date_ferris_wheel_female:
    bree.say "You want to ride the Ferris Wheel, Master?"
    bree.say "The queue's short and the ride's a gentle one."
    "The Master shoots me a sideways glance at this."
    "Probably mad that I mentioned the ride's lack of intensity."
    master.say "Only if you think I can handle it, my dear."
    master.say "Are you afraid that my ears might pop?"
    master.say "Or that I'm afraid of heights?"
    "I roll my eyes and do the best I can to ignore the jibes."
    "At the same time I walk over and secure us a place in the line."
    "The Master has a triumphant look on his face as he joins me."
    "As if he feels like he's put me in my place."
    "He's still smiling as we step onto the ride and the safety-bar comes down."
    "But as we start to rise into the air, I focus my attention on the view."
    "It's pretty impressive to begin with."
    "And it only gets better as we go higher."
    "By the time we get to the very top, I can see fore miles."
    "So it's very welcome when the wheel stops here for a moment."
    "I turn to see the Master gazing around in amazement."
    "And it feels good to know that he's enjoying the view too."
    bree.say "What do you think, Master?"
    bree.say "This was worth the effort, huh?"
    "The Master nods in agreement, a chilled-out smile on his face."
    master.say "Indeed!"
    master.say "Doesn't it all look so very hazy?"
    master.say "Just like the inside of a cataract!"
    "The smile on my face kind of turns into a rictus grin after that."
    "And I choose to stay silent for the rest of the ride."
    $ master.love += 1
    $ game.active_date.score += 10
    return

label master_date_merry_go_round_female:
    master.say "Oooh!"
    master.say "A Merry-Go-Round..."
    master.say "I haven't rode one of those since I was a boy!"
    "I follow the Master's gaze and take in the ride he's talking about."
    bree.say "Did they really have things like that back then, Master?"
    bree.say "Back when all you had was sticks to rub together to make fire?"
    "The old man's smile quickly turns into a frown."
    "And he begins to march towards the Merry-Go-Round."
    master.say "The cheek of it!"
    master.say "Just how old do you think I am?!?"
    "He joins the back of the line for the Merry-Go-Round."
    "Still lecturing me as we start to move forwards in the queue."
    master.say "I'll show you."
    master.say "I'm still strong enough to ride this thing!"
    "I decide to leave the matter alone after that."
    "So the Master is forced to mutter to himself until we get onto the ride."
    "Then he stalks over to the horse that takes his fancy."
    "And he gets into the saddle with what I have to admit is an agile hop."
    "As the ride starts to move though, he seems to feel the need to do more."
    "So once it's moving, the old man starts to jiggle up and down in his seat."
    "At the same time he's waving a hand in the air."
    "Plus he starts to yell what I guess he thinks are appropriate things."
    master.say "Whoopie!"
    master.say "Yippie whippy whippy!"
    master.say "Look at me - I'm a cowboy!"
    "I have to look away and cover my mouth as I start to snicker."
    "And it looks like a lot of the other people on the ride are doing the same thing."
    "Not that the Master seems to notice, as he just keeps right on going the whole time."
    "When he gets off the Merry-Go-Round, he seems to have gone bow-legged."
    "And he staggers from one side to the other, kind of like a drunken crab."
    "But he seems to be happy, thinking that he's made his point."
    "So I keep quiet, allowing the Master his moment of triumph."
    $ master.love += 1
    $ game.active_date.score += 10
    return

label master_date_haunted_house_female:
    bree.say "Let's do the Haunted House next."
    bree.say "That looks like fun."
    "The Master nods as we walk over to the attraction."
    "But once he sees it up close, he doesn't look convinced."
    master.say "Hmmm..."
    master.say "Are you sure about this?"
    master.say "In my experience, girls are more easily scared than men like me!"
    "I feel the usual twinge of annoyance at the Master's casual sexism."
    "But by now I've learned how to ignore it and just get on with things."
    "So all I do is shake my head."
    bree.say "No need to worry, Master..."
    bree.say "I can call on all the lessons you've taught me."
    bree.say "With that knowledge, I know that I have nothing to fear."
    "The Master nods, obviously gratified that I stroked his ego."
    "But all the same he makes sure to stand in front of me as we stand in the queue."
    "And even when we walk into the Haunted House itself, he insists on going first."
    master.say "Stay behind me, my dear..."
    master.say "I'll lead the way."
    "And so that's how we make our way round the Haunted House."
    "The Master in front with me bringing up the rear."
    "It's annoying to begin with, but that soon changes."
    "Because I realise that the Master isn't as staunch as he claims to be."
    "More than once he lets out a genuine shriek of alarm as something jumps out of the shadows."
    "And he's soon all but running around the place in an effort to get out as soon as possible."
    "Once we're out of there, he's panting and visibly sweating at the effort."
    "But he still manages to straighten himself up and pretend to be in complete control."
    "Although the sight of him scared out of his wits will stay with me for a long time to come."
    show master normal
    $ master.love += 2
    $ game.active_date.score += 20
    return

label master_date_love_boat_female:
    bree.say "I suppose you want to go on the Love Boat?"
    bree.say "Don't you, Master?"
    "The old man looks up with interest when I mention the ride."
    "But once he sees what it actually entails, he frowns."
    master.say "A wooden boat?"
    master.say "In a darkened tunnel?"
    master.say "What is there to love about that?!?"
    "His reaction kind of takes me by surprise."
    bree.say "Well..."
    bree.say "It's supposed to be romantic, you know?"
    bree.say "A chance to spend some private time with your date."
    "The Master still doesn't seem impressed."
    master.say "Why does it have to be dark?"
    master.say "How am I supposed to see what other people are doing in the dark?"
    "By now we've walked over to join the queue."
    "The Master following me as he argues."
    "Not really knowing where he's going."
    bree.say "You're not supposed to be watching other people!"
    bree.say "You're supposed to make out with your own date!"
    master.say "But why?"
    master.say "I can make out with my own date whenever I want."
    master.say "Isn't there somewhere we can watch other people on the ride?"
    "The Master's actually stepping into the boat as he asks this."
    "Still not realising exactly where he is or what's happening."
    "And so that's how we sail off into the tunnel."
    "With me trying to sell the whole thing to him."
    "And the Master claiming it would be so much more fun to make it voyeuristic."
    "Needless to say, it's no the most romantic experience of my life so far."
    $ master.love += 1
    $ game.active_date.score += 10
    return

label master_date_hedge_maze_female:
    master.say "A Hedge Maze..."
    master.say "Finally a fitting challenge for my skills!"
    bree.say "You're saying you want to do the maze?"
    bree.say "Isn't that a bit boring?"
    "The Master shakes his head as he makes for the back of the queue."
    "And I'm forced to follow behind him or else be left behind."
    master.say "Nonsense, my dear..."
    master.say "Excitement, thrills, nausea?"
    master.say "A martial artist craves not these things!"
    bree.say "Well that's good to know..."
    bree.say "Because you're not going to find any of them in there!"
    "No matter what I say, the Master won't be persuaded."
    "And so I find myself walking into the maze with him a moment later."
    "I watch as he plants his fists on his hips."
    "Then he looks around, like he's gathering his powers."
    master.say "Watch closely, my pupil..."
    master.say "My skills will allow me to create a mental picture of this maze."
    master.say "And with that, I will find my way out of here in no time!"
    "If only that was what happened next."
    "Instead I find myself trudging along behind the old man."
    "Groaning and muttering to myself as he seems to be going in circles."
    bree.say "Are you going to admit it?"
    master.say "Admit what?"
    bree.say "That you're hopelessly lost..."
    bree.say "And that you need my help?"
    "The Master puffs himself up, like he's going to tell me off."
    "But then, all at once, he seems to deflate, like the air's been let out of him."
    master.say "Erm..."
    master.say "Yes, my dear..."
    "I shake my head as I take him by the hand."
    "Then I proceed to lead him out of there in a mere matter of minutes."
    bree.say "There you go..."
    bree.say "We're out."
    "The Master still looks deflated."
    "But then I see a glimmer in his eye."
    "And he starts to regain some of his former confidence."
    master.say "Of course, my dear..."
    master.say "That was...that was a test."
    master.say "A test to see if your skills are as sharp as mine."
    master.say "And you passed, so well done you."
    master.say "But more so well done me, for teaching you so well!"
    "All I can do is shake my head and groan."
    "Flabbergasted by his ability to blow his own trumpet."
    $ master.love += 1
    $ game.active_date.score += 10
    return

label master_date_amusement_ice_cream_female:
    "I keep looking around to check that the Master is still following me."
    "Worried that the heat and the crowds are going to prove too much for him."
    "But I see that he's still there, trailing along behind me, tongue hanging out."
    "Which of course starts me worrying that he's in danger of overheating."
    bree.say "Master..."
    bree.say "Maybe we should get an ice-cream?"
    bree.say "You know, cool down a little?"
    master.say "Nonsense, my dear..."
    master.say "My years of martial arts training means that..."
    bree.say "That you can deal with extremes of temperature?"
    bree.say "Yeah, I thought you might say that!"
    bree.say "What if we just say we're getting one because we like the taste?"
    master.say "Hmm..."
    master.say "I can go along with that!"
    "With a nod, I lead the way to the queue for the ice-cream stand."
    "And soon enough we're being handed the ice-creams we ordered."
    "But as we walk away, I see the way the Master has his tongue out."
    "And the way that it seems to be lashing away at the ice-cream in his hand."
    "All of which makes me think that he might have been telling the truth."
    "His tongue could just have been hanging out because he was seeing things he found appetising."
    "And I'm not talking about ice-cream!"
    $ master.love += 0
    $ game.active_date.score += 0
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
