label reona_use_condom:
    "Everything seems to be falling into place."
    "Reona and I are more than ready to go."
    "But then I remember something - and it's an important something too!"
    mike.say "Wait a second, Reona..."
    mike.say "I'll be right back!"
    reona.say "Huh?"
    reona.say "Where are you going?"
    mike.say "We need to use a condom, Reona."
    mike.say "But it's okay, I have some over here..."
    "Reona nods as I explain myself."
    "And then I leap up to go grab some protection."
    "Then it only takes a couple of seconds to get it on."
    "Once that's done, we can get it on too!"
    return
