label shiori_date_amusement_park_male:
    scene bg amusement
    show shiori embarrassed
    with fade
    "As usual, I'm more than thrilled at the chance to visit the amusement park."
    "I can't wait to get in through the gates and start queuing for the rides."
    "But whenever I try to pick up the pace, I feel Shiori resisting a little."
    "It's not like she's really trying to keep us from getting in there."
    "More like she won't give into the thrill that I'm feeling and go with the flow."
    mike.say "Shiori..."
    mike.say "Are you feeling okay?"
    mike.say "You still want to go in there, right?"
    "Shiori gives me one of her famously nervous smiles."
    "Like she's scared to death of pissing me off with her answer."
    show shiori surprised
    shiori.say "Oh no!"
    shiori.say "It's just that..."
    show shiori joke
    shiori.say "Well, I'm used to coming to places like this with Kanta."
    shiori.say "So it feels strange to be doing the same thing on a date with you!"
    show shiori normal
    "Oh great - she thinks that I want to do kid's stuff!"
    "Like I'm totally immature or something."
    "I wave a hand in the air, trying to dismiss Shiori's concerns."
    mike.say "Don't worry about it, Shiori."
    mike.say "There's loads of adult stuff to do in there."
    show shiori surprised
    shiori.say "Are you sure?"
    show shiori normal
    mike.say "Trust me, okay?"
    show shiori joke
    shiori.say "Okay, [hero.name]…"
    shiori.say "I trust you!"
    show shiori normal
    "I nod my head, determined to do all that it takes to get Shiori on side."
    "I'll show her that a place like this can be for adults too."
    return

label shiori_date_ferris_wheel_male:
    mike.say "Let's ride the Ferris Wheel, Shiori."
    mike.say "That's one of the all-time classics, right?"
    "Shiori looks up at the wheel towering over us."
    "And I can see from the look on her face that she's not convinced."
    shiori.say "Oh, I don't know..."
    shiori.say "It looks awfully high!"
    "We've been walking towards the ride all the time we've been talking."
    "So by now we're actually standing at the back of the queue."
    "Which means that we're effectively waiting in line."
    mike.say "Don't worry about a thing."
    mike.say "These rides have been around for years."
    mike.say "So they must be the safest ones around."
    "Shiori still doesn't look like she's buying it."
    "But by now we've made it to the front of the line."
    "And I manage to usher her into the waiting gondola."
    "It's only when the safety-bar comes down that she seems to realise what's happening."
    shiori.say "Oh dear!"
    shiori.say "Oh dear, oh dear!"
    mike.say "Don't worry, Shiori..."
    mike.say "I'll keep you safe."
    "Shiori's only response to my promise is to bury her head into my shoulder."
    "That and to start sobbing, the sound muffled by the position she's taken up."
    "I do the best I can to keep pointing out the best bits of the ride to her."
    "But it does not good, as Shiori refuses to turn her head in any other direction."
    "In fact everything I say only seems to make her press herself harder against me."
    "And by the time the ride comes to a halt and lets us off, she's a sobbing wreck!"
    "It takes me a long while to calm Shiori down after that."
    "The whole time I'm doing it, I'm also making myself a promise."
    "That the next time she backs away from a ride, I respect her instincts."
    $ shiori.love -= 2
    $ game.active_date.score -= 20
    return

label shiori_date_merry_go_round_male:
    shiori.say "Oh look..."
    shiori.say "They have a Merry-Go-Round!"
    shiori.say "I used to put Kanta on those when he was little."
    "I'm still not happy hearing Shiori talking about her son right now."
    "Normally it wouldn't bother me, but here it feels like an insult."
    "Like she's comparing something I find fun with stuff kids get up to."
    mike.say "That's a carousel, Shiori."
    mike.say "Each one's a piece of fairground history."
    "Shiori squints at the ride, as if she's confused."
    shiori.say "Are you sure?"
    shiori.say "It just looks like a plain old Merry-Go-Round to me!"
    mike.say "Just take a ride on it, Shiori..."
    mike.say "Then you'll soon see what I mean."
    "Shiori shrugs at this and allows me to lead her over to the ride."
    "We queue up and wait for our turn to come around."
    "And then we step onto the ride, choosing where we want to sit."
    "I keep nodding and smiling at Shiori."
    "As I'm waiting for the moment the magic of the ride gets her."
    "But nothing seems to happen the whole time we're on it."
    "And once we get off, Shiori seems less than impressed."
    shiori.say "Well..."
    shiori.say "That was very...nice."
    shiori.say "But I don't think I'll want to go on it again."
    $ shiori.love -= 0
    $ game.active_date.score -= 0
    return

label shiori_date_haunted_house_male:
    mike.say "Let's do the Haunted House next, Shiori."
    mike.say "That's one thing in the park that's not for kids!"
    "As soon as I mention the idea, Shiori looks worried."
    "Glancing up at the façade of the attraction and then back at me."
    shiori.say "I..."
    shiori.say "I don't think I can, [hero.name]!"
    shiori.say "That looks way too scary for me!"
    "I shake my head and let out a dismissive laugh."
    "Then I take hold of Shiori's hand, starting to lead her towards the Haunted House."
    mike.say "Don't be silly, Shiori!"
    mike.say "This isn't that kind of scary, you know?"
    shiori.say "It isn't?"
    mike.say "Of course not."
    mike.say "This is the fun kind of scary."
    "Shiori still looks more than a little nervous."
    "But she offers no resistance as we join the queue."
    shiori.say "Okay..."
    shiori.say "But if I get scared..."
    shiori.say "You promise that you'll get me out of there?"
    mike.say "Of course, Shiori."
    mike.say "I promise."
    "Of course I'm really just saying that to get Shiori in there."
    "And once she is, I'm sure that she'll be fine with what's inside."
    "Secure in my own belief it'll be fine, I hustle Shiori in through the door."
    "But the moment the first scare hits, she starts screaming."
    "She's pushing backwards, trying to get out of there."
    "The problem is that there are people coming in behind us."
    "And there's no way I can go back."
    "So I just have to keep on pushing Shiori forwards."
    "Wincing every time she sees another scary prop and her screaming gets louder."
    "Once we're outside, I open my mouth to begin apologising."
    "But Shiori beats me too it, punching me hard on the arm."
    shiori.say "You lied to me!"
    shiori.say "You said it wouldn't be scary!"
    shiori.say "You said I could get out of there!"
    mike.say "Ouch!"
    mike.say "Okay, okay..."
    mike.say "I'm sorry, Shiori!"
    mike.say "Just please stop hitting me!"
    $ shiori.love -= 2
    $ game.active_date.score -= 20
    return

label shiori_date_love_boat_male:
    shiori.say "[hero.name]..."
    shiori.say "What ride is that?"
    "I look over in the direction that Shiori's pointing."
    "And it doesn't take me long to recognise the ride in question."
    mike.say "Oh, that?"
    mike.say "That's just the Love Boat, Shiori."
    "I'm expecting this to answer the question."
    "But instead, Shiori stares at me blankly."
    mike.say "You know?"
    mike.say "The Tunnel of Love?"
    mike.say "You sit in a boat, in the dark?"
    "Suddenly I see the light of recognition flash in Shiori's eyes."
    "And before I can say another word, I feel her grab hold of my hand."
    "Then I find myself being jerked toward the queue for the ride."
    "Not only that, Shiori's pulling me with a freakish show of strength too!"
    mike.say "Argh..."
    mike.say "Shiori..."
    mike.say "You're going to...snap my wrist!"
    "But Shiori's not listening, as she hustles me over to the ride."
    "And as there's no queue for it either, she can push me straight onto it."
    "I land hard on the seat of the boat, and then Shiori leaps in after me."
    "And before I can regain my senses, we're sailing into the darkness."
    "Okay, I have to admit that what follows more than makes up for being manhandled."
    "And once I've regained my senses, I find myself getting straight into it."
    "In the darkness of the ride, all of Shiori's shyness seems to vanish."
    show shiori kiss
    $ shiori.flags.kiss += 1
    "She's all over me, kissing, caressing and stroking me like crazy!"
    "And by the time we come out the other end, I'm only able to stagger out of the boat."
    $ shiori.love += 2
    $ game.active_date.score += 20
    return

label shiori_date_hedge_maze_male:
    mike.say "The Hedge Maze looks quiet today."
    mike.say "You want to give it a try?"
    "Shiori shrugs, like she's not particularly impressed with the idea."
    "But as she doesn't come out and say no, I take that as a yes."
    mike.say "That's decided then?"
    mike.say "Come on, let's get in the queue."
    "We do just that, but it hardly seems necessary."
    "The line is so short and so fast we're inside in no time at all."
    shiori.say "So..."
    shiori.say "What happens now?"
    shiori.say "Do we get on a cart or something?"
    mike.say "No."
    shiori.say "Are there things that jump out at us?"
    mike.say "Not exactly."
    shiori.say "Any special effects at all?"
    mike.say "Erm..."
    mike.say "No again!"
    shiori.say "So what does happen?"
    mike.say "We wander around in here until we find the exit!"
    "Shiori shakes her head in sheer amazement."
    shiori.say "So the idea is basically to get lost?"
    "I nod my head."
    shiori.say "That's so dumb!"
    mike.say "I guess it kind of is..."
    "Shiori rolls her eyes and walks off into the maze."
    "And all I can do is follow her."
    "Pretty soon she finds the exit, and leads me out."
    "After that I vow never to mention the maze to her again."
    $ shiori.love -= 1
    $ game.active_date.score -= 10
    return


label shiori_date_amusement_ice_cream_male:
    shiori.say "Oh my goodness..."
    shiori.say "I had no idea it was going to be so hot today!"
    shiori.say "If I had, I'd have worn less."
    "I'm kind of nodding as Shiori's words wash over me."
    "And I can't really make sense of the idea she could be wearing less."
    "Because what she has on right now is kind of struggling to contain her."
    mike.say "Y...yeah, Shiori..."
    mike.say "Wear less clothes..."
    mike.say "That's good!"
    "Shiori glances at me with a pleading look in her eyes."
    "Which makes it clear that she's waiting for me to offer a solution."
    "So I shake my head, trying to remember exactly what she said."
    mike.say "Hot...yes..."
    mike.say "Erm..."
    mike.say "Ice-cream?"
    "I say this because in that moment my eyes settle on an ice-cream stand."
    "And much to my relief, the suggestion seems to really please Shiori."
    shiori.say "Oh, [hero.name]..."
    shiori.say "I just love ice-cream!"
    "I offer Shiori my arm and she takes it as we walk over to the stand."
    "Then we choose what we want as we wait in the queue."
    "Soon enough the server takes our order and we get our ice-creams."
    shiori.say "Mmm!"
    shiori.say "This is so nice, [hero.name]."
    shiori.say "And I feel cooler already."
    "As Shiori says this, a blob of ice-cream falls off her cone."
    "And with most girls it would have dropped straight onto the ground."
    "But instead it lands right in Shiori's cleavage with a wet splat."
    shiori.say "Ooh..."
    shiori.say "That's so cold!"
    shiori.say "[hero.name], do something!"
    "Without thinking, I lean in and begin to lick the ice-cream off Shiori's chest."
    "And it's not until my tongue goes into the space between her breasts that I realise what I'm doing."
    "Luckily for me, the blob isn't too big and I manage to lick it up pretty quickly."
    "Then I stand up again, hoping that nobody saw what I was just doing."
    "Shiori seems to be taking the same approach, keeping quiet and staring straight ahead."
    "But all the same, I can see that her cheeks are flushed red."
    "And she also has a rather large smile on her face too."
    $ shiori.love += 2
    $ game.active_date.score += 20
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
