# label kylie_date_amusement_park_male:
#     scene bg amusement
#     show kylie normal
#     with fade
#     "I'm feeling a real buzz of excitement as I walk towards the gates of the Amusement Park."
#     "And that's nothing new for me, as I love the chance to come here and go on all my favourite rides."
#     "But today it feels extra special as I have Kylie holding my hand as I go through the gates."
#     "As if it weren't enough that I have a cute girl with me, she seems totally up for it too."
#     show kylie impressed
#     "Kylie's eyes are like saucers as she looks here and there, taking it all in."
#     "In fact she looks almost like they're going to glaze over with all of the flashing lights!"
#     mike.say "You look pretty excited to be here, Kylie!"
#     mike.say "You should have told me that you were so into this place."
#     show kylie normal
#     "At the sound of my voice, Kylie's expression changes."
#     "She tears her gaze away from what's going on around us."
#     "And all of a sudden I'm the centre of her attention."
#     "The change is so sudden and so complete that it's almost scary."
#     "Like every fibre of Kylie's being is focussed on me at once."
#     show kylie shout
#     kylie.say "Oh, this place is great, [hero.name]."
#     kylie.say "But that's not why I'm excited to be here."
#     show kylie normal
#     mike.say "It..."
#     mike.say "It isn't?"
#     show kylie crazyhappy
#     kylie.say "Of course not, silly!"
#     kylie.say "The really exciting thing is getting to spend time with you!"
#     show kylie smile
#     "As Kylie says this, I feel her grip on my arm tightening."
#     "At the same time her eyes seem to get even bigger than before."
#     show kylie happy
#     "And her smile widens, now showing off her even, white teeth too."
#     "I can't help thinking that all of this could be a little scary."
#     "You know, if I wasn't totally sure that it's just because she's into me?"
#     "Knowing that means I can just return the smile and forget all about it."
#     "And then I lead Kylie into the park for what promises to be a very enjoyable visit."
#     return

label kylie_date_ferris_wheel_male:
    mike.say "You want to ride the Ferris Wheel, Kylie?"
    mike.say "I mean, it is kind of a cliché!"
    mike.say "But I'm up for it if you are?"
    "Kylie gives me a pleasant smile and a nod."
    "Then we start walking towards the ride in question."
    kylie.say "Of course I'll ride it with you."
    kylie.say "That sounds great."
    kylie.say "The kind of thing that makes for romantic memories!"
    "I nod as Kylie and I join the line for the ride."
    "And we pass the time until we reach the front of the queue by chatting about nothing."
    "Soon enough we're climbing into a gondola and the safety-bar is coming down."
    "Then the wheel begins to move, and we climb slowly into the air."
    "Much to my delight, Kylie leans in close as all of this is happening."
    "And once we reach the top and the ride stops, she lets out a sigh."
    kylie.say "Hmm..."
    kylie.say "Doesn't the world look perfect from up here, [hero.name]?"
    mike.say "It sure does, Kylie."
    kylie.say "Almost like everyone else but us just vanished."
    kylie.say "They disappeared and left the place to you and me!"
    mike.say "That'd be great, Kylie!"
    kylie.say "You really think so?!?"
    mike.say "Oh yeah - imagine never having to wait in line for anything, ever again!"
    kylie.say "But it'd be so much work!"
    mike.say "What would, Kylie?"
    kylie.say "Doing away with all those people, of course!"
    mike.say "Oh, Kylie..."
    mike.say "You say the funniest things!"
    kylie.say "I do?!?"
    $ kylie.love += 1
    $ game.active_date.score += 10
    return

label kylie_date_merry_go_round_male:
    kylie.say "Hmm..."
    kylie.say "This place is so busy today!"
    kylie.say "It's going to take us an age to get on anything."
    "I feel Kylie's pain, as the park is pretty packed."
    "But then I set eyes on the Merry-Go-Round."
    "And I see that the line is very short."
    "Well, of course it would be, as that's a really old ride."
    "But getting on it quickly might just compensate for that."
    mike.say "Let's ride the Merry-Go-Round, Kylie..."
    mike.say "There aren't many people waiting for that."
    "I'm expecting Kylie to shoot the idea down."
    "Telling me that it's boring or just for kids."
    "But to my surprise, she nods in agreement."
    kylie.say "Okay, [hero.name]…"
    kylie.say "Let's do that."
    "Kylie and I hurry over to join the queue."
    "And it's so short that we're on the ride in mere minutes."
    "Together we pick out the places where we want to sit."
    "Then the ride begins to turn, and we hold on tight."
    "Sure, it's not the most exciting ride in the park."
    "But Kylie seems to be genuinely enjoying herself."
    "And the sight of such a big smile on her face cheers me up too."
    "So by the time the ride ends and we get off, I'm smiling as well."
    $ kylie.love += 2
    $ game.active_date.score += 20
    return

label kylie_date_haunted_house_male:
    mike.say "Ooh..."
    mike.say "The Haunted House!"
    mike.say "We have to go in there, Kylie!"
    "Kylie looks up at the spooky décor of the Haunted House."
    "And I can already see a frown spreading across her face."
    kylie.say "Really?"
    kylie.say "Because it looks kind of tacky to me!"
    mike.say "Oh, come on..."
    mike.say "It's one of my favourites."
    mike.say "A trip to the Amusement Park isn't complete without it!"
    "Kylie seems to surrender as I say this."
    "She shakes her head and rolls her eyes for sure."
    "But then she nods and starts to walk over to the ride."
    kylie.say "Okay, okay..."
    kylie.say "Let's get this over with."
    "We queue up and wait our turn."
    "And as soon as we're inside, I'm in my element."
    "Sure the decorations inside are a little cheesy."
    "And maybe the jump-scares are predictable."
    "But to me, that's all part of the charm."
    "Though when I take the time to look over my shoulder, Kylie doesn't seem impressed."
    "In fact I don't think I hear her scream or feel her jump even once the whole way round."
    "When we walk out of the exit, I just have to ask her what's going on."
    mike.say "What happened in there, Kylie?"
    mike.say "You didn't flinch once!"
    kylie.say "I guess that kind of thing just doesn't scare me."
    kylie.say "You know, ghosts and ghouls, and all that made up stuff?"
    mike.say "Then what does?"
    kylie.say "Oh, real human beings are much scarier!"
    kylie.say "Because serial-killers and cannibals - they're real!"
    mike.say "Ah..."
    mike.say "Okay, Kylie..."
    mike.say "I kind of wish I never asked!"
    $ kylie.love -= 2
    $ game.active_date.score -= 20
    return

label kylie_date_love_boat_male:
    kylie.say "Oh...my...god!"
    kylie.say "I can't believe they have one of these!"
    kylie.say "I've always wanted to ride one of them!"
    "I hurry over to see what's got Kylie so excited."
    "I'm expecting to see a crazy roller-coaster or a virtual reality simulator."
    "So it comes as quite a surprise to find myself looking at the Love Boat."
    mike.say "The Love Boat?"
    mike.say "That's what you want to ride?!?"
    kylie.say "Oh yeah!"
    kylie.say "And we are going to be riding it too."
    mike.say "You do know that it's just a boat, yeah?"
    mike.say "A boat that floats slowly along a dark tunnel?"
    "Kylie doesn't dignify this with an answer."
    "Instead she grabs me by the wrist, almost crushing it in the process."
    "And then she drags me straight over to where the queue begins."
    mike.say "Wha..."
    mike.say "Ow..."
    mike.say "Ouch!"
    "Kylie doesn't seem to hear my cries of pain."
    "Or else she ignores them entirely."
    "And I spend the rest of the time we're in the queue nursing my bruised wrist."
    "But once we step into the boat and it starts to move, I forget all about it."
    "That's because the moment we're out of sight, Kylie pounces on me."
    "And I don't mean that in the figurative sense either."
    "She literally turns and jumps atop me, sending the boat swaying."
    show kylie kiss
    $ kylie.flags.kiss += 1
    "I don't have time to register what's happening before she's kissing me."
    "Her tongue is in my mouth and her hands are all over my helpless body."
    "As soon as I can recover, I begin to return the attention as best I can."
    "But it still feels like I'm the one being ravished in the darkness!"
    "When the boat finally emerges from the tunnel, I'm totally overwhelmed."
    "All I can do is lie there, gasping for breath as Kylie strokes my cheek."
    "Part of me wants to ask if she'll go round again."
    "But another part of me is worried that I wouldn't survive it!"
    $ kylie.love += 2
    $ game.active_date.score += 20
    return

label kylie_date_hedge_maze_male:
    mike.say "You think we should try the Hedge Maze, Kylie?"
    mike.say "Could be quite chilled - you know, a change of pace?"
    "Kylie gives me a shrug and a twitch of the head."
    "Kind of like she's not exactly enthused by the idea of the maze."
    "But also like she can't summon any serious objection to it either."
    kylie.say "Okay, [hero.name]…"
    kylie.say "We can do the maze."
    kylie.say "Let's go queue up."
    "Kylie and I walk over to the start of the queue and join it."
    "Then we chat quietly while we wait for our turn to enter the maze."
    "Once we're inside, we find ourselves flanked on both sides by tall hedges."
    "And we start to wander along the corridors of the maze."
    "It's hard to put a finger on what the experience is like."
    "Because there's nothing exactly bad about it."
    "But there's also nothing exactly good as well."
    "All in all, it's more forgettable than anything else."
    "And once we inevitably find the exit, it's all over."
    "In fact it's so uneventful that neither of us mentions it again."
    "We just walk off in search of the next ride that takes our fancy."
    $ kylie.love += 0
    $ game.active_date.score += 0
    return

label kylie_date_amusement_park_female:
    scene bg amusement
    show kylie normal
    with fade
    "Sometimes it can feel a little weird taking a date to the Amusement Park."
    "Like, I know that it's not as strange as it once was for adults to be into that kind of stuff."
    "But I still don't like the idea of my date thinking that I'm immature and childish."
    "Which is why it's such a relief to have Kylie by my side as we walk into the place."
    show kylie smile
    "She's holding onto my hand and smiling, like it's not a chore for her to be seen here."
    "And that's filling me with confidence too, making me smile like a fool."
    kylie.say "Hmm..."
    show kylie shout
    kylie.say "What's gotten into you, [hero.name]?"
    show kylie normal
    "Kylie's question catches me totally off-guard."
    "I didn't realise that I was beaming like that."
    bree.say "Oh..."
    bree.say "I'm just happy, Kylie..."
    bree.say "Happy to be here and to be with you, I guess."
    show kylie smile
    "Kylie begins to smile too, like she's pleased with what I just said."
    "But there's something amused and knowing about the smile on her face."
    "Like she already knew what I was going to say."
    "And now she's pleased to be proven right."
    show kylie happy
    kylie.say "Me too, [hero.name], me too."
    show kylie shout
    kylie.say "I never seem to have an excuse to come here."
    kylie.say "So that's just another great thing about being with you."
    kylie.say "You're fun and you like to do fun things."
    show kylie normal
    bree.say "Aww..."
    bree.say "Thanks, Kylie."
    bree.say "I might be about to jinx this thing..."
    bree.say "But I think this is going to be the best trip to the Amusement Park ever!"
    show kylie crazyhappy
    "Kylie laughs and shakes her head at this."
    "And that's the very same moment that we walk through the gates."
    show kylie shout
    kylie.say "You sure are staking a lot on this date, [hero.name]!"
    kylie.say "Let's just hope that it all works out that way."
    show kylie normal
    "Kylie gives me a knowing glance, then raises one eyebrow."
    "All of which makes me feel like the pressure is really on."
    "Now all I have to do is put my money where my mouth is."
    "Which shouldn't be too hard, right?"
    return

label kylie_date_ferris_wheel_female:
    bree.say "You want to ride the Ferris Wheel, Kylie?"
    bree.say "Looks like the queue's pretty short."
    bree.say "And it's a clear day, so the view should be great too."
    "Kylie looks over a the ride in question."
    "And then she nods, adding a smile for good measure."
    kylie.say "Why not."
    kylie.say "That sounds really nice."
    "That seals the deal."
    "So we walk over and join the back of the queue."
    "The line moves quickly too, meaning we make it to the front in no time."
    "And so we find ourselves stepping into a gondola before we know it."
    "Kylie and I sit down as the safety-bar comes down."
    "Then the ride begins to move and we rise slowly into the air."
    "Nobody says a thing as begin to get higher than the park rides."
    "But once we make it to the top of the wheel, we're both gasping."
    "Kylie and I exchange a look of wonder, then return our attention to the view."
    bree.say "Wow..."
    bree.say "That really is one hell of a view!"
    bree.say "I think I can see the whole of the city from up here."
    "Kylie nods as she takes in the panoramic view as well."
    kylie.say "I must have been up this high in a building before."
    kylie.say "But this seems different somehow."
    kylie.say "You can see all of the possibilities!"
    "That seems a really strange way to put it."
    "Which makes me turn to Kylie with curiosity written on my face."
    bree.say "Possibilities?"
    bree.say "What could you possibly do up this high?"
    kylie.say "Oh, I was just thinking..."
    kylie.say "The possibilities of surviving a fall from this height."
    kylie.say "They have to be impossibly small, right?"
    "The question is beyond weird, but I do the best I can to ignore that fact."
    "Because I don't want to ruin the mood by asking awkward questions."
    bree.say "Erm..."
    bree.say "Yeah, Kylie..."
    bree.say "I guess so..."
    $ kylie.love += 1
    $ game.active_date.score += 10
    return

label kylie_date_merry_go_round_female:
    show kylie surprised
    kylie.say "Oh my..."
    kylie.say "Look, [hero.name]..."
    kylie.say "They have one of those old-fashioned Merry-Go-Rounds."
    "I've already seen the ride that Kylie's talking about."
    "And normally I'd be kind of blasé about that kind of thing."
    "But as she seems to be showing some enthusiasm, I decide to play along."
    bree.say "Really, Kylie?"
    bree.say "Then we should totally ride it."
    bree.say "Right?"
    show kylie happy
    "Kylie nods happily."
    kylie.say "If that's what you want, [hero.name]..."
    kylie.say "Come on, let's join the queue."
    "Kylie and I walk over and stand at the back of the line."
    "Then we make small-talk as we wait for our turn to come round."
    "Once we're on the ride, we choose the spots where we want to sit."
    "Then we wait patiently for the ride to begin."
    "When the ride starts moving, I find it goes faster than I expected."
    "So I feel the need to hold on tight to the pole in front of me."
    "Kylie sees this and seems to interpret it as me getting into the ride."
    "She nods and then looks ahead, sure that I'm having a good time."
    "The ride also lasts longer than I was expecting it to as well."
    "When it finally stops and we get off, I'm even a little dizzy."
    kylie.say "Are you okay, [hero.name]?"
    bree.say "I think do, Kylie..."
    bree.say "No need to worry about me!"
    "So I just went on a ride I didn't care about."
    "And I ended up feeling ill into the bargain."
    "Maybe next time I should be more honest."
    $ kylie.love += 1
    $ game.active_date.score += 10
    return

label kylie_date_haunted_house_female:
    bree.say "Oh, look..."
    bree.say "There's the Haunted House!"
    bree.say "I have to go in there, Kylie!"
    "Kylie casts a glance at the Haunted House, almost like she's surveying it."
    "But I have to say that she doesn't exactly look impressed with what she sees."
    kylie.say "Really?"
    kylie.say "You're into that kind of thing?"
    "I feel a little offended by the question."
    "But I do the best I can to put a smile on my face."
    bree.say "What's the problem, Kylie?"
    bree.say "It's just the Haunted House."
    bree.say "Just some harmless fun."
    "Kylie seems to think about it for a moment."
    "Then she gives me a brief nod."
    kylie.say "I suppose we could give it a go."
    kylie.say "But I don't think I'll like it."
    "I keep that in mind as we walk over and join the queue."
    "And luckily it doesn't take us long to get to the front."
    "Once we're inside, I'm determined to show Kylie that she's wrong."
    "Surely she'll see the fun of this as soon as she gets her first scare."
    "Right?"
    "But much to my surprise, she just kind of sighs."
    "And the rest of the Haunted House is much the same."
    "Once we're outside, I decide to question her on it."
    bree.say "What was that all about, Kylie?"
    bree.say "There were some genuine, guaranteed scares in there."
    bree.say "But you didn't sell one of them!"
    kylie.say "I'm sorry, [hero.name]..."
    kylie.say "But I just don't find that kind of thing scary."
    bree.say "Oh yeah?"
    bree.say "Then you tell me, Kylie..."
    bree.say "What do you find scary?"
    kylie.say "Trust me, [hero.name]..."
    kylie.say "It's not the ghosts and ghouls you should be scared off."
    kylie.say "They're all nothing but make-believe."
    kylie.say "What you should really be scared off is the escaped lunatic."
    kylie.say "Waiting under your bed, clutching at a carving knife."
    kylie.say "Just waiting for the sound of you falling asleep!"
    bree.say "Oh..."
    bree.say "Okay, okay..."
    bree.say "Forget I even asked!"
    $ kylie.love -= 2
    $ game.active_date.score -= 20
    return

label kylie_date_love_boat_female:
    kylie.say "Oh, now we have to do the Tunnel of Love!"
    kylie.say "Come on, [hero.name]."
    "I have what feels like a fraction of a second to respond."
    "And then I find myself being dragged along after Kylie."
    bree.say "Whoa..."
    bree.say "Okay, Kylie..."
    bree.say "I'm coming as fast as I can!"
    "And so that's how I find myself standing in the queue for the Love Boat."
    "I'm totally up for it and looking forward to getting on the ride."
    "But it seems like the smile on my face isn't enough to convince Kylie."
    bree.say "Erm..."
    bree.say "Ouch!"
    bree.say "Kylie, you can..."
    bree.say "You can let go of my hand, okay?"
    bree.say "Or at least, maybe not squeeze it so hard?"
    kylie.say "No time for that now, [hero.name]..."
    kylie.say "We're up!"
    "Again I'm caught off-guard as Kylie pushes me into the boat."
    "Then she jumps in behind me, making rock crazily."
    "And from that moment on, she doesn't release me."
    "Instead she only holds me tighter, determined not to let me go."
    "But I have to say that I'm not in the least bit against it!"
    $ kylie.love += 2
    $ game.active_date.score += 20
    return

label kylie_date_hedge_maze_female:
    bree.say "You want to do the Hedge Maze, Kylie?"
    bree.say "The queue's pretty short right now."
    "Kylie nods in agreement."
    kylie.say "Sure, [hero.name]..."
    kylie.say "I can't remember the last time I went into a maze."
    "Kylie and I walk over to join the queue."
    "Then we wait patiently until we reach the front of the queue."
    "Once we're inside, I turn around, taking it all in."
    "We're flanked on two sides by tall, impenetrable hedges."
    "And I'm beginning to find it all a little intimidating."
    bree.say "Wow..."
    bree.say "It's so dark in here."
    bree.say "Pretty creepy too!"
    "Kylie shakes her head as she takes hold of my hand."
    "Then she gives it a gentle, reassuring squeeze."
    kylie.say "Don't be silly, [hero.name]."
    kylie.say "There's noting in here to be scared of!"
    "With that she leads me deeper into the maze."
    "And soon enough I have no idea where we are."
    "But Kylie doesn't seem to have any such problems."
    "She leads me confidently around each and every corner."
    "And she doesn't stop until we find the exit either."
    $ kylie.love += 1
    $ game.active_date.score += 10
    return

label kylie_date_amusement_ice_cream_male:
    mike.say "Oh man..."
    mike.say "I could really go for an ice-cream right about now!"
    "Kylie looks at me with a smile as I say this."
    "Kind of cocking her head on one side as she does so."
    kylie.say "Okay, [hero.name]..."
    kylie.say "So why don't we go get one?"
    kylie.say "The queue for the ice-cream stand is just over there."
    "I follow Kylie's gaze."
    "But at the same time I let out a sigh."
    mike.say "Urgh..."
    mike.say "But just look at the size of the queue!"
    mike.say "I don't have the patience to wait that long."
    "I'm expecting Kylie to tell me off for being so lazy."
    "But instead she puts on a smile and shakes her head."
    kylie.say "No problem, [hero.name]..."
    kylie.say "I know a little hack to speed things up."
    kylie.say "What kind of ice-cream do you want?"
    "Just then I see a couple walking away from the stand."
    "They look really happy, ice-creams held in their hands."
    mike.say "Those look good, Kylie..."
    mike.say "The ones those two over there have?"
    kylie.say "I see them, [hero.name]..."
    kylie.say "Now you just wait right there, okay?"
    "I nod as Kylie disappears around the same corner as the couple."
    "After a couple of minutes, she comes back around the corner."
    "And to my amazement, she has two ice-creams in her hands."
    "They look just like the one's the couple had."
    "But I see these are flecked with red spots."
    "Kylie hands one to me, a huge smile on her face."
    mike.say "Wow, Kylie..."
    mike.say "There are just the same..."
    mike.say "Apart from the strawberry syrup!"
    kylie.say "Strawberry syrup..."
    kylie.say "Yeah...that's exactly what it is..."
    $ kylie.yandere += 1
    $ kylie.love += 1
    $ game.active_date.score += 10
    return
