label sasha_date_amusement_park_male:
    scene bg amusement
    show sasha upset
    with fade
    mike.say "What are you waiting for, Sasha?"
    mike.say "Come on - keep up!"
    "I take a look back over my shoulder to see what's up with Sasha."
    "And it comes as some small comfort to realise she's right on my heels."
    show sasha angry
    sasha.say "Hey!"
    sasha.say "Will you wait up one second?!?"
    show sasha upset
    "I shake my head as I turn it back to look ahead."
    mike.say "Uh-uh, Sasha..."
    mike.say "I don't want to waste a single second in the Amusement Park!"
    mike.say "Don't slow down now, because we're almost there."
    "A few seconds after I say all of this, I'm hurrying through the gates to the Park."
    "Only when I'm well inside of them do I finally stop and begin to catch my breath."
    "Sasha runs up a moment later, doubling over and gasping as she comes to a halt."
    show sasha pain
    sasha.say "Urgh..."
    sasha.say "What's the matter with you?"
    sasha.say "Are you some kind of sadist?"
    show sasha sad
    mike.say "No, Sasha..."
    mike.say "I'm just a regular guy that really loves the Amusement Park!"
    "By now I've recovered from the sprint to get into the place."
    "So the only thing on my mind is getting onto the nearest ride."
    mike.say "Okay, we're in..."
    mike.say "So what are we going to ride first?"
    show sasha whining
    sasha.say "I don't care..."
    sasha.say "So long as I can sit down on the damn thing!"
    return

label sasha_date_ferris_wheel_male:
    mike.say "You want to ride the Ferris Wheel, Sasha?"
    "Sasha makes a snorting sound and shakes her head."
    sasha.say "Fnnarr…"
    sasha.say "No, [hero.name], I do not want to ride the Ferris Wheel."
    sasha.say "But I will if you really want to?"
    "I can't help bristle a little at Sasha's tone."
    "Like she's suggesting I'm lame for suggesting it."
    mike.say "I'm not bothered, Sasha..."
    mike.say "But it's there and it's not going anywhere."
    mike.say "So we might as well do it."
    "Sasha looks over at the Ferris Wheel and shrugs."
    sasha.say "Whatever, [hero.name]…"
    sasha.say "I don't know why you won't just admit you want to ride it though!"
    "I shake my head as we walk over to join the back of the queue."
    "And I can't understand why Sasha's being so passive aggressive."
    mike.say "I already said I'm not fussed."
    mike.say "Just say you don't want to ride it if you don't want to!"
    "The exchange between us keeps on going like this until we're on the actual ride."
    "And it only seems to stop once we start to rise up into the air."
    "Sasha and I both fall silent, each of us sulking as this happens."
    "A silence that holds until the ride stops at the top of the wheel."
    sasha.say "Huh..."
    sasha.say "I suppose the view is pretty sweet from up here."
    sasha.say "Not that I'm saying I like it!"
    mike.say "Yeah, yeah..."
    mike.say "I've seen far worse than that."
    mike.say "But that doesn't mean I'm having a good time!"
    mike.say "Right?"
    sasha.say "Right!"
    "By the time the ride ends, the squabble seems to be over."
    "As if Sasha wants to forget about it and move on as much as I do."
    $ sasha.love += 1
    $ game.active_date.score += 10
    return

label sasha_date_merry_go_round_male:
    sasha.say "Urgh..."
    sasha.say "This is impossible!"
    sasha.say "The lines for all of the good rides are so long!"
    "I want to argue with Sasha, to say that she's exaggerating."
    "But I can see with my own eyes that she's right."
    "Almost all of the exciting rides have super-long queues."
    "Then I feel a glimmer of hope as I spot a ride with a much shorter one."
    "I look at the sign to see what it is, and I feel a pang of disappointment."
    mike.say "The Merry-Go-Round!"
    sasha.say "Huh?"
    sasha.say "What about it?"
    "I point out the ride and it's short queue to Sasha."
    mike.say "Tiny line, Sasha..."
    mike.say "That's what."
    sasha.say "Of course it has a short line - it's ancient and boring!"
    mike.say "I know that."
    mike.say "But we could kill some time riding it."
    mike.say "Maybe enough for the other queues to shrink."
    "For a moment I think that Sasha's going to argue."
    "But then she nods, grabbing my hand and pulling me towards the Merry-Go-Round."
    sasha.say "Screw it - let's ride the damn thing!"
    "The short queue means that we're getting on the ride in no time at all."
    "And once we're on there, I do the best I can to get some enjoyment out of it."
    "But all it does is go round in a circle, for god's sake!"
    "Plus the ride seems to be over before it even begins."
    "Once we get off the ride, it's clear neither of us is impressed."
    "But I still do the best I can to put a positive spin on things."
    mike.say "At least the other lines are shorter now."
    sasha.say "Yeah, but at what cost?"
    sasha.say "I feel like I'm losing the will to live!"
    $ sasha.love -= 2
    $ game.active_date.score -= 20
    return

label sasha_date_haunted_house_male:
    mike.say "We have to do the Haunted House, Sasha..."
    mike.say "It's one of my favourite things at the park."
    mike.say "And everyone loves a good scare, right?"
    "Sasha shakes her head at this."
    sasha.say "Figures this would be your favourite, [hero.name]..."
    sasha.say "You're pretty gruesome yourself!"
    mike.say "Hey!"
    with vpunch
    play sound punch_hard
    "Sasha laughs and gives me a playful punch on the shoulder."
    "But she does so as we walk over to the Haunted House."
    "And she joins the queue at my side without a hint of protest."
    "We chat about everything and nothing as we wait for our turn."
    "But secretly I'm hoping that I'll soon be getting my revenge."
    "Because I figure that I'm a veteran of things like this."
    "And so I should be able to ride it out much better than Sasha."
    "While she's jumping out of her skin, I'll be laughing my ass off!"
    mike.say "Okay, Sasha..."
    mike.say "Here we go - get ready to be scared!"
    "With that, I pull Sasha into the Haunted House with me."
    "And I wait impatiently for her to start screaming."
    "Which means I'm pretty surprised when she starts laughing instead!"
    sasha.say "Oh man..."
    sasha.say "Is this for real?"
    sasha.say "It's so damn cheesy!"
    mike.say "What are you even talking about?"
    mike.say "This place is supposed to be terrifying!"
    "Sasha spends the rest of the walk around the Haunted House chuckling away to herself."
    "And by the time we get out of there, I'm managing to see the funny side of it."
    "I mean, at least she wasn't bored and wanting to leave before the end."
    sasha.say "Wow..."
    sasha.say "Some of the things in there reminded me of guys I've dated!"
    mike.say "You mean dated in the past, right?"
    mike.say "Not that you're currently dating, right?"
    $ sasha.love += 2
    $ game.active_date.score += 20
    return

label sasha_date_love_boat_male:
    mike.say "We should ride the Love Boat, Sasha..."
    mike.say "It's like a right of passage for couples!"
    "Sasha doesn't seem convinced by my pitch."
    sasha.say "For couples that are frigid and timid maybe!"
    sasha.say "I don't need to ride a crappy boat to make out."
    sasha.say "I can get you to kiss me any damn time I like!"
    "I can't help frowning at that last comment."
    "Because it's like Sasha's saying she can control me!"
    mike.say "What's that supposed to mean?!?"
    "Sasha snaps her fingers and points to her lips."
    sasha.say "[hero.name]..."
    sasha.say "Kiss me - now!"
    show sasha kiss
    $ sasha.flags.kiss += 1
    "Without thinking, I lean in and plant a kiss on Sasha's lips."
    sasha.say "There, you see what I mean?"
    mike.say "That..."
    mike.say "That was a fluke!"
    sasha.say "No way - I can make you do whatever I want."
    sasha.say "Like...ride the Love Boat!"
    mike.say "Okay, Sasha..."
    mike.say "Whatever you say!"
    "Taking Sasha by the hand, I hurry over to the ride in question."
    "There's no real queue, so we pretty much step straight into a boat."
    "As we sail into the darkness, Sasha looks triumphant."
    sasha.say "Ha!"
    sasha.say "You see?"
    "But then the reality of the situation seems to dawn on her."
    sasha.say "Ah shit..."
    sasha.say "Why didn't I ask you to get me a beer or something like that?"
    sasha.say "This is going to be so boring!"
    $ sasha.love += 0
    $ game.active_date.score += 0
    return

label sasha_date_hedge_maze_male:
    mike.say "The queue for the Hedge Maze is pretty short."
    mike.say "Maybe we should give it a try?"
    "Sasha looks the queue over as I say all of this."
    "And she seems to be weighing up her options at the same time."
    sasha.say "I guess we could try it."
    sasha.say "What have we got to lose?"
    "Together we walk over to the back of the line."
    "And then we wait as we work our way up the queue."
    "Pretty soon our turn comes around and we step into the maze."
    mike.say "Huh..."
    mike.say "I swear the hedges didn't look so high from the outside!"
    sasha.say "I dunno, [hero.name]..."
    sasha.say "This is kind of cool."
    "I blink in amazement as Sasha seems to be warming to the maze."
    "Because she's usually the first person to call something lame and shoot it down."
    "So to hear her getting into something that's basically a bunch of hedges is weird."
    mike.say "Really?"
    sasha.say "Yeah..."
    sasha.say "It's like one of those dark labyrinths from a horror movie, you know?"
    sasha.say "Or even better, a rock video!"
    sasha.say "Where there's a monster chasing a helpless victim..."
    "I see Sasha hunching her shoulders and making claws of her hands."
    "Then she starts stalking towards me, like she's hunting me down!"
    mike.say "Sasha..."
    mike.say "What are you doing?"
    mike.say "Stop it - you're scaring me!"
    "Without warning, Sasha lets out a shriek and darts towards me."
    "I let out a similar sound and turn on my heels, running away from her."
    "The rest of the time I'm in the maze is spent fleeing from Sasha."
    "But it doesn't take me long to hear her laughter behind me."
    "That sound brings me back to reality and snaps me out of it."
    "From there, the chase turns into a game."
    "And a quite enjoyable one at that."
    "One that ends in the centre of the maze."
    "Where I'm more than happy to let Sasha capture me."
    $ sasha.love += 2
    $ game.active_date.score += 20
    return

label sasha_date_amusement_ice_cream_male:
    sasha.say "Oh man, is it ever hot today..."
    sasha.say "We need to find a way to cool down, and fast!"
    "I hadn't realised just how hot it was until Sasha spoke up just now."
    "But I can already feel my throat drying out as I return her gaze."
    mike.say "You know what, Sasha..."
    mike.say "You're one hundred percent correct."
    mike.say "I'm totally parched!"
    "I gaze around for a moment, searching for a solution."
    "But all of the rides that involve getting wet already have huge queues."
    "Because I guess everyone else is already a couple of steps ahead of us."
    "Then I have a flash of inspiration."
    mike.say "ICE-CREAM!"
    mike.say "Sasha, we need to get ice-cream."
    "Sasha nods as soon as she hears my suggestion."
    sasha.say "That's a great idea, [hero.name]..."
    sasha.say "Quickly - to the ice-cream stand!"
    "Sasha adopts a dramatic pose, then dashes off."
    "Which leaves me to hurry along after her."
    "Luckily for us, the line for the ice-cream stand is shorter."
    "So we make it to the front in what feels like record time."
    "And soon enough we have our ice-creams in our hands."
    sasha.say "Good thinking, partner!"
    "I can't help smiling as Sasha praises me."
    "Feeling like we're partners in crime."
    "As well as partners in another sense entirely too."
    $ sasha.love += 2
    $ game.active_date.score += 20
    return

label sasha_date_amusement_park_female:
    scene bg amusement
    show sasha annoyed
    with fade
    bree.say "Come on, Sasha..."
    bree.say "You have to keep up..."
    bree.say "Or else I'm gonna end up leaving you behind!"
    "I spare a precious moment to look back over my shoulder as I run towards the Amusement Park gates."
    "And I feel a sense of relief to see that Sasha's running along behind me."
    show sasha pain
    sasha.say "Wait up, [hero.name]..."
    sasha.say "You never told me..."
    sasha.say "That we'd have to...run!"
    show sasha upset
    "As soon as we're through the gates, I stop running."
    "And Sasha stops too, putting her hands on her knees and gasping for breath."
    bree.say "Oh no, Sasha..."
    bree.say "We don't have to run."
    bree.say "I'm just so excited to be visiting the Amusement Park."
    bree.say "So excited that I just needed to run right through the gates!"
    show sasha stuned
    "By now Sasha's managed to stand up straight again."
    "And she's staring at me in sheer amazement."
    show sasha surprised
    sasha.say "You mean all of that was for nothing?"
    sasha.say "You were just torturing me for what?"
    sasha.say "For the fun of it?!?"
    show sasha stuned
    "I force a nervous smile onto my face."
    "And I offer Sasha a helpless shrug."
    "Hoping that she'll see the funny side."
    bree.say "No, no, no..."
    bree.say "I was just trying to get you into the mood, that's all!"
    show sasha upset
    "Sasha walks off, shaking her head and muttering under her breath."
    "And I follow on behind her, still smiling and trying to lighten the mood."
    return

label sasha_date_ferris_wheel_female:
    bree.say "Let's ride the Ferris Wheel, Sasha..."
    bree.say "That's kind of a tradition, right?"
    "Sasha shrugs as we walk over to the Ferris Wheel."
    "Not outright refusing to ride it."
    "But not showing much enthusiasm either."
    sasha.say "Whatever, [hero.name]..."
    sasha.say "It'll kill some time, if nothing else."
    "Ignoring Sasha's muted response, I join the line."
    "And it doesn't take us long to reach the front of the queue."
    "Sasha and I step into the waiting gondola."
    "The safety-bar comes down, and we start to rise into the air."
    "The higher we go, the more impressive the view becomes."
    "And I can't keep from jabbing Sasha in the ribs."
    bree.say "Look at the view, Sasha..."
    bree.say "Pretty impressive, right?"
    sasha.say "I guess so."
    "I feel a little peeved at Sasha's lack of enthusiasm."
    "So I have another crack at her once we reach the top of the wheel."
    bree.say "How about now, Sasha?"
    bree.say "Are you impressed yet?"
    sasha.say "Will you leave it alone, [hero.name]?"
    sasha.say "I already said I wasn't impressed."
    sasha.say "Now quit making it awkward, and shut up!"
    "I feel a slight sting at being rebuked by Sasha."
    "Enough to make me do exactly what she just said."
    "So we spend the rest of the ride in silence."
    "Which ironically feels just as awkward as me asking so many questions."
    $ sasha.love += 1
    $ game.active_date.score += 10
    return

label sasha_date_merry_go_round_female:
    sasha.say "I can't believe you talked me into this, [hero.name]..."
    sasha.say "This ride's for little kids!"
    "I'm halfway through climbing onto the horse I've chosen when Sasha chimes up."
    "And I can't help looking at her in amazement."
    bree.say "Don't be such a grouch, Sasha."
    bree.say "This ride isn't just for kids."
    bree.say "If it was, there's be a height restriction or something."
    "Before I can say anything more, the Merry-Go-Round lurches into motion."
    "Which practically throws me into the saddle of my own horse."
    "So I hold onto the pole as best I can, smiling the whole time."
    bree.say "You see?"
    bree.say "This is a great ride!"
    "I thought that the worst thing Sasha could do was argue back."
    "But somehow the fact that she chooses to ignore me is even worse."
    "And so I have to spend the rest of the ride trying to get her attention."
    "But no matter what I do, she just keeps on staring straight ahead."
    "Once the ride comes to an end, I open my mouth to speak again."
    "But I find Sasha holding a hand up to silence me."
    sasha.say "Don't say it, [hero.name]!"
    sasha.say "That was the single most boring ride ever."
    sasha.say "And even worse, it made my butt go to sleep!"
    $ sasha.love -= 2
    $ game.active_date.score -= 20
    return

label sasha_date_haunted_house_female:
    bree.say "Are you sure you're ready for the Haunted House, Sasha?"
    bree.say "These things are way scarier than you might think!"
    "We're already standing in the queue for the Haunted House."
    "And it's almost our turn to enter the attraction too."
    "But despite my warnings, Sasha doesn't seem at all worried."
    sasha.say "Are you kidding, [hero.name]?"
    sasha.say "I've played gigs at scarier places than this!"
    sasha.say "Don't worry about me, I'll be fine."
    "I give Sasha what I hope is a knowing look."
    "And then we step into the Haunted House together."
    "I'm waiting for the moment that all of this pays off."
    "When Sasha lets out her first scream of terror."
    "And I can bask in the glory of knowing that I was right all along."
    "But when the scares begin, that's not exactly how it plays out."
    sasha.say "Ha, ha..."
    sasha.say "Oh man, will you look at that?"
    sasha.say "It's like a lame Halloween costume!"
    bree.say "What gives, Sasha?"
    bree.say "Why aren't you screaming in terror?"
    sasha.say "Are you kidding, [hero.name]?"
    sasha.say "I started watching horror films when I was a little kid."
    sasha.say "None of this is even remotely scary!"
    "That sets the standard for the rest of the time we're in there."
    "With Sasha laughing her way around the Haunted House."
    "In the end I come to see the funny side of it all."
    "And I take comfort in the fact that Sasha seems to be having fun."
    $ sasha.love += 2
    $ game.active_date.score += 20
    return

label sasha_date_love_boat_female:
    sasha.say "Wait a minute..."
    sasha.say "That's all this ride is?"
    sasha.say "A crappy boat in a dark tunnel?"
    "I find myself smiling nervously at Sasha's reaction to the reality of the Love Boat."
    "Not least because we happen to be standing at the front of the line when she says all of this."
    bree.say "Erm..."
    bree.say "Yeah, Sasha..."
    bree.say "I kind of thought everyone knew that!"
    sasha.say "Well I didn't."
    sasha.say "And I wouldn't have stood in line all that time if I had!"
    "I take a look at the queue and then turn my attention back to Sasha."
    bree.say "Look, Sasha..."
    bree.say "It'd actually be quicker to ride the thing than push back through the queue."
    bree.say "And it'd also be a hell of a lot less embarrassing too!"
    "Sasha takes a look at the line for herself."
    "And then she nods, stepping into the boat as an admission of defeat."
    sasha.say "Okay, okay..."
    sasha.say "Just don't expect this to be romantic, okay?"
    "Sasha makes sure it's not too."
    "The tense few minutes that I spend in that boat are painful and awkward."
    "And about as far from romantic as it's possible to be."
    $ sasha.love -= 2
    $ game.active_date.score -= 20
    return

label sasha_date_hedge_maze_female:
    sasha.say "Huh..."
    sasha.say "You want to do the Hedge Maze, [hero.name]?"
    "I look up in surprise."
    bree.say "The Hedge Maze?"
    bree.say "Really?"
    "Sasha seems to prickle a little at my question."
    sasha.say "Why not?"
    sasha.say "What's so weird about me wanting to do that?"
    bree.say "Nothing, Sasha..."
    bree.say "Nothing at all!"
    "Sasha's still eyeing me suspiciously as we queue up for the maze."
    "But by the time we make it to the front of the line, she seems to have forgotten all about it."
    "Because she takes hold of my hand and pulls me inside the moment we're allowed in."
    sasha.say "Come on, [hero.name]..."
    sasha.say "Let's see if you can keep up with me!"
    "With that, Sasha vanishes around the first corner."
    "And I have to hurry to even keep her in sight."
    "What follows is a surprisingly enjoyable game of cat and mouse."
    "Sasha trying to avoid me as I do my best to chase her down."
    "And by the time we walk out of the exit, we're both exhausted."
    "But I feel like what we just did was good for us too."
    "Because it was pure, unadulterated fun."
    $ sasha.love += 2
    $ game.active_date.score += 20
    return

label sasha_date_amusement_ice_cream_female:
    sasha.say "Oh man, is it ever hot today..."
    sasha.say "We need to find a way to cool down, and fast!"
    "I hadn't realised just how hot it was until Sasha spoke up just now."
    "But I can already feel my throat drying out as I return her gaze."
    bree.say "Totally, Sasha..."
    bree.say "You're one hundred percent correct."
    bree.say "I'm completely parched!"
    "I gaze around for a moment, searching for a solution."
    "But all of the rides that involve getting wet already have huge queues."
    "Because I guess everyone else is already a couple of steps ahead of us."
    "Then I have a flash of inspiration."
    bree.say "ICE-CREAM!"
    bree.say "Sasha, we need to get ice-cream."
    "Sasha nods as soon as she hears my suggestion."
    sasha.say "That's a great idea, [hero.name]..."
    sasha.say "Quickly - to the ice-cream stand!"
    "Sasha adopts a dramatic pose, then dashes off."
    "Which leaves me to hurry along after her."
    "Luckily for us, the line for the ice-cream stand is shorter."
    "So we make it to the front in what feels like record time."
    "And soon enough we have our ice-creams in our hands."
    sasha.say "Good thinking, partner!"
    "I can't help smiling as Sasha praises me."
    "Feeling like we're partners in crime."
    "As well as partners in another sense entirely too."
    $ sasha.love += 2
    $ game.active_date.score += 20
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
