label danny_after_dance_success_with_female:
    show danny smile
    "As soon as I'm done dancing, I look up to see Danny staring at me."
    "I'm pretty self-conscious when it comes to stuff like dancing."
    "So I brace myself for the criticism that I think is coming my way."
    bree.say "Erm..."
    bree.say "So, Danny..."
    bree.say "What did you think of my dancing?"
    "Danny shakes his head."
    show danny surprised
    danny.say "Fuck me, [hero.name]..."
    danny.say "Where'd you learn to move like that?!?"
    show danny smile
    "That's a question, rather than flat out praise or criticism."
    "So I instantly feel the need to seek clarification from Danny."
    bree.say "Is that because it was good, or bad?"
    show danny surprised
    "Danny looks at me in amazement."
    "Like he really doesn't get what I mean."
    danny.say "Are you shitting me, [hero.name]?"
    danny.say "I aint never seen a girl move like that!"
    danny.say "Not even in the fanciest strip-joints I've ever been in!"
    show danny smile
    bree.say "Oh..."
    bree.say "I...I guess I should take that as a compliment!"
    "Danny's nodding furiously by now."
    "And I can be sure that he's impressed by my dancing."
    "Which coming from a guy as rough around the edges as he is, must really mean something!"
    show danny normal
    return

label danny_after_dance_failure_with_female:
    show danny annoyed
    "As soon as I'm done dancing, I look up to see Danny staring at me."
    "But if I was hoping to hear words of encouragement, it seems I'm destined to be disappointed."
    "And that's because he has a look on his face that's almost one of disgust!"
    bree.say "Erm..."
    bree.say "So, Danny..."
    bree.say "What did you think of my dancing?"
    "Danny shakes his head."
    show danny angry
    danny.say "Urgh..."
    show danny shout
    danny.say "I gotta be honest, [hero.name]..."
    danny.say "You really stunk up the place!"
    show danny annoyed
    "Even though I was trying to brace myself, the criticism still stings."
    bree.say "Oh come on, Danny..."
    bree.say "It can't have been that bad, surely?"
    "Danny shakes his head again."
    show danny shout
    danny.say "[hero.name]..."
    danny.say "I've seen a guy strung up by his neck."
    danny.say "And I seen someone hooked up to a car battery by his fucking nipples too."
    danny.say "Both of them jerked and twitched before they was put out of their misery."
    show danny joke
    danny.say "And both of them moved better than you did just now!"
    show danny normal
    return

label danny_halloween_invitation_female:
    show danny
    "Almost the moment I agreed to the Halloween party, I knew who I wanted to invite."
    "But I make a point of keeping it to myself until I can actually get to speak to him."
    "Because I don't want my housemates to know I'm inviting a bad boy like Danny."
    "Plus he's not the most reliable of guys too, so him saying yes isn't a given thing."
    "So I wait for what feels like the best time to invite Danny to the party."
    "Which seems to come when there are no major distractions such as alcohol around him."
    bree.say "Hey, Danny..."
    bree.say "Halloween party at my place."
    bree.say "You up for it?"
    "Danny looks at me with that crooked smile of his."
    "And he kind of shrugs, rather than nodding or shaking his head."
    danny.say "A party, huh?"
    danny.say "What kind of party are we talking about?"
    bree.say "Erm..."
    bree.say "I dunno, Danny..."
    bree.say "The kind you have on Halloween, I guess!"
    "Danny shakes his head at this."
    "Clearly not happy with my explanation."
    danny.say "Nah, [hero.name]..."
    danny.say "I mean is it a REAL party?"
    danny.say "Is there gonna be booze?"
    danny.say "And what about pussy too?"
    bree.say "Sasha, [mike.name] and me are all going to be there."
    bree.say "And I think we're having some punch."
    danny.say "Huh..."
    danny.say "Two types of pussy and some punch!"
    danny.say "Sounds like your party needs some serious livening-up!"
    "By now I'm getting pretty tired of answering Danny's questions."
    "So I try pressing him to answer mine instead."
    bree.say "Look, Danny..."
    bree.say "Do you want to come or not?"
    if danny.love >= 100:

        "Danny grunts and then makes a kind of weird motion with his head."
        "One that I choose to take as a nod, until I hear what he has to say."
        danny.say "Sure, [hero.name]..."
        danny.say "Sounds like it could be fun."
        danny.say "And if it isn't, then I'll make it fun!"
        "I'm already nodding and smiling."
        "Doing the best I can to ignore the implications of what Danny said last."
        "He's probably just trying to show off and make himself look scary."
        "I'm sure he'll behave himself on the big day."
        bree.say "Brilliant, Danny..."
        bree.say "It's a costume party too."
        bree.say "So you might want to think about that."
        bree.say "Unless you want people to think you came as an extra from a Rober Rodriguez film!"
        danny.say "Hey!"
        danny.say "That was uncalled for and offensive!"
        $ game.flags.halloween_girl = "danny"
    else:

        "Danny grunts and then makes a kind of weird motion with his head."
        "One that I think is him shaking it, much to my disappointment."
        danny.say "Nah, [hero.name]..."
        danny.say "I think I'll pass."
        "I feel the disappointment building up inside of me."
        "And I can't help shaking my head as I begin to argue."
        bree.say "Oh, come on, Danny!"
        bree.say "Please come to the party?"
        bree.say "It's going to be a costume party too."
        bree.say "Doesn't that sound like fun?"
        "Danny lets out a low, mean chuckle."
        "And he shakes his head again."
        danny.say "You I can handle, [hero.name]."
        danny.say "But I couldn't give a damn about any of those pussys you know."
        danny.say "I probably robbed half of them or sold them illegal shit in the past anyway."
    return

label danny_halloween_arrival_female:
    scene bg house
    "I open the door, eager to see who's out there and what they're wearing."
    "But what I see is someone with their back turned to me."
    "Plus they're hunched over and wearing some kind of cloak."
    "So it's really hard for me to see just who it might be too."
    bree.say "Erm..."
    bree.say "Hi there..."
    bree.say "You're here for the party, right?"
    "At the sound of my voice, the mysterious figure kind of turns and jumps."
    "They open up their cloak too, using their hands to hold it up like a pair of wings."
    danny.say "Mwah ha ha!"
    danny.say "I want to suck your tits!"
    "It's pretty obvious that what I'm seeing is just Danny in a cheesy vampire costume."
    "But for some reason I can't help letting out a yelp of alarm and leaping backwards."
    "Which means that I stumble into the doorstep and lose my footing."
    "The next thing I know, I'm landing on my ass!"
    bree.say "Argh!"
    bree.say "Whoa..."
    bree.say "Ouch!"
    danny.say "Shit, [hero.name]..."
    danny.say "Do I really look that scary?"
    "I'm picking myself up as Danny asks the question."
    "And I'm really more pissed that he's not helping me than him scaring me."
    bree.say "You just startled me, that's all."
    bree.say "And it's blood, Danny?"
    bree.say "Vampires drink blood, they don't suck tits!"
    danny.say "This one does both."
    danny.say "So?"
    danny.say "What do you think of my costume?"
    menu:
        "Compliment":
            "I'm still pretty sore about falling on my ass."
            "But I want the party to go well, and so I try to ignore the pain."
            "Forcing a smile onto my face, I give Danny what I hope is a cheery nod."
            bree.say "I wouldn't have had you down as a vampire, Danny."
            bree.say "But it works kind of well."
            bree.say "Kind of comes out of left-field, you know?"
            "Danny shakes his head at this."
            "But he's grinning at the same time."
            "So I take that as a good sign."
            danny.say "I have zero fucking idea what that means, [hero.name]!"
            danny.say "But it sounds good, so that's cool with me."
            danny.say "Now are you gonna let me in or not?"
            danny.say "I could murder a cold one."
            bree.say "Don't vampires drink warm blood?"
            danny.say "Fuck that - I want a damn beer!"
        "Criticize":
            "I'm still pretty sore about falling on my ass."
            "And it was totally Danny's fault that happened."
            "So he's going to get both barrels from me!"
            bree.say "Are you kidding, Danny?"
            bree.say "You look like Danny Trejo after he got bit by Dracula!"
            "Danny looks instantly hurt as I unload on him."
            "He even takes a step backwards and fiddles with his cloak."
            danny.say "Hey!"
            danny.say "That's a little mean, don't you think?"
            danny.say "I already told you I don't normally do this kind of shit."
            danny.say "You should be grateful I even tried!"
            "I roll my eyes and shake my head at this."
            "Then I step aside and usher Danny into the house."
            bree.say "Oh for god's sake, Danny..."
            bree.say "Will you come inside and stop sulking like a baby?"
            "Danny does as he's told."
            "But I can tell that he's still pretty butt-hurt."
            "Looks like I'm going to have to salve his ego a little."
    scene bg black with dissolve
    $ renpy.pause(1)
    return

label danny_halloween_party_female:
    $ game.pass_time(2)
    scene bg livingroom
    show mike halloween at left5
    show danny halloween normal at right5
    with dissolve
    "I'm just grabbing a refill from the punchbowl for Danny and myself."
    "Which means my attention is totally focussed on the cup and ladle."
    "But I can hear the altercation going on long before I get back with the drinks."
    "And as I do the source of all the noise becomes painfully apparent."
    "[mike.name]'s pretty much squaring up to Danny, who seems more amused than afraid."
    "In fact I make it over just in time to see Danny give [mike.name] a shove in the chest."
    "I mean, [mike.name] was invading his personal space."
    "But that doesn't mean Danny's okay to put his hands on my housemates!"
    danny.say "Back up, little man..."
    danny.say "You don't know who you're messing with!"
    mike.say "I'm not scared of a scumbag like you!"
    mike.say "If we call the cops, you'll soon change your tune."
    "Putting the drinks down, I push my way between the two of them."
    "Which isn't easy when they're such a pair of beefcakes."
    "But luckily for me, they're both high on testosterone."
    "So I can kind of take them by surprise."
    bree.say "Break it up, you two!"
    bree.say "What the hell is going on here?"
    "Danny's been in situations like this many times before."
    "So he just holds up his hands and takes a step backwards."
    "Probably confident that he can talk his way out of it."
    "And fully aware of the value that comes with not having thrown the first punch."
    "But [mike.name]'s blood is up, and he instantly leaps in."
    mike.say "He was sizing the place up, [hero.name]..."
    mike.say "Checking out all of our stuff."
    mike.say "Probably planning to come back and rob us after the party!"
    danny.say "Bullshit!"
    danny.say "Sure, I was checking your shit out."
    danny.say "It's impressive shit!"
    danny.say "But that's all I was doing."
    menu:
        "Defend Danny":
            "I know that [mike.name]'s not being a prick on purpose."
            "He's just trying to defend his home."
            "But I feel for Danny in a situation like this."
            "And it's not fair that people stereotype him all the time."
            bree.say "Danny's my date tonight, [mike.name]."
            bree.say "And that means that I'm vouching for him."
            bree.say "So if you have a problem with him..."
            bree.say "Then talk to me, okay?"
            "[mike.name] scowls at this, and he shoots Danny a mean glance."
            mike.say "If you say so, [hero.name]."
            mike.say "But I'm going to be watching this guy."
            "With that, [mike.name] turns and walks off."
            "Danny watches him go, chuckling to himself."
            danny.say "You sure told his ass off, [hero.name]!"
            bree.say "I wish I hadn't had to, Danny."
            bree.say "[mike.name]'s not a bad guy really."
            bree.say "So please don't confirm his suspicions, yeah?"
            "Danny looks at me in surprise."
            "And for a moment I think he's going to mock me."
            "But then he nods."
            danny.say "Whatever, [hero.name]..."
            danny.say "I'll be on my best behaviour the rest of the night."
        "Defend [mike.name]":
            "I feel for Danny in a situation like this."
            "And it's not fair that people stereotype him all the time."
            "But he doesn't do himself any favours with his cocky attitude."
            "Plus I have to live under the same roof as [mike.name]."
            "So I don't want to piss him off."
            bree.say "He wasn't going to burglarize us, [mike.name]."
            "As soon as I say this, [mike.name] looks annoyed."
            "Whereas Danny rolls his eyes."
            bree.say "But you could try to act more like a party guest..."
            bree.say "And less like a home invader, Danny!"
            "Now their expressions have pretty much swapped places."
            "[mike.name] looks triumphant as he turns and walks away."
            "But Danny scowls at me, clearly not pleased."
            danny.say "What the fuck, [hero.name]?"
            danny.say "I already told you I didn't do nothing!"
            bree.say "Come on, Danny..."
            bree.say "I know you can't help it."
            bree.say "But you do look like a one-man crimewave!"
            "Danny looks down at his feet and mutters something under his breath."
            "Great, so he's going to be sulking for the remainder of the party."
            "But at least that's better than him getting into fights with my housemates."
    scene bg black with dissolve
    $ renpy.pause(1)
    return

label danny_halloween_dance_female:
    $ game.pass_time(2)
    scene bg livingroom
    show danny halloween
    with dissolve
    "I'm dividing my attention between the dancefloor and Danny's right arm."
    "And that's because I want to get out onto the former as soon as possible."
    "But all he seems to want to do is raise the latter to his lips!"
    bree.say "Danny..."
    bree.say "How many glasses of punch have you had?"
    "Danny pauses, the glass a couple of inches from his lips this time."
    danny.say "Huh?"
    danny.say "What's that got to do with anything?"
    bree.say "I want to dance, that's what."
    bree.say "At this rate you won't be able to stand up soon."
    bree.say "Let alone do any dancing!"
    "Danny shakes his head and then drains the contents of his glass."
    danny.say "Ah..."
    danny.say "Who wants to dance anyway, [hero.name]?"
    danny.say "Dancing's for losers!"
    bree.say "I already told you - I want to dance!"
    "But for all my pleading, it's clear Danny won't be swayed."
    menu:
        "Dance alone":
            "I think about staying put and waiting for a while."
            "Then asking Danny to dance again a little later."
            "But at the rate he's going, he'll be on his ass by then!"
            "So I decide to take matters into my own hands."
            bree.say "Stay here if you want, Danny..."
            bree.say "I'm going to go dance on my own."
            danny.say "Whatever, [hero.name]..."
            danny.say "You go dance with all those losers!"
            "I turn my back on Danny and walk out onto the dancefloor."
            "Doing it quickly before I have the urge to say something I might regret."
            "But once I'm out there, it doesn't take long for my mood to change."
            "And it's for the better too, as Sasha and [mike.name] soon come to join me."
            "There must be something happening on the dancefloor too."
            "Because Jack and Scottie aren't far behind them."
            "I keep stealing a glance at Danny as we all dance together."
            "And I can see that he's looking pretty pissed."
            "He does the best he can to cover it up with his macho posturing."
            "But I know that he's regretting his decision not to dance."
            "Which makes the experience of dancing all the more enjoyable."
        "Stay with Danny":
            "I think about just going out there and dancing on my own."
            "But that's just going to make me look like some kind of loser."
            "The kind that can't even get a dance out of her own date."
            "So I just shake my head and resolve to leave it for now."
            "Maybe I can convince Danny to change his mind later."
            "But until then, perhaps I should be having a drink too."
            bree.say "Danny..."
            bree.say "I'm going to grab some punch."
            "Danny doesn't even look in my direction."
            "He just holds out his glass and nods."
            danny.say "Great, sweet-cheeks..."
            danny.say "Get me a refill while you're at it."
            "It's not a request, more a straight-up demand."
            "And I find myself fuming all the way to the punchbowl and back."
    scene bg black with dissolve
    $ renpy.pause(1)
    return

label danny_halloween_sex_female:
    scene bg livingroom with dissolve
    "The party's been going a good few hours now, and the atmosphere is better than it's ever been."
    "We're well past the point where I have to worry about things not working out or going wrong."
    "All of the guests seem to be in a good mood, and the general vibe is moving towards chilled."
    "So now would be a good time to sit back and just enjoy the fruits of my labour."
    "And I intend to do just that, until I feel the sensation of someone taking my hand."
    "I look down to where fingers are intertwining themselves with mine."
    "They're pretty big, manly fingers."
    "And the hand they belong to is covered in tattoos and rings too."
    "So there's no question in my mind as to who's hand it is."
    show danny halloween at center, zoomAt(1.5, (640, 1040)) with fade
    bree.say "Hey, Danny..."
    bree.say "How are you liking the party?"
    "Danny doesn't answer me straight away."
    "Instead he kneels down in front of me, lifting my hand to his mouth."
    danny.say "Mmm..."
    danny.say "It's all good, [hero.name]..."
    danny.say "But I'm gagging for some blood right now!"
    "Danny underlines this by kissing the back of my hand."
    "And he looks up at me too, adding a wink as well."
    "He's being so corny and campy that I can't help giggling."
    "Putting a hand to my forehead, I start playing the part of the swooning damsel."
    bree.say "Oh, but, Mister Vampire..."
    bree.say "I don't think I have that much blood in my veins."
    bree.say "Not enough to satisfy a big, strapping blood-sucker like you!"
    danny.say "Nah, no need to worry."
    danny.say "I can drink other stuff too."
    danny.say "You just gotta let me suck it up!"
    "I'm enjoying the chance to joke and flirt with Danny like this."
    "But for a moment he seems to break character as he leans in closer."
    danny.say "Erm..."
    danny.say "We're both going the same way, right?"
    danny.say "Like, we're gonna go fool around after this?"
    bree.say "That's the way I was seeing it, Danny..."
    "This seems to be the answer that Danny was wanting to hear."
    "Because he instantly switches back to his corny vampire impression."
    "Drawing himself up to his full height, he takes me by the hand."
    danny.say "So let's go to my creepy tomb."
    danny.say "And there we can do creepy vampire stuff!"
    "I'm kind of expecting Danny to make straight for my bedroom."
    "So it comes as something of a surprise when he makes for the closet instead."
    bree.say "Erm..."
    bree.say "Danny..."
    bree.say "Are you serious?"
    danny.say "Aw, come on bree!"
    danny.say "I'm doing my best here..."
    danny.say "Just work with me, yeah?"
    "I roll my eyes and then nod my head, letting Danny usher me inside."
    "Once the door is closed behind us, it's as cramped as I expected it to be."
    danny.say "Geez, [hero.name]..."
    danny.say "Kind of ironic it's so dirty in here."
    danny.say "You know, what with it being where you keep all the cleaning stuff?"
    bree.say "Can we stop with the observations on domestic cleanliness, Danny?"
    bree.say "You're the one that wanted to come in here and play make-believe, remember?"
    danny.say "Oh..."
    danny.say "Okay..."
    danny.say "Bend over, and prepare to be staked!"


    "The pedantic side of my nature wants to point out that it's the vampire that gets staked."
    "But after all of the arguing and manoeuvring to get in here, I just decide to leave it."
    "Instead I turn my back on Danny and oblige him by pulling down the bottom half of my costume."
    "At the same time I bend over, pushing my ass backwards and into him."
    "Because I have to admit, the idea of doing it in here is pretty exciting."
    "One thing that my actions seem to do is cure Danny of the need to speak."
    "And it's kind of a relief to be spared his crappy vampire impression."
    "Instead I hear the sound of him unzipping his flies behind me."
    "As well as the way he's chuckling quietly."
    "That's more than enough to make me want what's coming next."
    "His bad boy persona is such a turn-on in situations like this."
    "And the moment I feel him clap his hands on my thighs..."
    "Well, let's just say that I'm more than ready for him down there!"
    "It's not like Danny's the kind of guy to beat about the bush either."
    "Which means that he wastes no time in thrusting himself forwards."
    "And at the same time he's also pulling me back."
    "This means that I feel the head of his cock pressing against me."
    "Even that's enough to send a shiver of pleasure through my entire body."
    "And I can't help wriggling backwards, doing all I can too push my ass into him."
    "All of this means that it doesn't take long for my muscles to surrender."
    "As soon as they do, I feel Danny start to push his way inside."
    "He's not subtle about it either, going as deep as he can as fast as he can too."
    "But at the same time, for all of his bravado, Danny's not a brute either."
    "I can tell how much he's enjoying the sensations of being inside me."
    "Yet I also know that he's getting off on how much I'm loving it too."
    "He knows that I want it fast and frantic, and he's not holding back."
    "Bracing my arms against the wall, I make sure to nod my head."
    "Letting Danny know that I want him to go for it."
    "And he doesn't disappoint me either."
    "Instantly picking up speed, his efforts make me throw back my head."
    "And in the next moment it falls back down again, below my shoulders."
    "Because from that point on, all I can do is hold on for dear life."
    "Danny lives up to his reputation, taking me on a roller-coaster ride."
    "And every last ounce on energy left over from the party is eaten up."
    "I don't know which one of us is the first to cum."
    "Just that I feel the wave of my own orgasm as he shoots his load inside me."
    "Afterwards I slump into the wall, my face pressed against it."
    "And it's all that I can do to reach down and pull things up again."
    "All that I'm good for then is to stagger to my room and collapse onto the bed."
    $ danny.sexperience += 1
    $ game.pass_time(1)
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
