label mike_date_amusement_park_female:
    scene bg amusement
    show mike
    with fade
    "Normally I find myself having to convince my dates to come to the Amusement Park with me."
    "And even when they do, I get the feeling it's more because they're indulging me than them wanting to be there."
    "But the moment I floated the idea in front of [mike.name], he was totally up for it."
    "And now that we're walking up to the gates, he can't wait to get into the place."
    show mike
    mike.say "Come on, [hero.name]..."
    mike.say "We have to hurry it up!"
    show mike smile
    bree.say "Oh my god..."
    bree.say "I was just about to say the same thing!"
    show mike happy
    "[mike.name] nods with evident enthusiasm."
    show mike shout
    mike.say "I hate it when people dawdle around outside the gates."
    mike.say "It's just time wasted..."
    mike.say "Time we could have spent waiting in line for the rides!"
    show mike smile
    "My head's nodding away too."
    "Because it's like [mike.name]'s reading my mind."
    bree.say "Totally!"
    bree.say "Like, why do people have to stop and think about the rides they want to do too?"
    bree.say "Why can't they do that while they're running into the park to save time?"
    show mike shout
    "[mike.name] almost stops moving as he looks at me in sheer amazement."
    "But I note that he manages to fight the urge and keep moving."
    show mike happy
    mike.say "My god, [hero.name]..."
    mike.say "It's like we're thinking alike..."
    mike.say "Like we each have half of the same brain!"
    show mike smile
    bree.say "Erm..."
    bree.say "I'm not sure that came out the way you meant it to, [mike.name]!"
    bree.say "But whatever - let's hit the rides!"
    "And with that, we plunge deeper into the park."
    "Already eyeing up the rides as we do so."
    return

label mike_date_ferris_wheel_female:
    mike.say "Ferris Wheel!"
    mike.say "[hero.name], let's do the Ferris Wheel!"
    "I look round to see [mike.name] pointing at the ride in question."
    "In fact he's almost jumping up and down on the spot!"
    bree.say "You're sure you want to ride that, [mike.name]?"
    bree.say "Not something more modern and exciting?"
    mike.say "No way, [hero.name]..."
    mike.say "It's a classic!"
    "I shrug as I allow [mike.name] to pull me towards the Ferris Wheel."
    "Then we join the back of the line and wait for our turn."
    "The line is short, so we make it to the front quickly."
    "[mike.name] leaps into the gondola, patting the seat beside him."
    "And I step inside so that the safety-bar can come down."
    "[mike.name]'s tapping his hands on the bar as we rise into the air."
    "Almost like he's got too much energy inside of him."
    "And he needs some way to release it."
    "I have to admit that the view only gets better the higher we go."
    "And once we reach the top, it almost takes my breath away."
    bree.say "Oh wow..."
    bree.say "I don't think I've ever seen the city like this!"
    mike.say "You see what I mean, [hero.name]?"
    mike.say "This is better than the view from a tall building."
    mike.say "Totally panoramic!"
    "We spend the rest of the time on the ride enjoying the view."
    "And even when we get off the ride, [mike.name] and I are still smiling."
    $ mike.love += 2
    $ game.active_date.score += 20
    return

label mike_date_merry_go_round_female:
    bree.say "How about we ride the Merry-Go-Round, [mike.name]?"
    bree.say "The queue's pretty short, and it's moving fast."
    bree.say "So that kind of makes up for it being an old ride, right?"
    "[mike.name] nods at this, like he's accepting the logic of my argument."
    "But at the same time there's something else going on behind his eyes."
    mike.say "That sounds good to me, [hero.name]..."
    mike.say "But there's something bugging me."
    mike.say "Something about that ride..."
    mike.say "I just can't remember what it is!"
    bree.say "So what?"
    bree.say "Do we ride it or not?"
    "[mike.name] shrugs as he starts to walk towards the Merry-Go-Round."
    mike.say "It can't be that important."
    mike.say "Not if I forgot all about it."
    mike.say "So let's go ride the Merry-Go-Round."
    "We walk over and join the line, quickly making it to the front."
    "[mike.name] and I pick spots next to each other on the ride."
    "Then we hold on tight, waiting for it to start."
    mike.say "Oh yeah..."
    mike.say "I just remembered what..."
    mike.say "Whoa..."
    "The moment that [mike.name]'s about to tell me what he remembered, the ride starts to move."
    "And it does so with a jerk that sends him grasping for the pole in front of him."
    "Assuming that it couldn't have been that important, I turn my gaze forwards."
    "And I spend the rest of the ride looking in that direction too."
    "It's only when the ride starts to slow and come to a stop that I look back at [mike.name]."
    "Which is when I see that he's turned an unhealthy shade of green!"
    "He slides out of his seat and runs away from the Merry-Go-Round."
    "Plus he's swaying from side to side as he goes."
    show mike sad
    "When I catch up to [mike.name], he's heaving up into a litter bin."
    mike.say "Urgh..."
    mike.say "Now I remember..."
    mike.say "Merry-Go-Rounds give me motion sickness!"
    $ mike.love -= 2
    $ game.active_date.score -= 20
    return

label mike_date_haunted_house_female:
    mike.say "The Haunted House!"
    mike.say "That's one of my all-time favourites!"
    bree.say "Me too, [mike.name]..."
    bree.say "We have to go in there!"
    "[mike.name] and I make straight for the Haunted House."
    "Even pushing people out of the way to get there."
    "But we manage to regain control of ourselves as we reach the queue."
    "Which means that we can stand in line like civilised people."
    "Though all of that seems to change once we make it to the front."
    "Because now our excitement is getting to be too much to keep in check."
    bree.say "Okay..."
    bree.say "Here we go!"
    mike.say "I know, I know..."
    mike.say "Prepare to be scared!"
    "[mike.name] and I hurry into the Haunted House, waiting for the first scare."
    "And when it comes, the sensation is...underwhelming."
    bree.say "Oh..."
    bree.say "I kind of saw that coming."
    mike.say "Me too, [hero.name]..."
    mike.say "Pretty obvious place to put it."
    bree.say "Well, maybe the next one will be better."
    "But it isn't."
    "If anything the scares only get more predictable as we move on."
    "Which also means the experience becomes less scary too."
    "By the time we walk out of the exit, we're bored stiff."
    bree.say "I don't get it, [mike.name]..."
    bree.say "I normally love the Haunted House."
    mike.say "I don't think it was us, [hero.name]."
    mike.say "That was just a lame example of one, that's all."
    $ mike.love += 1
    $ game.active_date.score += 10
    return

label mike_date_love_boat_female:
    bree.say "Maybe we should ride the Love Boat next, [mike.name]?"
    bree.say "You know, for a change of pace?"
    "As soon as I mention the Love Boat, [mike.name] begins to smile."
    "He leans in close and gently elbows me in the ribs."
    mike.say "Oh, I see..."
    mike.say "I know what you mean by 'change of pace', [hero.name]!"
    "I roll my eyes at this."
    "And I fix [mike.name] with a hard stare."
    bree.say "Then you should know not to push my buttons, yeah?"
    bree.say "Because I can always ride the thing on my own, [mike.name]!"
    "This has the desired effect on [mike.name]."
    "As he instantly drops the act and stops being a jerk."
    mike.say "Oh..."
    mike.say "Oh sure, [hero.name]..."
    mike.say "I totally get what you mean!"
    "[mike.name] scuttles along after me as I walk over to the queue for the ride."
    "And he behaves himself all the time we're standing in line too."
    "So much so, that once we're in the boat, I have to say something."
    bree.say "[mike.name]..."
    mike.say "Yeah, [hero.name]?"
    bree.say "It's okay."
    bree.say "You can stop behaving now!"
    "And I'm glad to say that [mike.name] does exactly as he's told from that point on."
    "So much so that both of us thoroughly enjoy the rest of the ride."
    $ mike.love += 2
    $ game.active_date.score += 20
    return

label mike_date_hedge_maze_female:
    mike.say "Urgh..."
    mike.say "[hero.name]..."
    mike.say "Do we really have to do the Hedge Maze?"
    "I turn to face [mike.name] as we're standing in the queue."
    "Crossing my arms over my chest to show that I'm serious."
    bree.say "Yes, [mike.name]..."
    bree.say "We really do have to do it."
    bree.say "Because we're already in the line."
    bree.say "And more importantly, because I want to!"
    show mike down
    "[mike.name] goes to open his mouth."
    "But I cut him off before he can say a word."
    bree.say "So shut up and start enjoying yourself!"
    "[mike.name] keeps on muttering the rest of the time we're waiting."
    "And even when we're inside the maze, he keeps on sighing to himself."
    "In the end it gets so distracting that I have to turn around and confront him."
    bree.say "[mike.name]..."
    bree.say "Will you stop!"
    bree.say "You're moaning so much that I'm getting lost!"
    mike.say "That's not my fault, [hero.name]..."
    mike.say "I didn't even want to come in here."
    mike.say "It's dull and it's boring!"
    bree.say "Well at least keep quiet while I find the way out!"
    mike.say "Alright, I won't say another word."
    bree.say "That's what I asked you to do."
    mike.say "Well I'm doing it."
    bree.say "Good, you do that."
    mike.say "I will."
    bree.say "Great."
    mike.say "Perfect."
    "We manage to keep squabbling the whole time that we're in the maze."
    "But once we're out of there, the spell seems to be broken, and we stop."
    "That leaves us both feeling awkward and irritable."
    "Though it's better than being in that damn maze."
    $ mike.love -= 2
    $ game.active_date.score -= 20
    return

label mike_date_amusement_ice_cream_female:
    bree.say "Hey, [mike.name]..."
    bree.say "It is WAY too hot today, yeah?"
    bree.say "We should get some ice-cream."
    "[mike.name] looks at me like I just told him we won the lottery or something."
    "The smile on his face almost making him look like he's losing his mind."
    mike.say "Like you need to ask?!?"
    mike.say "Come on, [hero.name]..."
    mike.say "That queue's not getting any shorter!"
    "[mike.name] turns and makes straight for the ice-cream stand."
    "Which leaves me to follow in his wake."
    "More than once I think he's going to barge into someone."
    "But somehow he manages to steer his way through the crowd."
    "And before I know it, we're standing in line."
    mike.say "Have you made your mind up yet, [hero.name]?"
    mike.say "Which one are you going to choose?"
    "I point at the ice-cream that I had in mind."
    bree.say "Erm..."
    bree.say "I was going to go for one of those?"
    mike.say "Okay, [hero.name]..."
    mike.say "I got this!"
    "[mike.name] steps forwards, already speaking to the server."
    "So I choose to stand back and let him take charge."
    "But when he turns around with my order, my eyes bulge."
    bree.say "WHOA!"
    bree.say "What in the hell is that?!?"
    mike.say "It's what you wanted, [hero.name]."
    bree.say "Yeah, but it's like, the largest size possible..."
    bree.say "And with all the trimmings too!"
    "[mike.name] shrugs as I take the huge, teetering ice-cream from him."
    "And then he starts to lick his own, leaving me to it."
    mike.say "You know how it is, [hero.name]..."
    mike.say "Go hard or go home!"
    bree.say "Are you serious, [mike.name]?"
    bree.say "We're talking about ice-cream, not international athletics!"
    $ mike.love -= 2
    $ game.active_date.score -= 20
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
