label angela_date_amusement_park_female:
    scene bg amusement
    show angela smile
    with fade
    "It feels kind of weird going to the Amusement Park with Angela."
    "Not least because of the age difference between the two of us."
    "But there's also the fact that she's [mike.name]'s mom too."
    "I mean, it's not like I feel as though she's the parent and I'm the kid here."
    "I'm sure I've already got over that weird idea and put it well out of my mind."
    "No, it's more like I can't help wondering if she brought [mike.name] here as a kid."
    "I don't know if they lived around here back then, or moved here when he was older."
    "Whatever the case, it's a strange image."
    show angela talkative
    angela.say "[hero.name]..."
    angela.say "Are you okay?"
    show angela normal
    "I can't help being a little startled as Angela interrupts my train of thought."
    "But I do the best I can to recover and look like there's nothing the matter."
    bree.say "What?"
    bree.say "Oh...oh no!"
    bree.say "I'm fine, Angela."
    show angela talkative
    angela.say "Are you sure?"
    angela.say "It looked like you were miles away just now."
    show angela normal
    "I shake my head, smiling and trying to dismiss Angela's concerns."
    bree.say "I was just thinking about this place."
    bree.say "It's been a while since I last came here, that's all."
    show angela smile
    "Angela nods at this."
    show angela talkative
    angela.say "I know that feeling!"
    show angela happy
    angela.say "I used to bring [mike.name] and Minami to places like this all the time."
    angela.say "Well...that was until they started being embarrassed at my being there!"
    show angela a smile
    "Angela smiles, but I can see that there's some tension in her as she does so."
    "And not for the first time, I get the impression that her age is bothering her."
    bree.say "That's their loss, Angela."
    bree.say "I can't wait to spend some time with you in there."
    "This seems to have the desired effect on Angela's mood."
    show angela happy
    "Her smile becomes more genuine, and she takes hold of my hand."
    "Then we walk into the park together, determined to have some fun."
    return

label angela_date_ferris_wheel_female:
    angela.say "Oh look, [hero.name]..."
    angela.say "They have a Ferris Wheel."
    bree.say "Yeah, Angela..."
    bree.say "What's so strange about that?"
    "Angela looks a little embarrassed as I say this."
    "But she soon shakes it off and explains herself."
    angela.say "Well, aren't they very old?"
    angela.say "I thought places like this only had modern rides?"
    "I feel the urge to make some kind of comment."
    "Something about old ones being classics."
    "But then I realise Angela might think I was talking about her too."
    "So I do the best I can to keep away from any such reference."
    bree.say "I guess they like to mix it up here."
    bree.say "Kind of have the old and the new together?"
    "In the time that we've been talking, we haven't been paying attention to where we're stood."
    "And once we do, Angela and I find that we've somehow ended up in the middle of the queue."
    "As soon as we realise, we both make to extricate ourselves from it."
    "But then, as one, we stop and exchange a shrug."
    bree.say "You want to ride it?"
    bree.say "Because the queue seems short."
    angela.say "Sure, why not?"
    angela.say "We are here to have fun."
    "Pretty soon we're stepping into one of the gondolas."
    "And then we start to rise up and into the air."
    "Angela and I look out, taking in the view."
    "There doesn't seem to be any need for anyone to say a word."
    "Because the silence that prevails is so easy and natural."
    "Though I do get a pleasant surprise when Angela reaches over and takes hold of my hand."
    "Even more so when she keeps hold of it after we get off the ride and walk back into the crowds."
    $ angela.love += 1
    $ game.active_date.score += 10
    return

label angela_date_merry_go_round_female:
    bree.say "You want to ride the Merry-Go-Round, Angela?"
    bree.say "Looks like the queue for that ride is pretty short."
    "Angela stares at the Merry-Go-Round for a moment."
    "Like she's really weighing up the pros and cons."
    "Which is kind of amusing, as it's just a quick ride."
    angela.say "Okay, [hero.name]..."
    angela.say "Let's give it a try."
    "Angela and I walk over to join the back of the queue."
    "And I'm proven right, as we quickly move up the line."
    "Once we're at the front, we're let onto the ride."
    "Angela picks out the spot that she wants."
    "And I make sure to get the one right next to her."
    "Soon enough, the ride starts up and we're spun around ever faster."
    "We start to go up and down too, moving in time to the music that's playing."
    "So fast in fact that I have to cling onto the pole in front of me."
    "And I make sure to keep a tight hold on it until the ride begins to slow again."
    "Once it comes to a stop, we climb down and make to walk away."
    "But I find that it's left me a little jelly-legged."
    "So I can't help staggering as I try to keep up with Angela."
    "She notices this, and hurries to help me along."
    "Though I note that she's chuckling as she does so."
    bree.say "Hey!"
    bree.say "Either help me or take the piss, Angela..."
    bree.say "Make up your mind!"
    angela.say "Oh come on, [hero.name]..."
    angela.say "It is pretty funny."
    angela.say "I mean there were children on that ride just now."
    angela.say "And none of them were getting dizzy!"
    $ angela.love += 1
    $ game.active_date.score += 10
    return

label angela_date_haunted_house_female:
    angela.say "Oh look..."
    angela.say "They have a Haunted House!"
    angela.say "Those things always remind me of Halloween."
    "I'm not usually crazy about going inside those things."
    "But I want to do all I can to impress Angela."
    "So I start walking straight towards it."
    bree.say "Then let's go do it, Angela."
    bree.say "It looks like fun."
    "Angela nods happily as she follows me over to the ride."
    "And we're soon joining the back of the queue."
    angela.say "Of course with the experiences I've had in my professional career..."
    angela.say "I know that all of this stuff is superstitious nonsense."
    angela.say "It's just things jumping out of the dark to scare you."
    bree.say "Oh, totally, Angela..."
    bree.say "You just have to keep your head and think logically."
    bree.say "There's nothing in there that could possibly hurt us."
    "Just as I finish saying this, we get to the front of the line."
    "So I give Angela what I hope is a confident smile."
    "And then we step into the Haunted House."
    "Everything goes according to plan from then on."
    "Right up until the moment the first scare hits."
    bree.say "AAARGH!"
    bree.say "FUCK!"
    angela.say "[hero.name]!"
    angela.say "It's just a puppet on a spring!"
    bree.say "SHIT!"
    bree.say "Get me the hell out of here!"
    "With that, I'm off and sprinting through the Haunted House."
    "Trying to get out of there as fast as I can, I blunder into everything."
    "And I jump at each scare that pops up in front of me."
    "I make it out of the exit well before Angela."
    "And when she finally catches up to me, I have my head between my knees."
    bree.say "Urgh..."
    bree.say "Oh god..."
    angela.say "Erm..."
    angela.say "There there..."
    "I feel Angela patting me lightly on the back, like she doesn't know what else to do."
    angela.say "I think we should forget that this ever happened, okay?"
    "I do the best I can to nod, totally sharing the sentiment."
    $ angela.love += 1
    $ game.active_date.score += 10
    return

label angela_date_love_boat_female:
    show angela normal
    "As soon as I see the sign for the Love Boat, my mind's made up."
    "Sure, I feel a little sleazy suggesting it to Angela."
    "But the idea of being alone with her in the darkness..."
    "Oh man - it just sends a shiver down my spine!"
    bree.say "Angela..."
    bree.say "We should really ride the Love Boat!"
    "At the mere mention of the words, Angela seems to stiffen a little."
    "And she starts shaking her head even before she turns to face me."
    angela.say "Oh dear..."
    angela.say "I don't think that would be a good idea, [hero.name]!"
    "I know that I should be sensitive to Angela's feelings."
    "But I can't help seeing her refusal as kind of a slap in the face!"
    bree.say "What do you mean, Angela?"
    bree.say "Don't you want to be seen on a ride like that with me?"
    "Now Angela really looks conflicted."
    "She keeps on glancing at the ride and then back to me."
    "But finally she shakes her head."
    angela.say "N...no, [hero.name]..."
    angela.say "Of course not!"
    angela.say "Let's go on the ride, okay?"
    "I nod and we walk over to join the queue."
    "But it doesn't feel like I've won."
    "Because I've basically guilted Angela into doing what I wanted."
    "Even worse, I still have no idea what her problem was in the first place."
    "Angela has a forced smile on her face as we step into the boat."
    "And I could swear that she looks a little pale too."
    "But things become even more dramatic as we sail into the darkness."
    "Because that's when Angela leans over the side of the boat."
    "And I hear the sound of her heaving up into the water!"
    "All I can do is sit there for the rest of the ride."
    "Uncomfortably watching her puking up the contents of her stomach."
    "Luckily she seems to be done before the ride ends."
    "Which means I can simply walk her over to a nearby bench."
    bree.say "Angela!"
    bree.say "Why didn't you tell me you get seasick?!?"
    angela.say "I'm sorry, [hero.name]..."
    angela.say "I was worried you'd think I was embarrassed to be seen with you!"
    "All I can do is shake my head in astonishment."
    "Amazed that Angela would go so far to protect my feelings."
    "And that I could be so dumb as to not pick up on it too!"
    $ angela.love -= 2
    $ game.active_date.score -= 20
    return

label angela_date_hedge_maze_female:
    angela.say "Ooh..."
    angela.say "A hedge maze!"
    angela.say "I remember visiting one of these when I was a little girl!"
    "Angela doesn't wait for me to say anything in response to all that."
    "Instead she pulls me straight over to the queue for the Hedge Maze."
    bree.say "Whoa..."
    bree.say "Slow down!"
    bree.say "Urgh...I guess that means we're going into the maze?"
    "Angela nods happily as we begin to work our way up the line."
    "And she becomes more animated as we make it to the front."
    "Once we're inside, she practically claps her hands together with glee."
    angela.say "Well, [hero.name]..."
    angela.say "Are you ready?"
    bree.say "Huh?"
    bree.say "Ready for what?"
    angela.say "Ready to catch me!"
    "With that, Angela literally turns on her heel and runs away."
    "She's disappeared around the first corner before I even know what's happening."
    "The only choice I'm left with is to run after her."
    "What follows is a breathless chase around the entire maze."
    "I keep catching glimpses of Angela in the corner of my eye."
    "Or else I hear the sound of her laughter nearby."
    "But I never seem to be able to catch up to her."
    "And when she finally sneaks up on me, I jump out of my skin."
    angela.say "Gotcha!"
    bree.say "Argh!"
    angela.say "Oh, [hero.name]..."
    angela.say "I wish you could see the look on your face!"
    "I nod and smile, trying to be a good sport."
    "But the truth is that I can see the look on Angela's face right now."
    "And the unfettered happiness I see there is enough to tell me this was a great idea."
    $ angela.love += 2
    $ game.active_date.score += 20
    return

label angela_date_amusement_ice_cream_female:
    bree.say "Oh look, Angela..."
    bree.say "There's an ice-cream stand."
    bree.say "You want to grab a couple?"
    "Angela looks in the direction that I'm pointing."
    angela.say "You know what, [hero.name]..."
    angela.say "That would be really nice."
    angela.say "It feels like forever since I had an ice-cream."
    "With a nod and a smile, I lead the way to the stand."
    "Angela follows close on my heels and soon we're ready to order."
    bree.say "I feel like getting one of those."
    "I point to one of the ice-creams that catches my eye."
    "Angela nods, but points to a different one for herself."
    angela.say "I think I'll have a cone."
    angela.say "And I'm going to ask them to pile it high too!"
    "Angela says this in a voice filled with mischief and glee."
    "Almost like we're doing something wicked and it's making her feel naughty."
    "All of which means that I can't help smiling and nodding to encourage her."
    "Soon enough we have our ice-creams and we're walking away from the stand."
    "Angela's trying to lick her cone, btu that's proving a challenge."
    "Because the thing really is stacked dangerously high."
    angela.say "Oh..."
    angela.say "Oh dear..."
    angela.say "I don't think that I can..."
    "I watch as Angela's ice-cream teeters and then falls."
    "And a large blob of it falls straight onto her chest."
    "Both of us stare down at it in silence for a moment."
    "Then she pulls out a handkerchief and begins to clean herself up."
    "Which leaves me to marvel at the fact not a drop of it touched the ground!"
    $ angela.love += 0
    $ game.active_date.score += 0
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
