label shawn_date_amusement_park_female:
    scene bg amusement
    show shawn smile
    with fade
    "I'm pretty stoked to be getting the chance to visit the Amusement Park."
    "It's one of my favourite things to do when I just want to have some fun."
    "And so I can't keep from beaming with excitement as we're walking up to the gate."
    "But when I take a glance at Shawn, walking beside me, he doesn't look as excited."
    "I mean, sure, he's smiling away."
    "But the expression on his face looks more ironic than anything else."
    bree.say "What's the matter, Shawn?"
    bree.say "I thought you'd be well up for this."
    bree.say "You're a nerd, you like doing fun stuff."
    bree.say "So what's up?"
    show shawn happy
    "Shawn chuckles and shakes his head at this."
    show shawn nice
    shawn.say "Honestly, [hero.name]..."
    shawn.say "There's nothing wrong, and I am happy to be here."
    show shawn smile
    bree.say "I sense a 'but' coming!"
    show shawn nice
    shawn.say "No, no, no..."
    shawn.say "I can just tell that I'm not as hyped as you seem to be, that's all."
    show shawn smile
    "I can feel myself starting to blush a little as Shawn says all of this."
    "Because I never stopped to look at how enthusiastic I can get before now."
    bree.say "Is..."
    bree.say "Is that not a good thing?"
    bree.say "Like, am I embarrassing you or something?"
    "All this gets me is another shake of the head from Shawn."
    show shawn nice
    shawn.say "Of course not, [hero.name]!"
    shawn.say "It's really cute that you're so enthusiastic."
    shawn.say "That's one of the things I like about you."
    show shawn smile
    "This is enough to mollify me a little."
    "But as it's a compliment, it only makes my blushing worse."
    bree.say "Oh..."
    bree.say "Oh, I see!"
    bree.say "That's good...that you think I'm cute!"
    "Urgh..."
    "I can already feel myself starting to babble."
    "So I make an effort to shut my mouth, before I embarrass myself even more."
    "Though I do make a point of reaching out and taking hold of Shawn's hand."
    "Already thinking of more ways that I could make him think I'm cute."
    return

label shawn_date_ferris_wheel_female:
    bree.say "Let's ride the Ferris Wheel next."
    bree.say "It's right over there, and the line's short too."
    "I start to walk in the direction of the Ferris Wheel."
    "And Shawn follows along with me, looking up at the ride."
    shawn.say "I can't remember the last time I rode one of these."
    shawn.say "It must have been years ago, maybe even decades!"
    "I nod as we join the back of the queue."
    bree.say "I know what you mean."
    bree.say "But I like to ride it when I'm here with someone new."
    bree.say "That way you can kind of make an old ride new again."
    "Shawn looks like he's about to toss off a response."
    "Maybe just shrug or say something non-committal."
    "But then what I just said seems to sink in."
    "And he ends up nodding his head in a thoughtful manner."
    shawn.say "You know what, [hero.name]..."
    shawn.say "I never thought of it that way."
    "I can't help grinning to myself as we step into the waiting gondola."
    "I know that Shawn likes to think he's smarter than the average guy."
    "So getting a compliment like that from him must really mean something."
    "We're both quiet as the safety-bar comes down and we rise into the air."
    "Instead of talking, I'm happy to take in the impressive view."
    "And it seems like the same thing is true of Shawn."
    "But when we finally reach the top of the wheel, the ride pauses."
    "Which is when I feel him tentatively moving his arm."
    "And just as hesitantly, he puts it around my shoulder."
    "At first I feel too nervous to move a muscle."
    "But as the seconds pass, I feel myself becoming more comfortable."
    "So much so that I feel like I can lean my head onto Shawn's shoulder."
    "And I stay in that same position for the rest of the ride."
    "Only moving from it once we have to get off again."
    "Sure, that might not have been the most passionate moment we just had together."
    "But I get the feeling that it was very real, and that it also meant something."
    $ shawn.love += 1
    $ game.active_date.score += 10
    return

label shawn_date_merry_go_round_female:
    shawn.say "Huh..."
    shawn.say "The Merry-Go-Round..."
    "I look around and see Shawn staring at the Merry-Go-Round."
    "And the thoughtful tone of his voice piques my interest."
    bree.say "What's that, Shawn?"
    bree.say "You want to ride it?"
    "Shawn shakes his head as he considers his answer."
    shawn.say "There was a reason I stopped riding these things, [hero.name]."
    shawn.say "But for the world, I can't remember what it was!"
    bree.say "Maybe you were just having too much fun?"
    bree.say "Whatever it was, it can't have been that serious."
    bree.say "Otherwise you'd have remembered it by now."
    "Shawn nods, apparently seeing the sense in what I just said."
    shawn.say "Maybe you're right."
    shawn.say "Let's ride it and see what happens."
    bree.say "That's more like it!"
    "Shawn and I hurry over to join the queue."
    "And as the ride isn't busy, we soon make it to the front."
    "We find a couple of spots that we like and settle in."
    "But even as the ride starts moving, Shawn still looks thoughtful."
    shawn.say "I just wish I could remember, [hero.name]..."
    shawn.say "What was it about these things?"
    shawn.say "What made me...."
    shawn.say "Whoa..."
    "I watch as Shawn's eyes start to lose focus."
    "And I swear that I can see the colour draining from his face too!"
    bree.say "Shawn?"
    bree.say "What is it?"
    bree.say "What's happening to you?"
    shawn.say "I..."
    shawn.say "I think I just..."
    shawn.say "Just remembered...what the...problem is!"
    "As the ride picks up speed, I don't need an explanation anymore."
    "I watch as Shawn's face turns from pale to a genuine shade of green."
    "His eyes roll back into his head, and he clings on for dear life."
    "Somehow he manages to hang on until the ride is over."
    "Then I follow him as he staggers to the nearest trashcan."
    "And I pat his back as he throws up into it."
    "Apparently what he'd forgotten was how Merry-Go-Rounds make him nauseous!"
    $ shawn.love -= 1
    $ game.active_date.score -= 10
    return

label shawn_date_haunted_house_female:
    shawn.say "Hmm..."
    shawn.say "Normally I'd be queuing up for the Haunted House over there."
    "I look in the direction that Shawn's pointing, and I see the ride in question."
    "But I can't help shaking my head, as I'm not sure why he's saying that."
    bree.say "What's different about today, Shawn?"
    bree.say "Why can't we go in there right now?"
    "I can see that the question leaves Shawn looking a little embarrassed."
    "And he seems to be struggling to explain himself to me."
    shawn.say "Well, you know..."
    shawn.say "Other times I've been here with guys."
    shawn.say "And you're a girl, aren't you?"
    bree.say "I was the last time I checked."
    bree.say "What's that got to do with anything?"
    "Shawn shrugs as I put him on the spot."
    "And he clearly can't just come out and say what he means."
    shawn.say "Well..."
    shawn.say "It's scary and stuff."
    shawn.say "Girls don't like that kind of thing!"
    "I feel the urge to burst out laughing at this."
    "That and to call Shawn out for being a sexist."
    "But then I realise that I could have a lot more fun with it instead."
    "So I take hold of his hand, and I march us over to the Haunted House."
    shawn.say "Wha..."
    shawn.say "What are you doing?!?"
    bree.say "I want to go in the Haunted House."
    bree.say "And it'll be okay, because I have a big, strong man to protect me."
    "Luckily for me, the queue is extremely short."
    "So there's no time for Shawn to object or come up with an excuse."
    "And once we're inside the Haunted House, he has to make good on his claims."
    "He has to put his money where his mouth is, standing bravely in front of me."
    shawn.say "Don't worry, [hero.name]..."
    shawn.say "Just stay right behind me."
    shawn.say "Do that, and everything will be fine."
    "That's how I end up following Shawn around the whole of the Haunted House."
    "And I get to watch him trying not to show a modicum of fear too."
    "Everything that jumps out at him seems to threaten that effort."
    "And by the time we make it to the exit, he's a frazzled mess."
    bree.say "Oh, thank you, Shawn!"
    bree.say "I could never have made it through there without you."
    "In his state of agitation, Shawn seems to miss the sarcasm of my tone."
    shawn.say "No worries, [hero.name]..."
    shawn.say "All part of the service."
    shawn.say "Now maybe we could try something a little more relaxing?"
    $ shawn.love += 2
    $ game.active_date.score += 20
    return

label shawn_date_love_boat_female:
    bree.say "You want to do something more relaxing next, Shawn?"
    bree.say "Maybe something romantic too?"
    "I nod towards the Love Boat as I'm saying all of this."
    "All in the hope that Shawn will latch onto what I'm saying."
    "And it doesn't take more than a second for him to give me a knowing smile."
    shawn.say "You know what, [hero.name]..."
    shawn.say "That really does look like a relaxing ride."
    shawn.say "I reckon that we should go check it out."
    "As I take hold of Shawn's hand, I breathe a sigh of relief."
    "Because I've dated some hot, but dumb guys in my time."
    "And sometimes it's a relief to be going out with a smart one!"
    "The Love Boat isn't the most exciting ride in the park."
    "So the queue for it is pretty short by the time we get there."
    "And this also means that we're soon climbing into the waiting boat."
    "I snuggle closer to Shawn as we sail off into the darkness."
    "And it doesn't take long for him to get the hint either."
    "As for what follows, well..."
    "Let's just say that it's as romantic as I hoped it would be."
    "Shawn and I take advantage of the chance to be affectionate."
    "But for the record, he remains a perfect gentlemen the whole time too."
    "Though I have to admit that I am feeling more than a little flustered at the end of the ride."
    $ shawn.love += 1
    $ game.active_date.score += 10
    return

label shawn_date_hedge_maze_female:
    shawn.say "Please don't make me go in there, [hero.name]..."
    shawn.say "Mazes have never really been my favourite thing."
    "I might have walked straight past the Hedge Maze if Shawn hadn't mentioned it."
    "But the moment he does, I can't get the idea of it out of my mind."
    "Maybe it's just the perverse side of my nature rearing it's head."
    "But as soon as he says he doesn't want to do it, I totally do!"
    bree.say "What?"
    bree.say "Are you kidding, Shawn?"
    bree.say "I love mazes, they're a total blast."
    bree.say "Am I not always saying how much I love them?"
    shawn.say "Erm..."
    shawn.say "No, [hero.name], you've never said anything like that to me."
    shawn.say "In fact I think this is the first time you ever mentioned them."
    "I can hear the words that are coming out of Shawn's mouth."
    "But by now I'm not really listening to them."
    "Instead I'm pulling him towards the entrance of the maze."
    "And the short queue means that we pretty much walk straight in there."
    "So within mere moments, we're inside the maze and wandering around."
    bree.say "Look at this place, Shawn..."
    bree.say "Isn't this great?"
    shawn.say "Not really, [hero.name]..."
    shawn.say "It's more confusing and kind of annoying."
    "I keep on doing all that I can to ignore Shawn."
    "And I persist in pulling him along the corridors inside the maze."
    "The longer I keep it up, the more annoyed he seems to become."
    "This persists until Shawn finally digs in his heels and stops me."
    shawn.say "Okay, [hero.name], okay..."
    shawn.say "New rule for the Amusement Park."
    shawn.say "From now on, we BOTH have to agree to a ride!"
    "All I can do is nod in agreement and slink off towards the exit."
    "Because I have to admit that he's right."
    "I probably did push it a little too far this time."
    $ shawn.love -= 1
    $ game.active_date.score -= 10
    return

label shawn_date_amusement_ice_cream_female:
    bree.say "Wow..."
    bree.say "It's so hot today!"
    "Shawn nods as soon as I speak those words."
    "Like he's relieved that someone else said it first."
    shawn.say "Oh god, [hero.name]..."
    shawn.say "It's too hot!"
    shawn.say "I feel like I'm going to die from sunstroke or something!"
    "Well, maybe he's being a little more melodramatic than I am."
    "But that doesn't mean I can't come up with a solution."
    bree.say "Hmm..."
    bree.say "What if we got some ice-cream?"
    bree.say "Would that help?"
    "The suggestion seems to do the trick."
    "As Shawn's mood instantly picks up."
    shawn.say "Great idea, [hero.name]!"
    shawn.say "Let's go get some."
    "Luckily the nearest ice-cream stand is pretty close by."
    "And so it's not too long before we have our ice-creams."
    "I start to lick at mine, but Shawn's still looking for something."
    shawn.say "Strawberry syrup, [hero.name]..."
    shawn.say "Can't have ice-cream without it!"
    "Shawn doesn't seem to be paying attention as he squeezes the bottle."
    "And the result is that a huge glob of the sticky, red liquid spatter across his shirt."
    bree.say "Ah, Shawn..."
    bree.say "You've got red on you!"
    shawn.say "Oh man..."
    shawn.say "This stuff never comes out!"
    $ shawn.love -= 1
    $ game.active_date.score -= 10
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
