label victor_date_amusement_park_female:
    scene bg amusement
    show victor
    with fade
    "I'm normally pretty excited to be going to the Amusement Park."
    "Ah, who the hell am I trying to kid?"
    "I'm totally hyped to be walking through the gates of the place!"
    "And even more when I'm getting to do it with a date for the first time."
    "But I have to admit that I was kind of worried about bringing Victor along."
    "I can't quite put my finger on exactly what's making me feel that way."
    "He just doesn't seem to give off an Amusement Park vibe, you know?"
    "That's why I keep on shooting him sly glances when he's not looking."
    show victor shout
    victor.say "Ah..."
    victor.say "Why'd you keep doing that?"
    show victor normal
    "Or at least I thought I was shooting him sly glances."
    "Looks like he's more observant than I gave him credit for."
    bree.say "Doing what, Victor?"
    show victor shout
    victor.say "Looking at me when you think I won't notice, of course!"
    victor.say "You've been doing ever since we got here."
    show victor normal
    "All I can do is shrug and hold my hands up."
    bree.say "Okay, Victor, you got me."
    bree.say "I'm just worried that you're not going to have a good time here."
    bree.say "That the Amusement Park isn't your kind of place."
    "Victor's face cracks into a smile as he hears what I have to say."
    "And you know the kind I mean - one of the really cute ones he does!"
    "But I can see that there's confusion in his eyes too."
    show victor angry
    victor.say "Ah..."
    victor.say "What's that supposed to mean?"
    victor.say "That I'm not into having fun?"
    show victor sad
    bree.say "No..."
    bree.say "Well, not exactly..."
    bree.say "What I mean is, you can be...kind of serious!"
    bree.say "Like, you dress in black and you're always furrowing your brow..."
    show victor upset
    "I can see Victor unconsciously reaching up to feel his brows."
    "But at the same time he's shaking his head at me."
    show victor shout
    victor.say "Ah..."
    show victor happy
    victor.say "You've got me all wrong, [hero.name]."
    victor.say "That's just when I'm in a serious mood."
    victor.say "I can do fun and games as well, you'll see!"
    show victor normal
    "I kind of wish that I'd never brought it up with Victor now."
    "And that I was better at hiding my worries from him."
    "But all the same, I nod and take hold of his hand."
    bree.say "Okay, Victor..."
    bree.say "Let's see how fun you really are to be around."
    return

label victor_date_ferris_wheel_female:
    victor.say "Ah..."
    victor.say "There's the Ferris Wheel, [hero.name]!"
    victor.say "We should, like, totally go on that."
    "We're already walking towards the ride in question."
    "And I have no objections to what Victor's suggesting."
    "So all I do is gently steer us towards the back of the line."
    bree.say "Are you sure, Victor?"
    bree.say "It's a pretty tame ride."
    bree.say "Don't you want some more excitement?"
    "Victor responds to this with a firm shake of the head."
    victor.say "No way, [hero.name]..."
    victor.say "I could use some relaxation in my life."
    "All I can do in response to that is shrug and let it go."
    "The queue for the Ferris Wheel is pretty short."
    "So it doesn't take long for us to reach the front."
    "Victor and I step into the waiting gondola."
    "Then the safety-bar comes down and we begin to rise into the air."
    "I have to admit that I'd forgotten just how hight this thing goes."
    "And I can't help looking around with a smile on my face."
    "Because the view just keeps on getting better the higher we go."
    "Victor's reaction is pretty much the same as mine."
    "I see him looking this way and that, trying to take it all in."
    bree.say "Pretty impressive, huh?"
    victor.say "Ah..."
    victor.say "You're not wrong, [hero.name]."
    victor.say "Strange to think..."
    victor.say "Things look so different up here."
    victor.say "That just a little more height can give you so much more perspective!"
    "I swear that I'm doing the best I can to listen to all that Victor is saying."
    "But the whole time my brain is struggling to ignore just how good he looks up here."
    "I'm seeing him in profile, his face outlined against the sun."
    "And at the same time, the wind is tousling his hair."
    "Not blowing it so that it's a mess, but tousling it so that he looks dramatic."
    "O...M...G..."
    "This guy is so hot!"
    victor.say "[hero.name]?"
    victor.say "Are you hearing me right now?"
    bree.say "Oh..."
    bree.say "Oh yeah...sorry!"
    "I feel myself blushing as we begin to return to the ground."
    "Ashamed of myself for thirsting over Victor like that."
    $ victor.love += 2
    $ game.active_date.score += 20
    return

label victor_date_merry_go_round_female:
    victor.say "Ah..."
    victor.say "That carousel looks really cool, [hero.name]..."
    victor.say "You think we could ride it?"
    "I take one glance at the Merry-Go-Round in front of us."
    "Noting the gilded poles and hand-painted wooden horses."
    "And then I look back at Victor, trying to square the circle."
    bree.say "You're sure that's the ride you want to go on next?"
    bree.say "I'm sure there's something like a roller-coaster around the corner."
    bree.say "Wouldn't you rather take a spin on that?"
    "Victor shakes his head, already walking over to the queue for the Merry-Go-Round."
    victor.say "No way, [hero.name]..."
    victor.say "These rides are classics, you know?"
    victor.say "Like, part of history in their own right."
    "I guess there's no arguing with the guy."
    "Victor wants to ride the Merry-Go-Round, and that's that."
    "Once I abandon all hope of changing Victor's mind, we join the queue."
    "Then we make small-talk until we're allowed onto the ride."
    "Victor hurries over to the horse that must have taken his fancy."
    "And not being so choosy, I just take the one next to him."
    "I keep looking over at Victor, expecting him to come to his senses."
    "To realise any moment that this is really a lame, boring ride."
    "But instead he still has a genuine smile on his face."
    "And it only seems to get wider as the ride starts to move."
    "When he starts shooting me glances in return, I can feel his enthusiasm."
    "In fact it's kind of contagious, making me start to smile too."
    "It doesn't take long for Victor to win me over."
    "Especially when he starts clowning, pretending to really ride his horse."
    "Somehow he manages to act in a cheesy manner, almost like a kid."
    "But he still makes me laugh, shaking my head at his efforts."
    "I'm still smiling when the ride comes to an end and we get off."
    "And I get the feeling he knows it too."
    "Though he's discreet enough to keep that to himself."
    $ victor.love += 2
    $ game.active_date.score += 20
    return

label victor_date_haunted_house_female:
    bree.say "Ooh..."
    bree.say "There's the Haunted House!"
    bree.say "We should totally go inside, Victor!"
    "I make a point of gesturing to the Haunted House as we walk towards it."
    "And Victor follows that with his eyes, looking it over with interest."
    victor.say "Ah..."
    victor.say "That place looks pretty sketchy, [hero.name]."
    victor.say "Reminds me of the places I've seen on contracts!"
    "I'm not sure what Victor can be talking about."
    "Maybe he's been doing freelance contract work."
    "And it's taken him to some of the rougher parts of town?"
    bree.say "Don't worry, Victor..."
    bree.say "It's just a spooky attraction, that's all!"
    "Victor seems convinced by my explanation."
    "And he doesn't resist as I pull him over to where the queue starts."
    "We're standing in line a little longer than I expected."
    "Probably because the Haunted House is a popular attraction."
    "But eventually we make it to the front of the line."
    "Victor hesitates before we walk into the Haunted House."
    "And he seems to unconsciously reach for something inside of his jacket."
    "But then he realises that, whatever it was, the mystery item isn't there."
    bree.say "Are you okay, Victor?"
    victor.say "Ah..."
    victor.say "Yeah, [hero.name]..."
    victor.say "I'm fine."
    "I give Victor a nod, and we walk inside."
    "Instantly I'm in my element, jumping, shrieking and laughing."
    "I'd almost forgotten how much fun being scared can be."
    "At least when you know that the danger isn't real."
    "But the same can't be said for Victor."
    "The dim lighting and shadows seem to make him paranoid."
    "And he responds to the jump-scares by leaping in front of me."
    "More than once I swear that he's actually going to punch something!"
    "This goes on the whole way round the Haunted House."
    "And I resist the urge to try and stop Victor."
    "Mainly because I don't want him to mistake me for some unseen danger."
    "Once we're out of there, he seems relieved."
    bree.say "Are you feeling okay, Victor?"
    bree.say "I thought you were freaking out in there!"
    victor.say "Ah..."
    victor.say "I'm okay, [hero.name]..."
    victor.say "It just reminded me of a job I did once."
    bree.say "Really?"
    bree.say "Must have been one tough gig!"
    victor.say "Believe me, you have no idea..."
    $ victor.love -= 2
    $ game.active_date.score -= 20
    return

label victor_date_love_boat_female:
    victor.say "Ah..."
    victor.say "'Love Boat'..."
    victor.say "What's that, [hero.name]?"
    "I'm kind of surprised that Victor doesn't know the answer to that question already."
    "After all, isn't the Love Boat a pretty common ride in an Amusement Park?"
    bree.say "It's a ride for couples, Victor."
    bree.say "You get in a little boat."
    bree.say "Then you ride through a dark tunnel together."
    victor.say "And what happens then?"
    victor.say "Do things jump out at you, like in the Haunted House?"
    victor.say "Or is it like the Roller Coaster, and you get shaken around?"
    "I can't help laughing at Victor's cluelessness."
    bree.say "Ha, ha..."
    bree.say "No, silly!"
    bree.say "It's supposed to be romantic."
    bree.say "You can get real close and have some fun."
    bree.say "You know what I mean?"
    "Victor nods at this, and I realise he's already pulling me towards the ride."
    "The line turns out to be pretty short, so it's not long before we're a the front."
    "By this time, Victor seems to have got a handle on his enthusiasm."
    "So when we step into the boat, it's a far more calm and civilised affair."
    "Victor looks kind of nervous as the boat sails into the semi-darkness."
    "Almost like he's wondering if he made a mistake in agreeing to this."
    "But once I slide over and lean against him, those misgivings seem to vanish."
    "What follows is a very enjoyable ride, punctuated with lots of memorable moments."
    "And by the time we come out the other end, we might look a little dishevelled."
    "But neither of us regrets it for a moment."
    $ victor.love += 2
    $ game.active_date.score += 20
    return

label victor_date_hedge_maze_female:
    bree.say "The Hedge Maze looks pretty quiet right now."
    bree.say "Let's go join the queue."
    "Victor's looking at the maze as I say all of this."
    "But to my surprise, he doesn't seem keen on the idea."
    victor.say "Ah..."
    victor.say "I don't know, [hero.name]..."
    victor.say "Mazes are kind of creepy, don't you think?"
    victor.say "All those dark corners for people to lurk around and stuff?"
    "I shake my head at Victor's response."
    "Because I'm having a hard time understanding his reservations."
    bree.say "What are you talking about?"
    bree.say "There's nobody lurking around the corners in there."
    bree.say "Just people trying to find the way out."
    "Victor still doesn't look convinced."
    "But he follows me to the back of the queue all the same."
    "And he doesn't stop looking worried the whole time."
    "He even looks concerned as we finally step into the maze."
    "I do the best I can to ignore it as I search for the exit."
    "But soon I find myself wanting to grab Victor by the neck and squeeze."
    "Because he keeps on jumping in front of me at every corner."
    "Then leaping around them, as if he's expecting us to be ambushed."
    "By the time we get to the exit, I'm totally frustrated with him."
    "So much so that I have to bite my lip and stride straight out of there."
    "Because otherwise I'm worried that I might end up saying something I'll regret."
    victor.say "Ah..."
    victor.say "[hero.name]..."
    victor.say "What's the problem?"
    victor.say "All I was trying to do was keep you safe!"
    $ victor.love -= 2
    $ game.active_date.score -= 20
    return

label victor_date_amusement_ice_cream_female:
    "I can see the ice-cream stand from where we are right now."
    "And I can see everyone walking away from it with one too."
    "In fact, I can practically taste them, even from a distance."
    "But I can't bring myself to ask Victor if he wants to grab one."
    "Because...well...he so serious!"
    "Part of me is sure that he'll give me one of those withering looks."
    "And that afterwards he won't respect me one iota."
    bree.say "Erm..."
    bree.say "Victor..."
    victor.say "Ah..."
    victor.say "Yeah, [hero.name]?"
    bree.say "Are you feeling, like...hot right now?"
    victor.say "I kind of am, yeah."
    victor.say "I was kind of wondering if..."
    victor.say "Ah..."
    victor.say "No, no...that's so dumb!"
    bree.say "No wait, Victor..."
    bree.say "What were you going to say?"
    victor.say "Ah..."
    victor.say "Maybe we could get ice-cream?"
    bree.say "What?"
    bree.say "Are you serious?"
    victor.say "I thought you'd think it was dumb!"
    bree.say "Get lost - I thought you would!"
    "And that's pretty much how the conversation goes all the way to the ice-cream stand."
    "Victor and I laughing about how dumb the pair of us are capable of being."
    "But as soon as we get our ice-creams, all the talking stops."
    "And instead we're both intently licking away."
    $ victor.love += 1
    $ game.active_date.score += 10
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
