label natalie_date_amusement_park_male:
    scene bg amusement
    show natalie normal
    with fade
    "I'm really looking forward to the chance of showing Natalie around the Amusement Park."
    "Because it's one of my favourite places to spend time, at least when I have any to spare!"
    "So this should be a great way for us to get to know each other a little better."
    "Not to mention having some genuine fun as well."
    "As we walk towards the gates, I take the chance to sneak a sideways glance at Natalie."
    "And I can see that she's gazing this way and that, taking it all in."
    mike.say "Are you looking forward to this, Natalie?"
    mike.say "I mean, you do like this kind of thing, right?"
    "Natalie turns her attention to me as I ask her the questions."
    "And she treats me to a pretty sweet smile as she does so."
    "But I note that she kind of shrugs her shoulders at the same time."
    natalie.say "I don't really know, [hero.name]!"
    natalie.say "The last time I came to a place like this was years ago."
    natalie.say "It was back when I was a little kid."
    "I'm kind of amazed to hear that."
    "Because I always assumed that everyone loved the Amusement Park."
    "But then I realise this could actually be a cleverly disguised opportunity."
    "If Natalie's an Amusement Park Virgin, then I can sell it to her."
    "I can make sure that she walks out of here today thinking it's the greatest place on earth."
    "And at the same time she'll come to associate all that good stuff with me too!"
    mike.say "Trust me, Natalie..."
    mike.say "You've been missing out."
    mike.say "And I just know that you're going to love it!"
    natalie.say "I hope so, [hero.name]…"
    natalie.say "Because it does look like a lot of fun!"
    return

label natalie_date_ferris_wheel_male:
    natalie.say "Oh wow..."
    natalie.say "I never thought they'd have one of those!"
    "I follow Natalie's gaze, expecting to see something new and impressive."
    "You know, like a roller-coaster or virtual reality ride."
    "So it comes as a surprise to see that she's looking at the Ferris Wheel."
    mike.say "What's the big deal, Natalie?"
    mike.say "It's just a Ferris Wheel."
    "Natalie shakes her head at my dismissive comments."
    natalie.say "The big deal is that I never got to ride one before."
    natalie.say "I was too young the last time I came to a place like this."
    natalie.say "Like, I was under the minimum height."
    "I take hold of Natalie's hand and start walking towards the Ferris Wheel."
    "She resists a little, obviously not realising what I'm doing."
    natalie.say "Whoa..."
    natalie.say "Slow down a little!"
    mike.say "Why?"
    mike.say "You've grown since then, right?"
    natalie.say "Yeah..."
    natalie.say "But so what?"
    mike.say "So you're tall enough to ride it now."
    "Now that she gets what I'm doing, Natalie stops resisting."
    "And she nods eagerly as we join the back of the queue."
    "It doesn't take us long to get on the ride."
    "And as we start to rise up into the air, Natalie looks pretty excited."
    "She's looking over the edge of the gondola and then around at the view."
    "Almost like she can't decide where to look for fear of missing something."
    "But the biggest thrill she gets seems to come when the ride stops us at the top."
    "Then she just stares at the view in a genuinely stunned silence."
    "On the way back down, I don't need to ask Natalie what she thinks."
    "Because the smile on her face is plain to see."
    return

label natalie_date_merry_go_round_male:
    mike.say "There's the Merry-Go-Round, Natalie..."
    mike.say "We should really take a ride on that."
    "Much to my surprise, Natalie doesn't seem enthusiastic."
    "And she drags her heels as we walk towards the ride in question."
    natalie.say "Do we have to, [hero.name]?"
    natalie.say "It looks a little childish to me."
    mike.say "But that's the entire point!"
    mike.say "This a chance for you to experience all of this stuff."
    mike.say "All the things you never got to do as a kid!"
    "Natalie lets out a sigh and follows me to the back of the line."
    natalie.say "If you say so..."
    "The Merry-Go-Round isn't exactly a popular ride."
    "Which means that the queue is short and moves pretty fast."
    "So we're soon climbing onto it and picking a place to sit."
    "Then we hold on as the ride starts moving."
    "Soon it picks up speed, and we're going a fair pace."
    "But when I look round at Natalie, she doesn't seem to be enjoying herself."
    "In fact she looks more like she's enduring the ride and wishing it would end."
    "Once we're off the Merry-Go-Round, Natalie shakes her head at me."
    natalie.say "Just for the record, [hero.name]..."
    natalie.say "Not all the rides I missed out on as a kid are worth trying."
    natalie.say "Because some of them are like that one - boring as hell!"
    return

label natalie_date_haunted_house_male:
    natalie.say "Oh my..."
    natalie.say "What is that noise?"
    "At first I'm not sure what Natalie's talking about."
    "The Amusement Park is kind of a noisy place."
    "And most of what I can hear sounds pretty standard too."
    mike.say "What do you mean, Natalie?"
    mike.say "I don't hear anything out of the ordinary."
    natalie.say "You have to be kidding!"
    natalie.say "You don't hear those screams?"
    natalie.say "How about the moaning?"
    natalie.say "And someone laughing like lunatic?!?"
    "Suddenly it dawns on me just what Natalie can hear."
    mike.say "Oh, right..."
    mike.say "That's just the Haunted House over there."
    natalie.say "It is?!?"
    natalie.say "How is that supposed to be fun?"
    "I wave for Natalie to follow me as I walk over to join the queue."
    mike.say "Trust me, Natalie..."
    mike.say "This is like one of the best rides in the park."
    mike.say "It's practically a rite of passage!"
    "Natalie looks interested in what I'm saying."
    "And she doesn't hesitate to join the queue as well."
    "I'm feeling confident that she'll love it."
    "Right up until the moment we get inside."
    "Which is when she freaks out at the very first scare."
    "After that she spends the entire time in the Haunted House in terror."
    "Cowering behind me and screaming at anything that moves."
    "Once we're outside, Natalie's still shaking."
    "And I make a mental note not to just assume she'll like a ride because I do the next time."
    return

label natalie_date_love_boat_male:
    natalie.say "The Love Boat!"
    natalie.say "They have one of those here?!?"
    "I look over at the Love Boat, not really getting what all the fuss is about."
    mike.say "Yeah, Natalie..."
    mike.say "They have a Love Boat."
    mike.say "Most Amusement Parks do."
    "Natalie's already dragging me over to the line for the ride as I say all of this."
    "And the next thing I know, she's shoving me into the queue!"
    natalie.say "I always wanted to go on one of these."
    mike.say "Why is that?"
    mike.say "It's just a boat in a dark tunnel!"
    natalie.say "I mean I always wanted to go on it with the right guy!"
    "Natalie gives me a serious look as she says this."
    "And what she means finally starts to dawn on me."
    "How could I be so stupid?"
    mike.say "Oh..."
    mike.say "Oh yeah..."
    mike.say "I see what you mean!"
    "Natalie rolls her eyes at this."
    "But she wraps her arm in mine and leans in closer all the same."
    natalie.say "Oh, [hero.name]..."
    natalie.say "You can be so dumb sometimes!"
    "When our turn comes round, we step into one of the boats."
    "Then we sail off together into the darkness of the tunnel."
    "It doesn't take Natalie long to get into the swing of things."
    "And I find out every single thing she's always wanted to do on the ride."
    "Even a couple of things that leave me totally amazed too!"
    return

label natalie_date_hedge_maze_male:
    natalie.say "Hedge Maze?"
    natalie.say "So that's what..."
    natalie.say "A maze made out of hedges?"
    "I can clearly hear how unimpressed Natalie seems to be with the concept."
    "So I feel like I have to do all that I can to big it up in front of her."
    "I have no idea why, other than the fact I'm trying to sell her on the park in general."
    mike.say "It's way more fun than it sounds, Natalie."
    mike.say "Why don't we go inside and I'll show you?"
    "Natalie shrugs and follows me over to the back of the queue."
    "And as the ride is quite quiet, we're soon at the front of it."
    "Once we're inside, I do the best I can to make the experience exciting."
    "Leading Natalie down one corridor and around the next bend."
    "All the time telling her to keep a handle on where we've been."
    "It doesn't help matters that I soon find myself totally lost."
    "And in order to find the way out, I have to ask for her help."
    "Natalie obliges, locating the exit with surprising speed."
    "And she's also kind enough not to rub it in afterwards too."
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
