label danny_date_amusement_park_female:
    scene bg amusement
    show danny annoyed
    with fade
    "I always love going to the Amusement Park, and I take the chance to go whenever it comes up."
    "In fact I love it so much that I can't imagine anyone else not wanting to be there either."
    "Which is why I can't understand why Danny's hanging back as we walk towards the gates."
    "Or why he seems to be walking along with his hands in his pockets and muttering to himself."
    bree.say "What's the problem, Danny?"
    bree.say "Aren't you looking forward to this?"
    "Danny looks to the left and the to the right, still muttering under his breath."
    "And then he finally looks me in the eye, curling his lip as he does so."
    show danny shout
    danny.say "No I am not, [hero.name]!"
    danny.say "Why'd you have to bring me to a place like this?"
    show danny annoyed
    "I can't help taking a step back and frowning at him."
    "I mean, what kind of a question is that?"
    bree.say "This is the Amusement Park, Danny..."
    bree.say "The idea is to come here and have some serious fun!"
    "Danny rolls his eyes and looks away again."
    danny.say "Mmm...nnn...mmm..."
    "I can't tell what he's saying, because he's started muttering again."
    "But I can certainly tell from the tone of his voice that it's not complimentary."
    bree.say "What was that, Danny?"
    bree.say "What are you saying?"
    show danny shout
    danny.say "I said - it doesn't look like fun to me!"
    show danny annoyed
    bree.say "Oh come on, Danny!"
    bree.say "You haven't even given it a chance."
    "I make a point of changing my tone as I try to convince Danny to change his tune."
    "Because unlike some guys, with him, flattery will usually get you pretty damn far."
    bree.say "Anyway, I did invite you here for another reason."
    show danny surprised
    danny.say "You did?"
    danny.say "What's that, [hero.name]?"
    bree.say "Well, I can really see you in a place like this."
    "Suddenly Danny looks intrigued, like he wants to hear my reasoning."
    danny.say "Why, [hero.name]?"
    danny.say "Because I'm slick and exciting, like the rides?"
    danny.say "That's the reason, yeah?"
    bree.say "No, Danny..."
    bree.say "It's because you remind me of the sleazy guys running the sideshows!"
    show danny angry
    danny.say "HEY!"
    show danny upset
    "With that, I turn and dash through the gates of the Amusement Park."
    "And Danny chases me right in there, the insult I just gave him still stinging."
    "But at least I managed to get him into the place."
    "That has to count for something, right?"
    return

label danny_date_ferris_wheel_female:
    bree.say "Let's ride the Ferris Wheel next."
    bree.say "The queue's really short right now."
    "Danny kicks his heels and rolls his eyes at the suggestion."
    "Making it pretty obvious that he's not enthusiastic."
    danny.say "Nah..."
    danny.say "That looks lame."
    bree.say "Well I'm going to go on it, with or without you."
    bree.say "So you'd better find something to do with yourself while I'm on it."
    "I turn and walk over to the back of the line."
    "And the I shoot Danny a defiant look."
    "He does the best he can to ignore me."
    "Even turning his back to me for a few moments."
    "But eventually he cracks, doing a weird little dance out of sheer frustration."
    "Then I see him walking towards me, looking more than a little annoyed."
    danny.say "Okay, okay..."
    danny.say "I'll go on the stupid ride with you."
    danny.say "But only because it's less boring that waiting on my own!"
    "I do the best I can to rub it in, smiling up at Danny."
    "I even wrap myself around his arm and lean my head on his shoulder."
    bree.say "Oh, Danny..."
    bree.say "You really know how to make a girl feel special!"
    "Danny keeps on sulking as we make our way to the front of the queue."
    "And he slinks into the gondola, crossing his arms in a huff."
    "But that doesn't bother me, as I focus my attention on the view instead."
    "As we rise into the air, it gets ever more impressive."
    "Until the wheel stops with us at the top, and I can literally see for miles."
    bree.say "Wow!"
    bree.say "You have to check this out, Danny!"
    danny.say "So we're up high..."
    danny.say "So what?"
    "I shake my head and resign myself to ignoring Danny."
    "Which is made easier by the fact he keeps quiet for the rest of the ride."
    "Soon enough we come back down and it's time to get off."
    "But I feel a small sense of triumph in having made him come along with me."
    $ danny.love += 0
    $ game.active_date.score += 0
    return

label danny_date_merry_go_round_female:
    bree.say "What about the Merry-Go-Round, Danny?"
    bree.say "I suppose that's too childish for you, yeah?"
    bree.say "That you think it's just for little kids?"
    "When Danny doesn't say anything, I just assume he's ignoring me."
    "That or he's gone back to muttering under his breath."
    "But when I turn to look in his direction, I see him staring at the Merry-Go-Round."
    danny.say "Hey..."
    danny.say "Those horses look neat!"
    bree.say "Are you serious?"
    bree.say "You actually want to ride the Merry-Go-Round?"
    "Danny looks at me like I'm talking nonsense."
    danny.say "Why not, [hero.name]?"
    danny.say "I always loved cowboys when I was a kid."
    danny.say "And I never got to ride a real horse in my life."
    bree.say "You won't now."
    bree.say "Those aren't real!"
    "Danny doesn't seem to hear what I'm saying."
    "Because he grabs hold of my hand, pulling me towards the ride."
    "I don't resist, figuring that I should probably just go with it."
    "So it looks like we're riding the Merry-Go-Round."
    "After a short wait in the queue, we're let onto the ride."
    "Danny picks a horse he likes the look of and climbs onto it."
    "Then he makes a point of jiggling around in the seat and slapping it with his hand."
    danny.say "Yee-hah!"
    danny.say "Look at me, [hero.name]..."
    danny.say "I'm a regular cowboy!"
    "Of course he looks like a complete idiot."
    "But before I can tell him that, the ride begins to move."
    "Danny's not ready for it, and he's thrown forwards."
    "Instinctively he clutches onto the horse and hold on for dear life."
    danny.say "Whoa..."
    danny.say "This thing goes fast!"
    danny.say "Everything's spinning!"
    "I watch as the ride picks up speed and Danny begins to look worse."
    "Before too long he seems to be turning an unhealthy shade of green."
    "By some miracle, he manages to hold on until the ride slows back down."
    "But as soon as it stops, he slides off and staggers away from it."
    "Then I watch as he finds the nearest garbage can and heaves up into it."
    "Some cowboy he turned out to be!"
    $ danny.love -= 2
    $ game.active_date.score -= 20
    return

label danny_date_haunted_house_female:
    bree.say "Come on, Danny..."
    bree.say "I want to go in the Haunted House next."
    "Danny allows himself to be pulled towards the Haunted House."
    "But at the same time I can feel him leaning back to take it all in."
    danny.say "Are you sure, [hero.name]?"
    danny.say "It looks a little cheesy to me."
    danny.say "Kind of like a bad Halloween party!"
    bree.say "Of course I'm sure."
    bree.say "And it's scary, not cheesy!"
    "Danny shakes his head as we stand in line."
    "Like he's not really sold on the whole idea."
    danny.say "Whatever you say, [hero.name]..."
    danny.say "But I swear I've lived in places scarier than this!"
    "Once we get to the front of the line, I steel my nerves for what lies ahead."
    "But all Danny does is shrug his shoulders as we step in through the entrance."
    "Even with all of the effort I've put into it, I still jump at the first scare."
    "My scream is pretty impressive, even if I do say so myself."
    "But when the puppet pops up in front of us, Danny doesn't hesitate."
    "He swings a punch at the thing, taking it's head clean off!"
    danny.say "Ha!"
    danny.say "There you go, [hero.name]..."
    danny.say "I took care of that asshole for you!"
    danny.say "Wha...what are you looking at me like that for?"
    bree.say "Danny, you can't do that!"
    bree.say "You can't punch the ghosts or knife the ghouls!"
    "Suddenly Danny looks more than a little bashful."
    danny.say "I can't?"
    danny.say "Oops..."
    "I look around, trying to see if there were any witnesses."
    "But to my relief, it seems that nobody else saw what just happened."
    "I take hold of Danny's hand and lead him around the rest of the Haunted House."
    "He shuffles after me, still hanging his head in shame."
    "Which means that he doesn't see the other things that leap out at us."
    "And it's probably safer that way."
    $ danny.love += 0
    $ game.active_date.score += 0
    return

label danny_date_love_boat_female:
    danny.say "Hmm..."
    danny.say "The Love Boat, huh?"
    danny.say "Now that sounds more like it!"
    "Normally I'd be more than a little inclined to groan at Danny's reaction."
    "But I was the one that insisted he come to the Amusement Park with me."
    "So it seems stupid to do anything but encourage him."
    bree.say "You want to ride the Love Boat, Danny?"
    bree.say "Then we should go join the queue."
    bree.say "Come on, before it gets any longer."
    "Danny looks at me with confusion written all over his face."
    danny.say "Wha..."
    danny.say "What are you saying, [hero.name]?"
    danny.say "That you want to go on it?"
    "I guess Danny was expecting me to call him a creep and refuse to go on the ride with him."
    "So my taking him up on the offer without any need to be convinced seems to have thrown him."
    bree.say "Yes, Danny..."
    bree.say "Exactly that."
    bree.say "Come on now!"
    "Danny hurries to follow me as I join the queue."
    "And it's clear from the look on his face that he's expecting this to be a joke."
    "That any moment I'm going to tell him to get lost and laugh in his face."
    "And he's still looking like that when we actually get into one of the boats."
    "In fact he only begins to loosen up when I lean against him and rest my head on his shoulder."
    "But as we sail into the gloom of the tunnel, Danny finally realises that I'm serious."
    "And from that point on, the voyage into the privacy of the tunnel becomes well worth it."
    "Even better, nobody else can see what we get up to either."
    $ danny.love += 2
    $ game.active_date.score += 20
    return

label danny_date_hedge_maze_female:
    bree.say "Let's try the Hedge Maze, Danny..."
    bree.say "That should be something you're good at."
    "Danny shoots me a suspicious look."
    "And he also narrows his eyes for good measure."
    danny.say "Hey!"
    danny.say "What's that supposed to mean?"
    "I shrug and smile as we join the line for the maze."
    "Enjoying the chance to make a joke at his expense."
    bree.say "Oh, nothing..."
    bree.say "Just that I figured you'd be good at escaping from things!"
    danny.say "Ha, ha..."
    danny.say "Very funny, [hero.name]..."
    danny.say "Make fun of my troubled past, why don't you?"
    bree.say "Isn't that what I just did?"
    danny.say "Ah, don't be a smart-ass as well!"
    "We keep on squabbling lightly until we make it to the front of the queue."
    "But once we're inside the maze, Danny looks around and shakes his head."
    danny.say "So?"
    bree.say "So what?"
    danny.say "So what happens now?"
    bree.say "We find the way out of course!"
    danny.say "You mean that's it?"
    danny.say "The whole point is just to get lost and then find your way again?"
    bree.say "It's a maze, dumbass..."
    bree.say "That is the whole point!"
    "I shake my head and walk off, beginning to explore the maze."
    "Danny hurries after me, still complaining about how lame he thinks it all is."
    "And he doesn't stop until after we've walked out of the exit either."
    "All of which makes me wish I could have found a way to lose him in there."
    $ danny.love += 1
    $ game.active_date.score += 10
    return

label danny_date_amusement_ice_cream_female:
    bree.say "Ooh..."
    bree.say "We should get ice-cream!"
    bree.say "It's been an age since I had one."
    "Danny nod his head and gives me one of his best smiles."
    "The kind that make him look like a pirate intent on plunder."
    danny.say "Yeah, [hero.name]..."
    danny.say "That sounds like a great idea."
    "I'm fully expecting him to follow that up by telling me what he wants."
    "You know, with him being pretty cheap and a dodgy character at the best of times."
    "But instead Danny surprises me by walking straight over to the ice-cream stand."
    danny.say "Don't worry, [hero.name]..."
    danny.say "I got this!"
    bree.say "But, Danny..."
    bree.say "You don't even know what I want!"
    "Danny just waves a hand vaguely in the air as I say this."
    "Which I take to mean that he's sure he knows my taste in ice-cream."
    "And when he returns a few moments later, I'm not disappointed."
    "Because he hands me a massive cone, piled high with ice-cream."
    bree.say "WOW!"
    bree.say "This is amazing, Danny!"
    bree.say "How did you afford all of this?"
    "Danny starts to push me along even before I take my first lick."
    "Almost like we have somewhere to be and need to get there fast."
    danny.say "Ah, yeah..."
    danny.say "I'm just feeling generous, [hero.name]!"
    danny.say "Now I need you to lick and walk at the same time, okay?"
    "I nod as I start to dig into my ice-cream."
    "And it's probably a good thing Danny wants us to move too."
    "As I can hear some kind of commotion starting up at the ice-cream stand."
    "It's hard to make out, but it sounds like someone's being accused of stealing."
    "So I'm just glad to be walking quickly in the opposite direction right now!"
    $ danny.love += 1
    $ game.active_date.score += 10
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
