label lexi_date_amusement_park_male:
    scene bg amusement
    show lexi b normal
    with fade
    lexi.say "Come on, [hero.name]…"
    lexi.say "What are you waiting for?"
    lexi.say "A written fucking invitation?!?"
    show lexi b lollipop
    "Normally it would be me sprinting ahead to the entrance of the Amusement Park."
    "All the while trying to drag my date along behind me, despite their attempts to resist."
    "But this is the first time that I've found myself in the reverse of that scenario."
    mike.say "Hey!"
    mike.say "Wait up, Lexi..."
    mike.say "I'm coming as fast as I can!"
    "Putting on a final burst of speed, I manage to catch up to Lexi just as she reaches the gates."
    "So I at least have the comfort of knowing that she didn't manage to beat me there."
    show lexi a normal
    lexi.say "You'd better move faster than that once we're in there!"
    lexi.say "Because I'm not missing out on all the rides I want to do while I wait for you."
    show lexi a lollipop
    mike.say "Urgh..."
    mike.say "Geez, Lexi..."
    mike.say "It's literally hours until the park closes."
    mike.say "We've got all the time in the world before then."
    show lexi a annoyed
    "Lexi shakes her head at this."
    show lexi a bored
    lexi.say "Uh-uh..."
    show lexi a normal
    lexi.say "We need to factor in queuing times."
    lexi.say "Then there's toilet breaks."
    lexi.say "And stopping for regular snacks - I need to keep my energy levels up!"
    show lexi a blank
    mike.say "I'm sure we'll be fine, Lexi..."
    mike.say "Now can we actually get in there?"
    show lexi b smile nophone
    "Lexi nods and grabs hold of my hand."
    "Then I find myself being dragged through the gate and into the crowds beyond."
    return

label lexi_date_ferris_wheel_male:
    mike.say "The Ferris Wheel is pretty quiet, Lexi..."
    mike.say "I bet we could be on that thing in no time at all."
    "Lexi looks over at the Ferris Wheel and then at the queue."
    lexi.say "Normally I'd say no way - that's a ride for old farts!"
    lexi.say "But I want to cram as much in as possible."
    lexi.say "So let's do it!"
    "With that, Lexi makes straight for the queue."
    "I follow on her heels and we join the back of the line."
    "It doesn't take long for me to be proven right too."
    "Not only is the line short, it moves fast as well."
    "Before we know it, we're being ushered into one of the gondolas."
    "Even so, Lexi fidgets in her seat as the safety-bar comes down."
    lexi.say "Come on, come on..."
    lexi.say "What's taking so long?"
    "Her movements are making the gondola sway back and forth."
    "And even when we start to ascend, Lexi doesn't stop for a second."
    lexi.say "Oh yeah..."
    lexi.say "Here we go..."
    lexi.say "This is more like it!"
    "I do the best I can to ignore how we're lurching around."
    "And instead I focus all of my attention on the view around me."
    "Of course that just keeps getting better and better the higher we go."
    "So by the time we reach the top and the ride stops, it's totally amazing."
    mike.say "Will you look at that, Lexi..."
    mike.say "You must be able to see for miles and miles up here!"
    "At last this seems to be enough to distract Lexi."
    "And the gondola stops rocking as she turns her attention to the view."
    lexi.say "Erm..."
    lexi.say "Yeah..."
    lexi.say "That's high..."
    "Without warning, Lexi clings onto the safety-bar."
    "She turns a worrying shade of white, her eyes bulging in their sockets."
    "And I can see that she's now staring at the bottom of the gondola."
    mike.say "Shit..."
    mike.say "Lexi, are you okay?"
    lexi.say "I want to get off this thing!"
    lexi.say "I need to be back on the ground!"
    "I had no idea that Lexi suffered from Vertigo, but I know the symptoms."
    "So I do all that I can to calm her down as the ride starts moving again."
    "And once we're off, I sit her down until the symptoms pass."
    $ lexi.love -= 2
    $ game.active_date.score -= 20
    return

label lexi_date_merry_go_round_male:
    mike.say "How about we ride the Merry-Go-Round next, Lexi?"
    mike.say "I'm sure we can squeeze a quick one in between the other rides."
    "As soon as the words are out of my mouth, I realise what I actually said."
    "And so it comes as no surprise that Lexi bursts into peals of filthy laughter."
    lexi.say "Oh yeah?"
    lexi.say "You want to use the back-passage for that, [hero.name]?"
    lexi.say "Maybe deliver some sausage while you're back there?"
    "I do the best I can to keep things at least semi-serious."
    "Which seems to be simply ignoring Lexi and asking the question again."
    mike.say "Very funny, Lexi..."
    mike.say "But what about it?"
    mike.say "You want to ride the Merry-Go-Round or not?"
    lexi.say "What the hell..."
    lexi.say "Let's ride the thing."
    "With that decided, Lexi and I walk over to where the queue starts."
    "Thanks to this being an older and more sedate ride, it's not too long."
    "And we soon make our way to the front, climbing onto the Merry-Go-Round."
    "Lexi still has a knowing smile on her face as we choose where we're going to sit."
    "So it looks like she's going to be smirking at me for the length of the ride."
    "But as the thing starts to speed up, I notice a change in her mood."
    "Slowly she starts to cling on more tightly, noticing the speed of the ride."
    "And before too long she's rocking back and forth with the motion of it too."
    mike.say "Lexi..."
    mike.say "Are you okay?"
    lexi.say "Whoa..."
    lexi.say "I feel so fucking dizzy right now!"
    mike.say "Is that good or bad?"
    mike.say "If it's bad, I can make them stop the ride, okay?"
    lexi.say "No, no..."
    lexi.say "It's good!"
    "Lexi whoops and screams her way through the rest of the ride."
    "And even when she gets off she seems to be staggering as she walks."
    "But she looks like she's enjoying the sensation."
    "So I decide to leave it well enough alone."
    $ lexi.love += 2
    $ game.active_date.score += 20
    return

label lexi_date_haunted_house_male:
    mike.say "There's the Haunted House, Lexi..."
    mike.say "I always try to go in there."
    mike.say "It's my favourite thing at the park!"
    "Lexi gives me a shrug as we walk over to the Haunted House."
    lexi.say "Huh!"
    lexi.say "I never really gave a toss either way."
    lexi.say "But if you like it that much, we should probably go on there."
    "Even a half-hearted answer like that is good enough for me."
    "And so I lead the way to the back of the line for the Haunted House."
    "Lexi and I chat about everything and nothing as we work our way up the queue."
    "So it comes as a surprise when we're the next in line to enter."
    "As soon as we're in there, I feel myself getting lost in the experience."
    "I love every twist and turn in the place, every jump-scare and pop-up surprise."
    "But Lexi doesn't seem to have the same reaction as me."
    "Sure, she's not complaining about it or asking when we're going to get out."
    "Yet I can tell that she's not exactly enjoying herself either."
    "Which kind of brings the whole thing down for me a little too."
    "Once we're out of the Haunted House, I think about bringing it up."
    "But as it would probably only spark an argument, I decide to leave it alone."
    "That and not to take Lexi into the Haunted House with me the next time."
    return

label lexi_date_love_boat_male:
    lexi.say "The Love Boat?"
    lexi.say "Wasn't that a crappy TV show from like the stone age or something?"
    lexi.say "How come they made a ride out of it?"
    "I shrug and shake my head."
    mike.say "I never heard of that show, Lexi."
    mike.say "But the ride can be pretty fun."
    mike.say "You know, depending on who you ride it with?"
    "I add a nod and a wink, just to be sure Lexi understands me."
    "And that seems to do the trick."
    lexi.say "Oh yeah?"
    mike.say "Yeah!"
    lexi.say "Well now we have to ride it!"
    "Lexi wastes no time in grabbing me by the hand."
    "Then she leads me over to where the queue begins."
    "We don't have to wait in line long before we reach the front."
    "But Lexi seems less than impressed when she sees the actual boat."
    lexi.say "That's it?"
    lexi.say "Like, a crappy little wooden boat?!?"
    mike.say "It gets better, Lexi..."
    mike.say "Just trust me, okay?"
    "Lexi doesn't look convinced."
    "But she gets into the boat anyway."
    "And then we sail off into the gloomy tunnel."
    lexi.say "So what happens next?"
    lexi.say "Is it like a roller-coaster?"
    lexi.say "Or a ghost train?"
    mike.say "Erm..."
    mike.say "No, Lexi..."
    mike.say "We're just supposed to make out in here."
    lexi.say "What?!?"
    lexi.say "We could do that outside!"
    mike.say "Yeah, I know..."
    mike.say "But in here nobody can see us."
    lexi.say "Who cares if anyone sees us?!?"
    lexi.say "Fuck sake, [hero.name] - this is totally pointless and SO boring!"
    $ lexi.love -= 4
    $ game.active_date.score -= 30
    return

label lexi_date_hedge_maze_male:
    lexi.say "Hedge Maze?"
    lexi.say "How dumb does that sound!"
    lexi.say "Who wants to get lost on purpose?"
    "I hardly hear Lexi's withering comments on the Hedge Maze."
    "Because I'm more interested in the fact the queue is so short."
    "We could be in there far faster than with the other rides around it."
    mike.say "I dunno, Lexi..."
    mike.say "It could be fun."
    mike.say "Figuring a way to escape - kind of like one of those escape rooms."
    "Lexi shakes her head at this."
    "But she still follows me as I walk over to join the queue."
    "And I'm soon proven right as it takes almost no time to get to the front."
    "As soon as we get inside, I do all I can to prove myself right a second time."
    "Though it soon becomes apparent that my efforts are having no effect on Lexi."
    "She puffs, moans and complains the entire way around the maze."
    "Telling me off for not getting us out of there quickly enough."
    "While at the same time doing nothing to help find the exit."
    "And once we're out, I turn my back on the maze and vow never to return."
    "At least not while I'm here with Lexi."
    $ lexi.love -= 2
    $ game.active_date.score -= 10
    return

label lexi_date_amusement_park_female:
    scene bg amusement
    show lexi b normal
    with fade
    lexi.say "Come on, [hero.name]…"
    lexi.say "What are you waiting for?"
    lexi.say "A written fucking invitation?!?"
    show lexi b lollipop
    "Normally it would be me sprinting ahead to the entrance of the Amusement Park."
    "All the while trying to drag my date along behind me, despite their attempts to resist."
    "But this is the first time that I've found myself in the reverse of that scenario."
    bree.say "Hey!"
    bree.say "Wait up, Lexi..."
    bree.say "I'm coming as fast as I can!"
    "Putting on a final burst of speed, I manage to catch up to Lexi just as she reaches the gates."
    "So I at least have the comfort of knowing that she didn't manage to beat me there."
    show lexi a normal
    lexi.say "You'd better move faster than that once we're in there!"
    lexi.say "Because I'm not missing out on all the rides I want to do while I wait for you."
    show lexi a lollipop
    bree.say "Urgh..."
    bree.say "Geez, Lexi..."
    bree.say "It's literally hours until the park closes."
    bree.say "We've got all the time in the world before then."
    show lexi a annoyed
    "Lexi shakes her head at this."
    show lexi a bored
    lexi.say "Uh-uh..."
    lexi.say "We need to factor in queuing times."
    lexi.say "Then there's toilet breaks."
    lexi.say "And stopping for regular snacks - I need to keep my energy levels up!"
    show lexi a blank
    bree.say "I'm sure we'll be fine, Lexi..."
    bree.say "Now can we actually get in there?"
    show lexi b smile nophone
    "Lexi nods and grabs hold of my hand."
    "Then I find myself being dragged through the gate and into the crowds beyond."
    return

label lexi_date_ferris_wheel_female:
    bree.say "The Ferris Wheel is pretty quiet, Lexi..."
    bree.say "I bet we could be on that thing in no time at all."
    "Lexi looks over at the Ferris Wheel and then at the queue."
    lexi.say "Normally I'd say no way - that's a ride for old farts!"
    lexi.say "But I want to cram as much in as possible."
    lexi.say "So let's do it!"
    "With that, Lexi makes straight for the queue."
    "I follow on her heels and we join the back of the line."
    "It doesn't take long for me to be proven right too."
    "Not only is the line short, it moves fast as well."
    "Before we know it, we're being ushered into one of the gondolas."
    "Even so, Lexi fidgets in her seat as the safety-bar comes down."
    lexi.say "Come on, come on..."
    lexi.say "What's taking so long?"
    "Her movements are making the gondola sway back and forth."
    "And even when we start to ascend, Lexi doesn't stop for a second."
    lexi.say "Oh yeah..."
    lexi.say "Here we go..."
    lexi.say "This is more like it!"
    "I do the best I can to ignore how we're lurching around."
    "And instead I focus all of my attention on the view around me."
    "Of course that just keeps getting better and better the higher we go."
    "So by the time we reach the top and the ride stops, it's totally amazing."
    bree.say "Will you look at that, Lexi..."
    bree.say "You must be able to see for miles and miles up here!"
    "At last this seems to be enough to distract Lexi."
    "And the gondola stops rocking as she turns her attention to the view."
    lexi.say "Erm..."
    lexi.say "Yeah..."
    lexi.say "That's high..."
    "Without warning, Lexi clings onto the safety-bar."
    "She turns a worrying shade of white, her eyes bulging in their sockets."
    "And I can see that she's now staring at the bottom of the gondola."
    bree.say "Shit..."
    bree.say "Lexi, are you okay?"
    lexi.say "I want to get off this thing!"
    lexi.say "I need to be back on the ground!"
    "I had no idea that Lexi suffered from Vertigo, but I know the symptoms."
    "So I do all that I can to calm her down as the ride starts moving again."
    "And once we're off, I sit her down until the symptoms pass."
    $ lexi.love -= 2
    $ game.active_date.score -= 20
    return

label lexi_date_merry_go_round_female:
    bree.say "How about we ride the Merry-Go-Round next, Lexi?"
    bree.say "I'm sure we can squeeze a quick one in between the other rides."
    "As soon as the words are out of my mouth, I realise what I actually said."
    "And so it comes as no surprise that Lexi bursts into peals of filthy laughter."
    lexi.say "Oh yeah?"
    lexi.say "You want to use the back-passage for that, [hero.name]?"
    lexi.say "Maybe deliver some sausage while you're back there?"
    "I do the best I can to keep things at least semi-serious."
    "Which seems to be simply ignoring Lexi and asking the question again."
    bree.say "Very funny, Lexi..."
    bree.say "But what about it?"
    bree.say "You want to ride the Merry-Go-Round or not?"
    lexi.say "What the hell..."
    lexi.say "Let's ride the thing."
    "With that decided, Lexi and I walk over to where the queue starts."
    "Thanks to this being an older and more sedate ride, it's not too long."
    "And we soon make our way to the front, climbing onto the Merry-Go-Round."
    "Lexi still has a knowing smile on her face as we choose where we're going to sit."
    "So it looks like she's going to be smirking at me for the length of the ride."
    "But as the thing starts to speed up, I notice a change in her mood."
    "Slowly she starts to cling on more tightly, noticing the speed of the ride."
    "And before too long she's rocking back and forth with the motion of it too."
    bree.say "Lexi..."
    bree.say "Are you okay?"
    lexi.say "Whoa..."
    lexi.say "I feel so fucking dizzy right now!"
    bree.say "Is that good or bad?"
    bree.say "If it's bad, I can make them stop the ride, okay?"
    lexi.say "No, no..."
    lexi.say "It's good!"
    "Lexi whoops and screams her way through the rest of the ride."
    "And even when she gets off she seems to be staggering as she walks."
    "But she looks like she's enjoying the sensation."
    "So I decide to leave it well enough alone."
    $ lexi.love += 2
    $ game.active_date.score += 20
    return

label lexi_date_haunted_house_female:
    bree.say "There's the Haunted House, Lexi..."
    bree.say "I always try to go in there."
    bree.say "It's my favourite thing at the park!"
    "Lexi gives me a shrug as we walk over to the Haunted House."
    lexi.say "Huh!"
    lexi.say "I never really gave a toss either way."
    lexi.say "But if you like it that much, we should probably go on there."
    "Even a half-hearted answer like that is good enough for me."
    "And so I lead the way to the back of the line for the Haunted House."
    "Lexi and I chat about everything and nothing as we work our way up the queue."
    "So it comes as a surprise when we're the next in line to enter."
    "As soon as we're in there, I feel myself getting lost in the experience."
    "I love every twist and turn in the place, every jump-scare and pop-up surprise."
    "But Lexi doesn't seem to have the same reaction as me."
    "Sure, she's not complaining about it or asking when we're going to get out."
    "Yet I can tell that she's not exactly enjoying herself either."
    "Which kind of brings the whole thing down for me a little too."
    "Once we're out of the Haunted House, I think about bringing it up."
    "But as it would probably only spark an argument, I decide to leave it alone."
    "That and not to take Lexi into the Haunted House with me the next time."
    return

label lexi_date_love_boat_female:
    show lexi b surprised
    lexi.say "The Love Boat?"
    lexi.say "Wasn't that a crappy TV show from like the stone age or something?"
    lexi.say "How come they made a ride out of it?"
    "I shrug and shake my head."
    bree.say "I never heard of that show, Lexi."
    bree.say "But the ride can be pretty fun."
    bree.say "You know, depending on who you ride it with?"
    "I add a nod and a wink, just to be sure Lexi understands me."
    "And that seems to do the trick."
    lexi.say "Oh yeah?"
    bree.say "Yeah!"
    lexi.say "Well now we have to ride it!"
    "Lexi wastes no time in grabbing me by the hand."
    "Then she leads me over to where the queue begins."
    "We don't have to wait in line long before we reach the front."
    "But Lexi seems less than impressed when she sees the actual boat."
    lexi.say "That's it?"
    lexi.say "Like, a crappy little wooden boat?!?"
    bree.say "It gets better, Lexi..."
    bree.say "Just trust me, okay?"
    "Lexi doesn't look convinced."
    "But she gets into the boat anyway."
    "And then we sail off into the gloomy tunnel."
    lexi.say "So what happens next?"
    lexi.say "Is it like a roller-coaster?"
    lexi.say "Or a ghost train?"
    bree.say "Erm..."
    bree.say "No, Lexi..."
    bree.say "We're just supposed to make out in here."
    lexi.say "What?!?"
    lexi.say "We could do that outside!"
    bree.say "Yeah, I know..."
    bree.say "But in here nobody can see us."
    lexi.say "Who cares if anyone sees us?!?"
    lexi.say "Fuck sake, [hero.name] - this is totally pointless and SO boring!"
    $ lexi.love -= 4
    $ game.active_date.score -= 30
    return

label lexi_date_hedge_maze_female:
    lexi.say "Hedge Maze?"
    lexi.say "How dumb does that sound!"
    lexi.say "Who wants to get lost on purpose?"
    "I hardly hear Lexi's withering comments on the Hedge Maze."
    "Because I'm more interested in the fact the queue is so short."
    "We could be in there far faster than with the other rides around it."
    bree.say "I dunno, Lexi..."
    bree.say "It could be fun."
    bree.say "Figuring a way to escape - kind of like one of those escape rooms."
    "Lexi shakes her head at this."
    "But she still follows me as I walk over to join the queue."
    "And I'm soon proven right as it takes almost no time to get to the front."
    "As soon as we get inside, I do all I can to prove myself right a second time."
    "Though it soon becomes apparent that my efforts are having no effect on Lexi."
    "She puffs, moans and complains the entire way around the maze."
    "Telling me off for not getting us out of there quickly enough."
    "While at the same time doing nothing to help find the exit."
    "And once we're out, I turn my back on the maze and vow never to return."
    "At least not while I'm here with Lexi."
    $ lexi.love -= 2
    $ game.active_date.score -= 10
    return

label lexi_date_amusement_ice_cream_male:
    mike.say "Hey, Lexi..."
    mike.say "You want to grab an ice-cream?"
    "Lexi turns her head to look at me as I ask the question."
    "And I can see there's already a smile spreading across her face."
    lexi.say "You bet I do!"
    lexi.say "I fucking love ice-cream."
    "Lexi and I hurry over to the ice-cream stand."
    "And once we're there, Lexi stares at the menu."
    "By which I mean she really stares."
    "Like she's going to start drooling any moment!"
    lexi.say "Ooh..."
    lexi.say "I want a big one, [hero.name]…"
    lexi.say "One of those!"
    "I buy Lexi the ice-cream that she wants and a smaller one for myself."
    "But as I had over the money and take my ice-cream, I see the server staring at something."
    "And when I turn around, I instantly see what's caught their interest."
    "Lexi's already licking away at her ice-cream, eyes closed and totally engrossed."
    lexi.say "Mmm..."
    lexi.say "Oh yeah..."
    lexi.say "Uurgh…"
    lexi.say "That tastes SO fucking good!"
    "It's only when I hear the sound of something wet splattering on the ground that I snap out of it."
    "Realising that a large dollop of my own ice-cream's fallen at my feet while I've been staring at Lexi eating her own."
    $ lexi.love += 2
    $ game.active_date.score += 20
    return

label lexi_date_amusement_ice_cream_female:
    lexi.say "Hey, [hero.name]..."
    lexi.say "You wanna grab an ice-cream?"
    lexi.say "Maybe share a big one with me?"
    "Lexi adds a raucous snort of laughter to the last question."
    "Underlining the fact that she's trying to be suggestive."
    bree.say "So long as we really talking about ice-cream, Lexi!"
    bree.say "Because I want to cool down a little, you know?"
    "Lexi leads the way over to the ice-cream stand and gets the server's attention."
    lexi.say "Ooh..."
    lexi.say "I see a big one, [hero.name]…"
    lexi.say "One of those!"
    bree.say "Looks good to me, Lexi..."
    bree.say "But are you sure you want to share?"
    lexi.say "Sure I'm sure."
    "I shrug as I order the ice-cream that Lexi's pointing to."
    "And it doesn't take long for the server to knock it up."
    "As soon as they hand it over, Lexi lean in and starts licking."
    lexi.say "Mmm..."
    lexi.say "Oh yeah..."
    lexi.say "Uurgh…"
    lexi.say "That tastes SO fucking good!"
    "It's all that I can do to remember to keep licking away myself."
    "Because Lexi's being more than a little distracting right now."
    "And I don't think there's any hope of this actually cooling me down."
    "Right now it seems to be doing the exact opposite!"
    $ lexi.love += 2
    $ game.active_date.score += 20
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
