label dwayne_date_amusement_park_female:
    scene bg amusement
    show dwayne
    with fade
    "I'm feeling stoked to be going to the Amusement Park today."
    "Sure, I've been there before and on more than one occasion."
    "But I don't have college or a shift at work to worry about."
    "All that lies ahead of me is a day of fun and frivolity at the park!"
    show dwayne angry
    dwayne.say "Ahem..."
    show dwayne upset
    "Oh, and I almost forgot to mention that I'm not here on my own."
    "Dwayne's come along with me too, and so he's going to joining in the fun!"
    "Or at least he should be looking forward to having a good time."
    "But right now he looks like something's annoying him."
    "I wonder what it could be?"
    bree.say "Are you okay, Dwayne?"
    bree.say "Do you have a frog in your throat?"
    show dwayne vangry
    dwayne.say "No, [hero.name], I don't."
    dwayne.say "But I would appreciate it if you'd tone things down a little."
    show dwayne upset
    "I can't help staring at Dwayne in confusion."
    bree.say "What are you talking about?"
    bree.say "I'm just excited that we're going to the Amusement Park, that's all."
    bree.say "Aren't you getting excited too?"
    show dwayne annoyed
    "Dwayne rolls his eyes and lets out a sigh."
    dwayne.say "Hmm..."
    show dwayne shout
    dwayne.say "[hero.name], that's the way Cassidy used to behave when I brought her to a place like this."
    dwayne.say "And I indulged it in her because she was a child at the time."
    dwayne.say "You're neither a child nor my daughter, you're my date."
    dwayne.say "So I'd appreciate you behaving in a way that reflects that fact."
    show dwayne normal
    "For a moment I don't know what to say."
    "I just stare at Dwayne without blinking."
    "But then I shake my head at him."
    bree.say "Oh, come on..."
    bree.say "Since when did you have a stick up your ass?"
    "Dwayne's eyes go wide with surprise at this."
    "And he looks left and right, checking to see if anyone overheard me."
    "Then he makes to say something in return."
    "Probably something that he thinks will put me in my place."
    "Or at least make it seem like he's won the argument."
    "But I'm not about to let that happen."
    "So I turn and run straight through the gates of the park."
    show dwayne vangry
    dwayne.say "[hero.name]..."
    dwayne.say "Where are you going?"
    dwayne.say "Get back here!"
    show dwayne upset
    "I only glance back over my shoulder long enough to make sure of one thing."
    "That Dwayne's been forced to shut up and follows me."
    "Once I see that, I don't hesitate to keep on running deeper into the park."
    return

label dwayne_date_ferris_wheel_female:
    bree.say "How about the Ferris Wheel, Dwayne?"
    bree.say "You want to ride that?"
    "Dwayne looks up at the wheel, towering above us."
    "And then he nods his head."
    dwayne.say "If you want to ride it, [hero.name]..."
    dwayne.say "Then we'll ride it."
    "Dwayne's answer kind of catches me off-guard."
    "Because I really wasn't expecting him to say yes."
    "I was sure he'd dismiss the Ferris Wheel out of hand."
    "That he'd say it was too old and boring for him to bother with."
    "Or that it was one of the rides intended for kids."
    "But as we join the queue, Dwayne reminds me of how charismatic he can be."
    "Because he chats away to me, telling me intriguing little anecdotes."
    "And that way he keeps me interested until we reach the head of the queue."
    "Then he stands aside and allows me to step into the gondola first."
    "Oh man..."
    "He really knows how to turn on the charm!"
    "As we start to rise into the air, Dwayne looks out."
    "And I can tell that he's admiring the view, taking it all in."
    dwayne.say "That really is something."
    dwayne.say "Don't you think, [hero.name]?"
    bree.say "Oh, come on, Dwayne..."
    bree.say "The view from your office window is higher."
    bree.say "And you must see that almost every day."
    bree.say "What's so special about this one?"
    "Dwayne chuckles and shakes his head."
    dwayne.say "There's no comparison to this."
    dwayne.say "Seeing this from behind reinforced glass just isn't the same."
    dwayne.say "And the company has a lot to do with it as well."
    "Dwayne turns to look me in the eye as he says the last part."
    "And then he hits me with the big guns."
    "He raises that one eyebrow to underline the point."
    "I can already feel my heart pounding in my chest."
    "And he seems to know it too."
    "Because he holds my eye for what feels like the rest of the ride."
    $ dwayne.love += 2
    $ game.active_date.score += 20
    return

label dwayne_date_merry_go_round_female:
    bree.say "We could grab a ride on the Merry-Go-Round, Dwayne."
    bree.say "The queue for that one's always pretty short too."
    "Dwayne gazes over at the Merry-Go-Round and seems to study it for a moment."
    "Then he nods his head, but I don't know which point he's agreeing with."
    dwayne.say "Hmm..."
    dwayne.say "The queue's probably short because of the ride's age, [hero.name]."
    dwayne.say "It's got to be one of the oldest things in the park!"
    "I can't help frowning at Dwayne's answer."
    "Because it doesn't answer my first question."
    "And it just sounds like he's pissing on my idea too!"
    bree.say "Yeah, well..."
    bree.say "Maybe that's so..."
    bree.say "But do you want to go on it or not?"
    "Dwayne moves his head in a way that might be a nod."
    "Or it might just as easily be an unconscious tic!"
    dwayne.say "If that's what you want."
    dwayne.say "Then we can spare a few minutes."
    "That's a good enough answer for me."
    "And so we go to join the back of the queue."
    "It's not long before we make it to the front, thanks to the shortness of the line."
    "Then Dwayne and I choose our places on the ride."
    "I hold on tight as it starts to move, nodding to Dwayne."
    "He does that thing with his head again."
    "Moving it in a way that might or might not be a nod in return."
    "But then the ride lurches, gaining speed."
    "And I have to devote all of my attention to holding on."
    "Afterwards, I do the best I can to get a find out what Dwayne thinks."
    "But he keeps on smoothing over everything, not showing his true thoughts."
    bree.say "That was pretty good, huh?"
    dwayne.say "It wasn't bad."
    bree.say "So..."
    bree.say "The opposite of bad is good, right?"
    dwayne.say "If you say so, [hero.name]."
    "And we go on like that until I finally give up."
    "Let him be mysterious if he wants."
    "And I'll do the best I can to pretend I don't care."
    $ dwayne.love += 1
    $ game.active_date.score += 10
    return

label dwayne_date_haunted_house_female:
    dwayne.say "Ha!"
    dwayne.say "Will you look at that, [hero.name]..."
    dwayne.say "It looks like something out of a goofy horror movie!"
    "I follow Dwayne's line of sight as he keeps on laughing to himself."
    "And it doesn't take me long to see that he's talking about the Haunted House."
    "So the comments kind of get my back up a little."
    "Because that's one of the attractions that I really like."
    bree.say "Oh yeah, Dwayne?"
    bree.say "So what are you saying?"
    bree.say "That if you went in there, you wouldn't be scared?"
    "Dwayne turns and shoots me one of his classic challenging looks."
    "The kind he whips out when he senses that someone's questioning him."
    dwayne.say "Wait a second, [hero.name]..."
    dwayne.say "Are you saying I should put my money where my mouth is?"
    dwayne.say "That I should prove it?"
    "Dwayne can be super intimidating when he's in this kind of mood."
    "But I've come this far, so I'm not about to back down now."
    "So I do the best that I can to stand up to Dwayne."
    bree.say "That's exactly what I'm saying."
    bree.say "Put up or shut up, Dwayne!"
    bree.say "Show me that you can make it through the Haunted House..."
    bree.say "Without getting scared even once!"
    "Dwayne doesn't even bother to say a word in response."
    "He simply turns on his heels and strides over to the Haunted House."
    "I hurry to join him, standing by his side in the queue."
    "Because I'm more than a little eager to see if he can actually do it."
    "Once we make it to the front of the line, Dwayne gives me a nod."
    dwayne.say "Not one scare."
    dwayne.say "Just stand back and watch!"
    "Dwayne walks straight into the Haunted House, head held high."
    "And I follow, keen to see just what's about to happen."
    "But much to my surprise, Dwayne seems to be as good as his word."
    "He walks straight up to the first couple of scares."
    "Then he stands there impassively as they go off in front of him."
    "And even I can't help jumping at some of them."
    "Dwayne seems to notice my amazement."
    "And so he shoots me a knowing smile."
    dwayne.say "You see, [hero.name]..."
    dwayne.say "This is a walk in the park for me!"
    dwayne.say "I could do this all..."
    dwayne.say "AAARGH!"
    "I watch in amazement as Dwayne leaps up in the air."
    "His eyes are wide with what looks like genuine terror."
    "And his arms are waving in front of him."
    bree.say "Whoa..."
    bree.say "Way to lose the bet, Dwayne!"
    dwayne.say "What?!?"
    dwayne.say "Something just dripped down the back of my neck!"
    bree.say "I'm afraid that still counts."
    bree.say "It was something inside of the Haunted House."
    bree.say "And it scared you stiff."
    dwayne.say "That so does not count!"
    bree.say "I think you'll find that it does!"
    "Dwayne and I keep on squabbling as we walk out of the Haunted House."
    "And we're so distracted that we totally ignore the rest of the scares in there too."
    $ dwayne.love += 1
    $ game.active_date.score += 10
    return

label dwayne_date_love_boat_female:
    bree.say "You want to ride the Love Canal, right?"
    bree.say "I mean, it's kind of a rite of passage!"
    "Dwayne shrugs as he leads me towards the line for the ride."
    dwayne.say "If that's what you want, [hero.name]..."
    dwayne.say "Let's join the line."
    "As we queue up, I can't help staring at Dwayne."
    "Is he really going to be that blasé about this?"
    "I manage to hold it in until we're getting into the boat."
    "But then I'm almost bursting with irritation."
    "So I have to ask the question, even if it ruins the ride."
    bree.say "What's up, Dwayne?"
    bree.say "Why aren't you into the idea of the ride?"
    "Dwayne shakes his head."
    "But he looks like he's about to explain himself all the same."
    dwayne.say "Well, the thing is..."
    dwayne.say "Once you've been to places like Venice..."
    dwayne.say "And you've ridden in the gondola's there..."
    "Dwayne lets out a sigh."
    dwayne.say "You see..."
    dwayne.say "Nothing is ever as romantic again."
    dwayne.say "Everything pales in comparison."
    "Which I guess includes me!"
    bree.say "Whoa..."
    bree.say "Way to make me feel inadequate, Dwayne!"
    dwayne.say "Hey!"
    dwayne.say "Don't try to put this on me."
    dwayne.say "I was just being honest."
    "I cross my arms and turn away from Dwayne."
    "Making sure to look out of the opposite side of the boat."
    bree.say "Well then I'm just going to honestly look this way."
    bree.say "For the rest of the ride!"
    dwayne.say "Fine, you do that."
    dwayne.say "I'll just look the other way."
    "We spend the rest of the ride doing just that."
    "Deliberately ignoring each other and sulking."
    $ dwayne.love -= 1
    $ game.active_date.score -= 10
    return

label dwayne_date_hedge_maze_female:
    bree.say "Let's go the Hedge Maze next."
    bree.say "That looks like it could be fun!"
    "Dwayne shakes his head."
    "Evidently unimpressed with my suggestion."
    dwayne.say "Really, [hero.name]?"
    dwayne.say "That looks like the most boring thing in the entire park!"
    "I do the best I can to act like I didn't just hear that."
    "And instead I walk over to join the queue."
    "Which means that Dwayne can either join me."
    "Or he can refuse and cause a scene."
    "Luckily for me, he chooses the former."
    bree.say "Look how short the line is too."
    bree.say "We'll be in there in no time at all!"
    dwayne.say "The line's short because this ride sucks!"
    dwayne.say "Isn't that obvious?!?"
    "Once we're inside the maze, I keep on trying to big it up."
    "Looking around as if it's the most amazing thing ever."
    bree.say "Come on, Dwayne..."
    bree.say "Let's start exploring."
    bree.say "This is going to be one hell of an adventure!"
    "By now Dwayne seems to have lost the will to fight."
    "So instead he just trudges after me, looking defeated."
    "I manage to keep up the intensity of my reactions for a short while."
    "But by the time we round what feels like the hundredth corner, I feel myself cracking."
    bree.say "Oh wow..."
    bree.say "Another left turn!"
    bree.say "Ah, who am I trying to kid?"
    bree.say "This is just the same thing, over and over again!"
    dwayne.say "Thank god!"
    dwayne.say "Now can we get the hell out of here, please?"
    bree.say "Erm..."
    bree.say "Yeah..."
    bree.say "As soon as I figure out where the exit actually is!"
    $ dwayne.love -= 2
    $ game.active_date.score -= 20
    return

label dwayne_date_amusement_ice_cream_female:
    bree.say "Ooh..."
    bree.say "I could really go for an ice-cream right now!"
    bree.say "You want me to grab one for you too, Dwayne?"
    "I'm fully expecting Dwayne to burst out laughing and say no."
    "So it comes as some surprise to realise he's actually just staring at me."
    "That and raising a single eyebrow as he does so."
    bree.say "Erm..."
    bree.say "Dwayne..."
    bree.say "Is there something wrong?"
    bree.say "You know it makes me nervous when you do the eyebrow thing!"
    dwayne.say "Let me get this straight, [hero.name]..."
    dwayne.say "YOU want to buy Me an ice-cream?"
    "I look left and right, wondering if this is a trick question."
    "But in the end, all I can think to do is give Dwayne an honest answer."
    bree.say "Yeah, Dwayne..."
    bree.say "I want to buy you an ice-cream."
    "Dwayne throws his head back and bellows with laughter."
    dwayne.say "HA HA!"
    dwayne.say "Oh, [hero.name]..."
    dwayne.say "Do you know how long it's been since someone offered to buy me something?"
    dwayne.say "When you're as rich and influential as I am, it's always the other way round!"
    bree.say "Okay..."
    bree.say "So...do you want an ice-cream or not?"
    dwayne.say "Yes, [hero.name], I'd like an ice-cream."
    "Still a little freaked out, I make good on my promise."
    "Dwayne and I walk over to the ice-cream stand, and I buy us both a cone."
    "But it's while we're walking away that I think I start to get it."
    "Because Dwayne looks genuinely happy as he licks away."
    "And I get to thinking that maybe I just did something that made him happy."
    "Just a little gesture that treated him as a human being."
    "Rather than a walking ATM machine."
    $ dwayne.love += 4
    $ game.active_date.score += 40
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
