# label ayesha_date_amusement_park_male:
#     scene bg amusement
#     show ayesha sadsmile
#     with fade
#     "I'm always excited to be going to the Amusement Park, as it makes me feel like a kid again."
#     "And I'm even more keen when I get the chance to take someone special along with me."
#     "Today that's Ayesha, who I can feel squeezing my hand as we walk towards the entrance."
#     "But when I cast a look in her direction, I see that Ayesha doesn't seem as enthusiastic."
#     "It's not that she looks annoyed or pissed-off at the prospect."
#     "More that her expression is kind of neutral, not tending towards either extreme of emotion."
#     mike.say "Ayesha..."
#     mike.say "Are you feeling okay?"
#     show ayesha stuned
#     "At the sound of my voice, Ayesha seems to snap out of it a little."
#     show ayesha sadsmile
#     "She turns to look at me, a weak smile appearing on her face as she does so."
#     ayesha.say "Huh?"
#     show ayesha surprised
#     ayesha.say "Oh..."
#     ayesha.say "There's nothing wrong, [hero.name]."
#     ayesha.say "I'm fine, honestly."
#     show ayesha normal
#     mike.say "Really, Ayesha?"
#     mike.say "Because you don't look very excited."
#     show ayesha whining
#     ayesha.say "Well..."
#     ayesha.say "This kind of thing isn't really my bag, you know?"
#     show ayesha sad
#     mike.say "So what are you saying, Ayesha?"
#     mike.say "That you don't want to go in there?"
#     show ayesha normal
#     "Ayesha shakes her head at this."
#     show ayesha happy
#     ayesha.say "Oh no..."
#     ayesha.say "I'm fine with it, really."
#     ayesha.say "I'm determined to have a good time."
#     show ayesha normal
#     "I'm not so sure that you can force yourself to have a good time at a place like this."
#     "But I decide to go along with what Ayesha's saying, hoping for the best."
#     return

label ayesha_date_ferris_wheel_male:
    "As soon as I see the Ferris Wheel, I know that we have to ride it."
    "The image of all those romantic scenes from TV and the movies fill my head."
    "And I can just see Ayesha and me in the same position."
    mike.say "Let's ride the Ferris Wheel, Ayesha."
    mike.say "Come on - while the queue's short!"
    "Ayesha doesn't resist as I pull her towards the ride."
    "And soon enough we're sitting in one of the gondolas."
    "Then the ride starts up, and we climb slowly into the air."
    "Ayesha's been pretty quiet up to now, but I keep to my original plan."
    "Which involves slipping my arm around her shoulders and sliding closer."
    "And with Ayesha that's no mean feat, as she has pretty broad shoulders!"
    ayesha.say "Oh..."
    ayesha.say "Hello there, mister!"
    "I'm relieved to find that Ayesha doesn't try to pull away from me."
    "But at the same time she's not really getting into the spirit of it either."
    mike.say "Are you okay, Ayesha?"
    mike.say "Don't you like the view from up here?"
    ayesha.say "I'm fine, [hero.name]."
    ayesha.say "And the view's very nice."
    ayesha.say "It just doesn't seem to be doing anything for me, that's all."
    "All I can do in response to that is shrug and leave it alone."
    "It feels like enough that Ayesha at leas gave it a try."
    "So it'd be churlish to keep demanding more out of her."
    $ ayesha.love += 1
    $ game.active_date.score += 10
    return

label ayesha_date_merry_go_round_male:
    mike.say "How about the Merry-Go-Round, Ayesha?"
    mike.say "You want to take a ride on that?"
    "Ayesha looks the ride over for a moment."
    "Then she nods in agreement."
    ayesha.say "Sure, [hero.name]…"
    ayesha.say "Why not!"
    "Eager to make the most of Ayesha's enthusiasm, I head straight for the queue."
    "The ride seems to go pretty fast, so it doesn't take long for us to make it to the front either."
    "Soon enough we're on the Merry-Go-Round, waiting for it to get started."
    "As the ride begins to move, everything seems to be going well."
    "I glance over at Ayesha and see that she's smiling."
    "So I obviously assume that she's enjoying herself."
    "And I also indulge myself in thinking that I made a good call."
    "But as the ride gets up to speed, I hear Ayesha let out a groan."
    ayesha.say "Urgh..."
    "Turning in her direction, I see that she doesn't look happy."
    "And worse, her face is going pale right in front of my eyes!"
    mike.say "Ayesha..."
    mike.say "What's wrong?!?"
    ayesha.say "Feel...sick..."
    ayesha.say "Gonna...puke..."
    "This sends me into a flurry of panic."
    "As I can imagine Ayesha losing her breakfast on the ride."
    "Then the puke spraying onto everyone else, causing a chain-reaction."
    "Everyone throwing up at the same time!"
    "Luckily for me, the ride comes to a stop before that can happen."
    "I do the best I can to support Ayesha as she staggers off it."
    "She makes it to a nearby bathroom before it's too late."
    "And while I listen to the sound of her heaving inside, I make a mental note."
    "No more rides like that one, as Ayesha has a weak stomach!"
    $ ayesha.love -= 2
    $ game.active_date.score -= 20
    return

label ayesha_date_haunted_house_male:
    "As soon as I see hear the sounds of the Haunted House, I know that I have to go in there."
    "So I hurry over, pulling Ayesha along with me, already making for the back of the queue."
    "But much to my surprise, I feel her resisting me, trying to pull in the opposite direction."
    mike.say "What's wrong, Ayesha?"
    mike.say "It's just the Haunted House!"
    "As soon as I ask the question, Ayesha looks embarrassed."
    "As though she's ashamed to meet my eye and give me an answer."
    ayesha.say "I..."
    ayesha.say "I don't really like that kind of thing, [hero.name]."
    ayesha.say "And I don't normally go into them either!"
    "I brush Ayesha's objections away."
    "Already walking her into the queue as I do so."
    mike.say "Don't worry, Ayesha..."
    mike.say "This time it's different."
    mike.say "This time you're going in there with me!"
    "Ayesha opens her mouth to say something, probably to protest."
    "But it's too late, as we've already reached the head of the queue."
    "Before she can object, we're walking into the Haunted House."
    "And it doesn't take me long to discover the source of her misgivings too."
    "Almost as soon as the first jump-scare happens, Ayesha all but leaps into my arms."
    "As she lets out a scream of terror, I realise that she really is scared!"
    "The problem is that I naturally do all I can to comfort her."
    "And that results in Ayesha clinging onto me the whole way round the Haunted House."
    "So what's the problem with that, you might well ask?"
    "Who wouldn't want their hot date clinging onto them?"
    "Well you see Ayesha doesn't so much cling to me as put me in an impromptu wrestling hold."
    "And every time she gets scared by something, she instinctively tightens it up too!"
    "So by the time we get out of there, I feel like I've gone twelve rounds with a Boa Constrictor."
    "Which I guess is a fitting punishment for ignoring Ayesha's protests."
    $ ayesha.love -= 4
    $ game.active_date.score -= 20
    return

label ayesha_date_love_boat_male:
    ayesha.say "Oh look, [hero.name]..."
    ayesha.say "They have one of those Love Boats."
    ayesha.say "You know, like a Tunnel of Love?"
    "At the mere mention of the ride, my head begins to fill with ideas."
    "And I can imagine all the things we could get up to while in there."
    mike.say "Oh yeah, Ayesha..."
    mike.say "We so have to ride that!"
    "Ayesha looks a little surprised at first."
    "Like she doesn't think the ride is exciting enough for me."
    "But then her expression changes, becoming more knowing."
    "And she gives me a sideways glace with a little smile."
    ayesha.say "Okay, okay..."
    ayesha.say "I guess we can do that!"
    "I can hardly contain myself as we get into the boat."
    "But as it begins to move, Ayesha puts a hand on my chest."
    ayesha.say "But let me make one thing clear, [hero.name]..."
    ayesha.say "Kissing and cuddling is totally acceptable."
    ayesha.say "No tyring to get more adventurous than that though."
    ayesha.say "Because I don't want to tip up the boat and end up in the water!"
    show ayesha kiss
    $ ayesha.flags.kiss += 1
    "I nod in agreement, getting Ayesha's point."
    "And we do have a pretty nice time doing what she describes."
    "But somehow the mere mention of going further makes me want to do it."
    "So I can't help feeling a little disappointed when the ride is over."
    hide ayesha
    show ayesha
    $ ayesha.love += 4
    $ game.active_date.score += 20
    return

label ayesha_date_hedge_maze_male:
    mike.say "Let's try the Hedge Maze out, Ayesha."
    mike.say "I bet you can't find your way out!"
    "Ayesha seems more than a little intrigued by my challenge."
    "And she nods as we walk over to the queue for the maze."
    ayesha.say "You're on, [hero.name]."
    ayesha.say "I'm sure it's just a matter of thinking rationally."
    ayesha.say "That and remembering where you've already been."
    "But as soon as we're inside the maze, I sense there's something wrong."
    "Ayesha just doesn't look enthusiastic anymore."
    "Yet I can't put my finger on what could have happened to change her mood."
    mike.say "What's wrong, Ayesha?"
    mike.say "I thought you were really up for this?"
    "Ayesha lets out a weary sigh and shakes her head."
    ayesha.say "It's just one of those things, [hero.name]."
    ayesha.say "Stuff you kind of get used to when you're extra tall."
    "I shake my head, still not getting it."
    "That is until Ayesha stands up to her full height."
    "Which shows me that she can clearly see over the top of the hedges!"
    mike.say "Oh..."
    mike.say "I see what you mean."
    mike.say "I guess you can..."
    ayesha.say "See the exit from up here?"
    ayesha.say "Yeah, pretty much!"
    mike.say "Ouch..."
    mike.say "Sorry, Ayesha!"
    ayesha.say "Don't worry, [hero.name]..."
    ayesha.say "You weren't to know."
    ayesha.say "And one advantage of being tall is that I can see the ice-cream stand from here."
    ayesha.say "Follow me out of the maze and we'll go grab one, okay?"
    "I nod and take Ayesha's hand, letting her lead me out of the maze."
    $ ayesha.love += 0
    $ game.active_date.score += 0
    return

label ayesha_date_amusement_ice_cream_male:
    mike.say "Hey, Ayesha..."
    mike.say "You want to grab an ice-cream?"
    "Ayesha shakes her head as I ask the question."
    ayesha.say "Ah, no..."
    ayesha.say "I'll pass, [hero.name]."
    ayesha.say "But you go right ahead and get one for yourself if you want."
    "I can't help frowning as I make my way over to the ice-cream stand."
    mike.say "Are you seriously saying you don't like ice-cream?"
    ayesha.say "Oh no, I love it!"
    ayesha.say "I'm just training hard at the moment."
    ayesha.say "So I have to watch what I eat, that's all."
    "I give Ayesha a shrug as I turn around to place my order."
    "And for a moment I'm distracted as the server makes it up."
    "Once the ice-cream is in my hands, I take my first lick."
    "Which is when I look up to see Ayesha staring at me intently."
    "In fact, she's even biting her lip!"
    mike.say "Erm..."
    mike.say "Are you okay, Ayesha?"
    mike.say "Why are you looking at me like that?"
    ayesha.say "I..."
    ayesha.say "Well..."
    ayesha.say "Maybe I could have just one lick?"
    ayesha.say "I'm sure that wouldn't hurt my diet!"
    "More than happy to oblige, I hold out my ice-cream to Ayesha."
    "Then I watch as she leans in and begins to lick away at it."
    "And I have to say that she takes more than one."
    "But as she's licking away, I can see the sheer pleasure on her face."
    "So instead of stopping her, I just stand there and watch."
    "Because while the ice-cream is getting softer, the opposite is happening in my pants!"
    $ ayesha.love += 2
    $ game.active_date.score += 20
    return

label ayesha_date_amusement_park_female:
    scene bg amusement
    show ayesha
    with fade
    "I was in two minds whether to ask Ayesha along to the Amusement Park with me."
    "Not because I'm embarrassed to be seen there with a girl as my date."
    "Of course not - I'd happily go anywhere with Ayesha."
    "It was more because she can seem awkward in some social situations."
    "I guess that's because she's such a big girl, and she stands out even in a crowd."
    "But I figured that there are usually so many people at the Amusement Park."
    "Way too many to really be crowd - more like a sea of people really."
    "So even someone as unique as Ayesha should be able to get lost in the middle of them all."
    "The only problem is that I don't know if Ayesha sees it that way."
    "So as we approach the gates to the park, I try to gauge her mood."
    "But without letting her know what I'm doing, of course!"
    show ayesha talkative
    ayesha.say "[hero.name]..."
    ayesha.say "What are you doing?"
    show ayesha normal
    "The fact that Ayesha pretty much calls me out as soon as I start takes me by surprise."
    "And I'm forced to think up an excuse on the spot."
    bree.say "Huh?"
    bree.say "What do you mean?"
    bree.say "I'm not doing anything!"
    "Yeah, I know, I know..."
    "She caught me on the hop, okay!"
    show ayesha curious
    ayesha.say "Erm..."
    show ayesha talkative
    ayesha.say "I think you are, [hero.name]."
    ayesha.say "You keep looking at me and then looking away before you think I've noticed."
    show ayesha normal
    bree.say "I do?"
    bree.say "Well..."
    bree.say "That's just because I'm so glad to be here with you, Ayesha!"
    show ayesha happy
    "Ayesha gives me a look that says she shares the sentiment."
    "But I can tell there's also some suspicion in her eyes too."
    ayesha.say "Me too, [hero.name]..."
    ayesha.say "But just remember, I find being in crowds kind of hard."
    ayesha.say "So try to act normal, okay?"
    show ayesha normal
    "I nod and smile, hoping that's enough to reassure Ayesha."
    "Then we walk into the park together and join the crowds."
    "And all the time I'm hoping that my efforts not to ruin the day don't end up doing just that."
    return

label ayesha_date_ferris_wheel_female:
    bree.say "I think we should ride the Ferris Wheel, Ayesha."
    "Ayesha turns to look a the ride in question as I mention it."
    "And as she does so, I can see that she's sizing it up."
    ayesha.say "Are you sure, [hero.name]?"
    ayesha.say "That looks like the oldest ride in the park!"
    "I shake my head as I start to walk towards the line for the ride."
    "Which means that Ayesha has to follow me if she wants to keep up the conversation."
    bree.say "That means it's a classic."
    bree.say "The kind of thing you have to ride to get the authentic theme park experience."
    ayesha.say "Hmm..."
    ayesha.say "Are you sure it's even safe?"
    bree.say "Of course I am!"
    bree.say "It wouldn't be open if it wasn't safe."
    "By this time we're already standing in the queue."
    "And we're making our way to the front as we keep on talking."
    ayesha.say "Okay, [hero.name]..."
    ayesha.say "I guess we're okay to ride it."
    "Almost as soon as Ayesha finishes saying that, we're at the front of the queue."
    "There's a gondola waiting for us and we step straight into it."
    "Then the safety-bar comes down and we begin to ascend."
    "Ayesha sits quietly, watching as the view gets better by the second."
    "Part of me is waiting for her to announce that she's scared of heights."
    "Because that's the kind of thing that seems to happen to me in situations like this."
    "But instead, Ayesha stays silent the whole time."
    "Even when the ride stops at the top, she still just keeps on admiring the view."
    "In fact Ayesha keeps quiet until we're getting off the ride."
    ayesha.say "You know what, [hero.name]..."
    ayesha.say "That wasn't too bad."
    bree.say "I knew it!"
    ayesha.say "I mean, it wasn't brilliant."
    ayesha.say "But it wasn't bad either."
    "I suppose I can take that as a minor win, right?"
    $ ayesha.love += 1
    $ game.active_date.score += 10
    return

label ayesha_date_merry_go_round_female:
    bree.say "How about the Merry-Go-Round, Ayesha?"
    bree.say "Everyone likes that ride, don't they?"
    "Ayesha looks at the ride with a thoughtful expression on her face."
    "And for a moment I think she's going to say no."
    "But then she nods and starts walking towards the Merry-Go-Round."
    ayesha.say "You know, [hero.name]..."
    ayesha.say "I haven't ridden one of these things is forever."
    ayesha.say "And I just don't know why that is."
    "Sensing the chance to encourage Ayesha, I don't hesitate to jump in."
    bree.say "All the more reason to ride it now, Ayesha."
    bree.say "This is a chance to remind yourself of what you've been missing."
    "Ayesha nods and together we join the back of the queue."
    "Luckily for us the Merry-Go-Round is one of the older rides in the park."
    "That means the line is short and moves pretty quickly."
    "So it doesn't take long for us to be ushered onto it."
    "Ayesha picks her spot, and I make sure to be right by her side."
    ayesha.say "[hero.name]..."
    ayesha.say "I think something just came back to me."
    ayesha.say "I think I remember why..."
    "Suddenly the ride jerks into motion."
    "This cuts Ayesha off before she can finish what she was trying to say."
    "And I watch as she clings onto the pole in front of her for dear life."
    "To me it looks like she's just surprised by the sudden motion."
    "So I turn my head away and allow myself to enjoy the ride."
    "It doesn't last all that long, and soon enough it slows then comes to a stop."
    "But when I turn to look at Ayesha again, I see her lurching off the ride."
    "And from the brief glimpse I get of her face, she looks pretty pale."
    bree.say "Ayesha?"
    bree.say "What's the matter?"
    "Despite my calls, Ayesha doesn't stop to answer me."
    "So I follow her as she dashes off the ride and towards a nearby restroom."
    "I wait outside, listening to the distressing sounds coming from inside."
    "And when Ayesha finally emerges, she's wiping the corners of her mouth."
    ayesha.say "Motion...sickness..."
    ayesha.say "That's why...no Merry-Go-Rounds!"
    $ ayesha.love -= 1
    $ game.active_date.score -= 10
    return

label ayesha_date_haunted_house_female:
    bree.say "Oh wow!"
    bree.say "The Haunted House looks so good!"
    bree.say "What do you say we do that next?"
    "I can't keep the enthusiasm out of my voice."
    "But Ayesha doesn't seem as keen as me to go into the Haunted House."
    ayesha.say "I...I don't know, [hero.name]..."
    ayesha.say "That's really not my kind of thing."
    "I shake my head at this."
    "Not willing to be talked out of it so easily."
    bree.say "Oh come on, Ayesha..."
    bree.say "I need you to come in there with me."
    bree.say "You can be my bodyguard, yeah?"
    bree.say "Keep me safe from all the ghosts and ghouls!"
    "Ayesha still doesn't seem sold on the idea."
    "But all the same, she lets me drag her over to the queue."
    "All the time we're waiting in it, I keep on about how great this is going to be."
    "Yet all that I can get out of Ayesha in response are a couple of tense nods."
    "Right up until it's our turn to walk through the entrance."
    bree.say "Okay, Ayesha..."
    bree.say "Here goes!"
    "Together we walk into the Haunted House."
    "And I'm expecting to spend the next few minutes screaming my head off."
    "But of course with the added bonus of being able to hide behind Ayesha."
    "Then the first scare jumps out at us."
    "And Ayesha lets out the loudest shriek I've ever heard."
    ayesha.say "Aaargh!"
    ayesha.say "[hero.name], save me!"
    "For a moment I honestly think she's going to leap into my arms."
    "But luckily for me, Ayesha just tries to hide herself behind me."
    "Which, given the size difference, looks pretty ridiculous."
    "From that point on, I find myself leading her through the Haunted House."
    "Shielding her from everything that pops up along the way."
    "Sure, it's a pretty bizarre experience for me."
    "Yet at least I now know why Ayesha didn't want to come in here to begin with."
    $ ayesha.love -= 2
    $ game.active_date.score -= 20
    return

label ayesha_date_love_boat_female:
    bree.say "The Love Boat looks quiet right now, Ayesha."
    bree.say "I bet we could walk right onto it."
    "Ayesha doesn't look very enthusiastic at the suggestion."
    "Which I have to admit makes me feel a little aggrieved."
    ayesha.say "Are you sure you want to ride that, [hero.name]?"
    ayesha.say "Especially with me?"
    "Now I really can't believe what I'm hearing."
    "What is Ayesha trying to suggest?"
    "That I'm embarrassed to be seen with her?"
    bree.say "Who else would I want to ride it with?"
    bree.say "Aren't we here on a date?"
    "As soon as I make my point, Ayesha's expression changes."
    "She goes from concerned to amused in mere seconds."
    ayesha.say "Oh, [hero.name]..."
    ayesha.say "That's not what I mean at all!"
    bree.say "Huh?"
    bree.say "Then what do you mean?"
    ayesha.say "I mean those boats look very fragile to me."
    ayesha.say "Are you sure they could handle my weight?"
    "I stare at Ayesha blankly for a moment."
    "Then I feel myself starting to blush."
    bree.say "I..."
    bree.say "Well..."
    bree.say "Let's see what the sign on the ride says!"
    "A quick check proves that Ayesha's well within the tolerances of the ride."
    "And with that settled, she soon agrees to get into one of the boats with me."
    "What follows is a pretty romantic experience, and a very private one too."
    "So you're going to have to use your imagination fill in the rest of the details."
    "Because I had my hands full the whole time we were in there!"
    $ ayesha.love += 2
    $ game.active_date.score += 20
    return

label ayesha_date_hedge_maze_female:
    bree.say "You fancy tackling the Hedge Maze, Ayesha?"
    bree.say "Facing the challenge of a cerebral attraction?"
    "Almost as soon as I issue the challenge, Ayesha nods."
    "And then she strides straight over to the entrance of the maze."
    ayesha.say "Now that sounds like my kind of thing, [hero.name]!"
    ayesha.say "Let's see if this maze is anything but a pushover!"
    "The maze doesn't seem to be one of the more popular attractions in the park."
    "Which means a short line and an equally short time to wait in it too."
    "So we soon find ourselves walking into the maze together."
    bree.say "Okay..."
    bree.say "Let's do this!"
    "Ayesha chuckles at my enthusiasm."
    "And then we begin to explore the maze in earnest."
    "Pretty soon the twists and turns start to get me confused."
    "Every turn we make, I find myself somewhere I swear I've been before."
    "The walls of every stretch look just the same as the last."
    "And I'm getting worried that I'll never find my way out."
    "Which is why I'm glad to have Ayesha with me right now."
    "She seems to know exactly where we're going the whole time."
    "Even when she stops to figure it out, she looks totally confident."
    "So it comes as no surprise to me that she soon leads me out of there."
    ayesha.say "There we are."
    ayesha.say "I just knew the exit had to be round that last corner!"
    bree.say "Erm..."
    bree.say "Yeah, Ayesha..."
    bree.say "It had to be there!"
    bree.say "I wasn't worried about getting lost at all..."
    $ ayesha.love += 2
    $ game.active_date.score += 20
    return

label ayesha_date_amusement_ice_cream_female:
    bree.say "Hey, Ayesha..."
    bree.say "You want to grab an ice-cream?"
    "Ayesha shakes her head as I ask the question."
    ayesha.say "Ah, no..."
    ayesha.say "I'll pass, [hero.name]."
    ayesha.say "But you go right ahead and get one for yourself if you want."
    "I can't help frowning as I make my way over to the ice-cream stand."
    bree.say "Are you seriously saying you don't like ice-cream?"
    ayesha.say "Oh no, I love it!"
    ayesha.say "I'm just training hard at the moment."
    ayesha.say "So I have to watch what I eat, that's all."
    "I give Ayesha a shrug as I turn around to place my order."
    "And for a moment I'm distracted as the server makes it up."
    "Once the ice-cream is in my hands, I take my first lick."
    "Which is when I look up to see Ayesha staring at me intently."
    "In fact, she's even biting her lip!"
    bree.say "Erm..."
    bree.say "Are you okay, Ayesha?"
    bree.say "Why are you looking at me like that?"
    ayesha.say "I..."
    ayesha.say "Well..."
    ayesha.say "Maybe I could have just one lick?"
    ayesha.say "I'm sure that wouldn't hurt my diet!"
    "More than happy to oblige, I hold out my ice-cream to Ayesha."
    "Then I watch as she leans in and begins to lick away at it."
    "And I have to say that she takes more than one."
    "But as she's licking away, I can see the sheer pleasure on her face."
    "So instead of stopping her, I just stand there and watch."
    "Because I can see that the ice-cream is melting and starting to drip."
    "And let's just say that a similar thing is happening in my panties right now too!"
    $ ayesha.love += 2
    $ game.active_date.score += 20
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
