label mike_use_condom:
    $ result = randint(0, 5)
    if result == 0:
        bree.say "But first..."
        bree.say "We need to get a condom on this thing!"
        "[mike.name] nods as I hop off him and grab a condom."
        "Then he watches with interest as I hop back on."
        mike.say "You need a hand there, [hero.name]?"
        bree.say "Nah, I'm good."
        "A few moments later it's on."
        "And then we're ready to go."
    elif result == 1:
        "But there's one more thing I need to take care of first."
        bree.say "Just a second, [mike.name]..."
        bree.say "We need some protection."
        mike.say "Oh..."
        mike.say "Oh yeah!"
        mike.say "Good thinking, [hero.name]!"
        bree.say "Don't worry, I have some right here."
        "I slip out of bed and grab a condom from my stash."
        "Then I slide back into bed and slide it onto [mike.name]'s cock."
        "That done, we're ready to go."
    elif result == 2:
        "But first things first."
        "We need to take precautions."
        bree.say "Wait a minute, [mike.name]."
        bree.say "We need to use a condom."
        mike.say "Oh..."
        mike.say "Oh yeah!"
        mike.say "Good idea, [hero.name]!"
        bree.say "Don't worry."
        bree.say "I've got one - right over there."
        "[mike.name] follows my hand as I point it out."
        "Then he hops off the bed to grab the condom."
        "As soon as he has it on, we're back to it."
    elif result == 3:
        bree.say "But first, we're going to need a condom."
        bree.say "Be a dear and go grab one from over there?"
        "I nod in the direction of where I keep my condoms."
        "But I also give his cock a tug in that direction too."
        mike.say "Ouch!"
        mike.say "Okay, okay!"
        mike.say "I'm on it, [hero.name]!"
        "[mike.name] hops off the bed to retrieve the condom."
        "Then he walks back, already slipping it on."
        "So once he climbs back onto the bed, we're good to go."
    elif result == 4:
        "But just as [mike.name]'s about to do as he's told, I remember something."
        "And before he can go any further, I wave my hands in the air."
        bree.say "No, [mike.name]..."
        bree.say "Wait a minute!"
        mike.say "Huh?"
        mike.say "What's the problem?"
        "I hop off the bed and make for the bedside table."
        bree.say "I forgot the condom!"
        bree.say "But it's okay..."
        bree.say "I have one right here."
        "I hold the condom up as I hurry back to the bed."
        "And [mike.name] nods in agreement."
        mike.say "Oh yeah..."
        mike.say "Good thinking,[hero.name]!"
        "It only takes me a couple of seconds to get the thing on him."
        "And then we're all ready to go."
    else:
        "But then a thought occurs to me."
        bree.say "Whoa..."
        bree.say "We need to take precautions first!"
        mike.say "Huh?"
        mike.say "What do you mean, [hero.name]?"
        bree.say "We need to grab a condom, [mike.name]."
        bree.say "I keep some just over there."
        "[mike.name] follows the direction I'm glancing in."
        "Then he hops off the bed and grabs one."
        "Quickly putting it on, he gets back into position."
        "That done, we're ready to go."
    return







label mike_warn_condom:
    $ result = randint(0, 5)
    if result == 0:
        mike.say "Ah, [hero.name]..."
        mike.say "We really should use a condom."
    elif result == 1:
        mike.say "Would you stop torturing me for a moment, [hero.name]?"
        mike.say "Don't worry..."
        mike.say "You can start again as soon as we grab a condom!"
    elif result == 2:
        "But then [mike.name] stops and shakes his head."
        mike.say "Wait a minute, [hero.name]..."
        mike.say "We should really use a condom."
    elif result == 3:
        "But then I feel [mike.name] hesitate."
        bree.say "Huh?"
        bree.say "What's up, [mike.name]?"
        mike.say "Erm..."
        mike.say "We should really use a condom, [hero.name]!"
    elif result == 4:
        "I'm waiting patiently for [mike.name] to do as he's told."
        "But instead, he stops in his tracks."
        bree.say "What's the matter, [mike.name]?"
        bree.say "Why did you stop?"
        mike.say "I just remembered, [hero.name]..."
        mike.say "We need to grab a condom!"
    else:
        "But then [mike.name] seems to think of something."
        "Because he lets go of my ass."
        bree.say "What's up, [mike.name]?"
        mike.say "You know what, [hero.name]..."
        mike.say "We should really use a condom!"
    return

label mike_force_condom:
    $ result = randint(0, 5)
    if result == 0:
        mike.say "Don't worry, I have one right here!"
        "Before I can say a word, [mike.name] wriggles out from under me."
        "Then he grabs a condom and gets back into the same position."
        "A few moments later it's on."
        "And then we're ready to go."
    elif result == 1:
        mike.say "Gimmie a second..."
        mike.say "I've got one right over here."
        "[mike.name] hops off the bed to retrieve the condom."
        "Then he walks back, already slipping it on."
        "So once he climbs back onto the bed, we're good to go."
    elif result == 2:
        mike.say "Don't worry."
        mike.say "I have one on me."
        "[mike.name] hops off the bed to grab the condom."
        "As soon as he has it on, we're back to it."
    elif result == 3:
        mike.say "Don't worry."
        mike.say "I have one in my pocket!"
        "[mike.name] slips out of bed and grabs the condom."
        "Then he slides back into bed and we slide it onto his cock."
        "That done, we're ready to go."
    elif result == 4:
        mike.say "Don't worry..."
        mike.say "I have one in my wallet."
        "I let [mike.name] up from the bed so he can go grab it."
        "Then he holds up the condom as he hurries back to the bed."
        "It only takes me a couple of seconds to get the thing on him."
        "And then we're all ready to go."
    else:
        mike.say "Don't worry..."
        mike.say "I have one on me!"
        "[mike.name] hops off the bed and grabs the condom."
        "Quickly putting it on, he gets back into position."
        "That done, we're ready to go."
    return

label mike_mad_condom:
    $ result = randint(0, 5)
    if result == 0:
        bree.say "What's the matter, [mike.name]?"
        bree.say "You afraid to take a few risks?"
        bree.say "To live dangerously, even a little?"
        "[mike.name]'s expression changes as I say all of this."
        "Before he was eager to please me."
        "But now he looks irritated and serious."
        "Then he pushes me off him and climbs out of bed."
        mike.say "Maybe you should get some sleep after all, [hero.name]."
        mike.say "Because you're acting pretty weird right now."
        mike.say "Like you're not really yourself."
        "[mike.name]'s words catch me off-guard, cutting me deeply."
        "I thought I was being impulsive and exciting."
        "But it looks like I've gone too far."
        "And it's turned him off me as a result."
        "That's why I just look at the floor and let him leave."
        "I feel too ashamed to argue with him."
    elif result == 1:
        bree.say "Don't be such a pussy, [mike.name]!"
        bree.say "Just pull out before the end."
        "I hear [mike.name] sigh."
        "And then I feel him getting off the bed."
        bree.say "Hey, where are you going?"
        bree.say "Aren't you forgetting something?!?"
        mike.say "Nah, [hero.name]..."
        mike.say "I'll pass."
        mike.say "You kind of just killed the mood for me."
        "I watch as [mike.name] stoops to pick up his clothes."
        "Then he walks out of the room, leaving me alone."
        "And all for the sake of a lousy condom."
    elif result == 2:
        bree.say "Seriously, [mike.name]?"
        bree.say "Just forget about it, yeah?"
        bree.say "Try to live a little for a change!"
        "[mike.name] sits up and pulls away from me."
        "Then he shakes his head and hops off the bed."
        mike.say "You know what, [hero.name]..."
        mike.say "I think we should call it a night."
        mike.say "Because you're not sounding like yourself right now."
        mike.say "Maybe in the morning you'll have sobered up."
        bree.say "What?"
        bree.say "What are you even talking about?"
        "It's no good."
        "No matter what I say, [mike.name] just grabs his clothes."
        "Then he heads straight out of the door."
        "Leaving me alone and massively frustrated too."
    elif result == 3:
        bree.say "Urgh..."
        bree.say "Really, [mike.name]?"
        bree.say "Just stick it in me already!"
        "I hear [mike.name] let out an irritated sigh."
        "Then I feel him getting out of the bed."
        bree.say "Huh?"
        bree.say "Where are you going?"
        mike.say "Back to my room, [hero.name]."
        mike.say "Until you sleep off the stupid!"
        "I'm shocked at the way [mike.name] just spoke to me."
        "So much so that he's gone before I can think of a good comeback."
        "And in the end, I fall asleep before one come to me to use in the morning too."
    elif result == 4:
        bree.say "Are you kidding me?"
        bree.say "Forget about the condom."
        bree.say "Get on with it already!"
        "I feel [mike.name] pull himself out from under me."
        "Which results in me tumbling onto the mattress."
        "Then he walks away from the bed and begins gathering his clothes."
        bree.say "Oh come on, [mike.name]!"
        bree.say "You're not leaving, are you?!?"
        mike.say "Oh yes I am!"
        mike.say "At least this way you can drop off in peace!"
        scene bg bedroom4
        $ game.room = "bedroom4"
        "With that he walks to the door and lets himself out."
        "Which leaves me alone, naked and totally frustrated!"
    else:
        bree.say "Forget that, [mike.name]!"
        bree.say "Just fuck me already!"
        bree.say "You can always pull out before the end."
        "[mike.name] shakes his head as he climbs off the bed."
        mike.say "[hero.name], I'm disappointed in you!"
        mike.say "That's never been an effecting form of birth-control."
        mike.say "And you know it!"
        "I stare at [mike.name] in sheer amazement as he gathers up his clothes."
        "Part of me can't believe he's actually walking out on me."
        "But that's exactly what he does, slamming the door behind him too!"
        "Urgh..."
        "Trust me to be able to bring my own luck to a crashing end!"
    return
return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
